# Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.

from __future__ import annotations

from dataclasses import dataclass, field
from decimal import Decimal
from typing import Any, ClassVar, Optional, Union

from ._generated_identifiers import *  # noqa: F403
from .models import Balance, Cursor, Market, Order, OrderRequest, Timestamp, WireModel, _ascii_upper, _decode_value, _model_to_wire


@dataclass(frozen=True)
class OrderAccount(WireModel):
    balance: Balance
    average_buy_price: Decimal
    average_buy_price_modified: bool
    average_buy_price_unit: Optional[str] = None


@dataclass(frozen=True)
class OrderOption(WireModel):
    provider_id: str
    order_type: Optional[OrderType] = None
    time_in_force: Optional[TimeInForce] = None


@dataclass(frozen=True)
class OrderRules(WireModel):
    market: Market
    market_name: str
    status: MarketStatus
    buy_fee_rate: Decimal
    sell_fee_rate: Decimal
    maker_buy_fee_rate: Decimal
    maker_sell_fee_rate: Decimal
    sides: list[Side]
    buy_options: list[OrderOption]
    sell_options: list[OrderOption]
    buy_price_unit: Optional[Decimal]
    sell_price_unit: Optional[Decimal]
    minimum_buy_total: Decimal
    minimum_sell_total: Decimal
    maximum_total: Decimal
    quote_account: OrderAccount
    base_account: OrderAccount


@dataclass(frozen=True)
class AssetNetwork(WireModel):
    exchange: Exchange
    asset: str
    network: Network
    provider_id: str
    deposit_enabled: bool
    withdrawal_enabled: bool
    withdrawal_fee: Optional[WithdrawalFee]
    minimum_withdrawal: Optional[Decimal]
    maximum_withdrawal: Optional[Decimal]
    memo_required: bool

    def __post_init__(self) -> None:
        object.__setattr__(self, "asset", _ascii_upper(self.asset))


@dataclass(frozen=True)
class DepositAddress(WireModel):
    exchange: Exchange
    asset: str
    network: Network
    address: Optional[str] = None
    memo: Optional[str] = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "asset", _ascii_upper(self.asset))


@dataclass(frozen=True)
class DepositAddressEntry(WireModel):
    exchange: Exchange
    asset: str
    network: Optional[Network] = None
    provider_network: Optional[str] = None
    address: Optional[str] = None
    memo: Optional[str] = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "asset", _ascii_upper(self.asset))


@dataclass(frozen=True)
class ExchangeDestination(WireModel):
    exchange: Exchange
    asset: str
    network: Network
    address: str
    memo: Optional[str] = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "asset", _ascii_upper(self.asset))


@dataclass(frozen=True)
class ChainDestination(WireModel):
    asset: str
    network: Network
    address: str
    memo: Optional[str] = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "asset", _ascii_upper(self.asset))


@dataclass(frozen=True)
class ExchangeTransferRequest(WireModel):
    asset: str
    source_network: Optional[Network]
    destination_network: Optional[Network]
    amount: Decimal

    def __post_init__(self) -> None:
        object.__setattr__(self, "asset", _ascii_upper(self.asset))


@dataclass(frozen=True)
class ChainTransferRequest(WireModel):
    asset: str
    source_network: Optional[Network]
    destination: ChainDestination
    amount: Decimal

    def __post_init__(self) -> None:
        object.__setattr__(self, "asset", _ascii_upper(self.asset))


@dataclass(frozen=True)
class TransferDestination(WireModel):
    _wire_union: ClassVar[bool] = True
    kind: str
    value: Optional[Union[ChainDestination, ExchangeDestination]] = None

    @classmethod
    def exchange(cls, value: ExchangeDestination) -> TransferDestination:
        return cls("exchange", value=value)

    @classmethod
    def chain(cls, value: ChainDestination) -> TransferDestination:
        return cls("chain", value=value)

    @classmethod
    def from_wire(cls, value: dict[str, Any]) -> TransferDestination:
        kind = value.get("kind")
        if kind == "exchange":
            for key in value:
                if key not in {"kind", "value"}:
                    raise ValueError(f"TransferDestination.exchange does not accept {key}")
            return cls.exchange(
                value=_decode_value(ExchangeDestination, value["value"]),
            )
        if kind == "chain":
            for key in value:
                if key not in {"kind", "value"}:
                    raise ValueError(f"TransferDestination.chain does not accept {key}")
            return cls.chain(
                value=_decode_value(ChainDestination, value["value"]),
            )
        raise ValueError(f"unknown TransferDestination kind: {kind}")

    def to_wire(self) -> dict[str, Any]:
        if self.kind == "exchange":
            if self.value is None:
                raise ValueError("TransferDestination.exchange requires value")
            return {
                "kind": "exchange",
                "value": _model_to_wire(self.value),
            }
        if self.kind == "chain":
            if self.value is None:
                raise ValueError("TransferDestination.chain requires value")
            return {
                "kind": "chain",
                "value": _model_to_wire(self.value),
            }
        raise ValueError(f"unknown TransferDestination kind: {self.kind}")


@dataclass(frozen=True)
class WithdrawalFee(WireModel):
    _wire_union: ClassVar[bool] = True
    kind: str
    value: Optional[Decimal] = None
    rate: Optional[Decimal] = None
    minimum: Optional[Decimal] = None
    maximum: Optional[Decimal] = None

    @classmethod
    def fixed(cls, value: Decimal) -> WithdrawalFee:
        return cls("fixed", value=value)

    @classmethod
    def from_rate(cls, rate: Decimal, minimum: Optional[Decimal] = None, maximum: Optional[Decimal] = None) -> WithdrawalFee:
        return cls("rate", rate=rate, minimum=minimum, maximum=maximum)

    @classmethod
    def from_wire(cls, value: dict[str, Any]) -> WithdrawalFee:
        kind = value.get("kind")
        if kind == "fixed":
            for key in value:
                if key not in {"kind", "value"}:
                    raise ValueError(f"WithdrawalFee.fixed does not accept {key}")
            return cls.fixed(
                value=_decode_value(Decimal, value["value"]),
            )
        if kind == "rate":
            for key in value:
                if key not in {"kind", "rate", "minimum", "maximum"}:
                    raise ValueError(f"WithdrawalFee.rate does not accept {key}")
            return cls.from_rate(
                rate=_decode_value(Decimal, value["rate"]),
                minimum=_decode_value(Optional[Decimal], value.get("minimum")),
                maximum=_decode_value(Optional[Decimal], value.get("maximum")),
            )
        raise ValueError(f"unknown WithdrawalFee kind: {kind}")

    def to_wire(self) -> dict[str, Any]:
        if self.kind == "fixed":
            if self.rate is not None:
                raise ValueError("WithdrawalFee.fixed does not accept rate")
            if self.minimum is not None:
                raise ValueError("WithdrawalFee.fixed does not accept minimum")
            if self.maximum is not None:
                raise ValueError("WithdrawalFee.fixed does not accept maximum")
            if self.value is None:
                raise ValueError("WithdrawalFee.fixed requires value")
            return {
                "kind": "fixed",
                "value": _model_to_wire(self.value),
            }
        if self.kind == "rate":
            if self.value is not None:
                raise ValueError("WithdrawalFee.rate does not accept value")
            if self.rate is None:
                raise ValueError("WithdrawalFee.rate requires rate")
            return {
                "kind": "rate",
                "rate": _model_to_wire(self.rate),
                "minimum": _model_to_wire(self.minimum),
                "maximum": _model_to_wire(self.maximum),
            }
        raise ValueError(f"unknown WithdrawalFee kind: {self.kind}")


@dataclass(frozen=True)
class TravelRuleRequirement(WireModel):
    _wire_union: ClassVar[bool] = True
    kind: str
    consent_url: Optional[str] = None

    @classmethod
    def not_required(cls) -> TravelRuleRequirement:
        return cls("not_required")

    @classmethod
    def required(cls, consent_url: Optional[str] = None) -> TravelRuleRequirement:
        return cls("required", consent_url=consent_url)

    @classmethod
    def from_wire(cls, value: dict[str, Any]) -> TravelRuleRequirement:
        kind = value.get("kind")
        if kind == "not_required":
            for key in value:
                if key not in {"kind"}:
                    raise ValueError(f"TravelRuleRequirement.not_required does not accept {key}")
            return cls.not_required(
            )
        if kind == "required":
            for key in value:
                if key not in {"kind", "consent_url"}:
                    raise ValueError(f"TravelRuleRequirement.required does not accept {key}")
            return cls.required(
                consent_url=_decode_value(Optional[str], value.get("consent_url")),
            )
        raise ValueError(f"unknown TravelRuleRequirement kind: {kind}")

    def to_wire(self) -> dict[str, Any]:
        if self.kind == "not_required":
            if self.consent_url is not None:
                raise ValueError("TravelRuleRequirement.not_required does not accept consent_url")
            return {
                "kind": "not_required",
            }
        if self.kind == "required":
            return {
                "kind": "required",
                "consent_url": _model_to_wire(self.consent_url),
            }
        raise ValueError(f"unknown TravelRuleRequirement kind: {self.kind}")


@dataclass(frozen=True)
class WithdrawalQuote(WireModel):
    fee: Optional[Decimal]
    expected_receive: Optional[Decimal]
    minimum_amount: Optional[Decimal]
    maximum_amount: Optional[Decimal]
    address_allowed: Optional[bool]
    travel_rule: TravelRuleRequirement
    expires_at: Optional[Timestamp] = None


@dataclass(frozen=True)
class TransferPlan(WireModel):
    source: Exchange
    destination: Optional[Exchange]
    request: WithdrawRequest
    quote: WithdrawalQuote
    created_at: Timestamp
    expires_at: Timestamp


@dataclass(frozen=True)
class Withdrawal(WireModel):
    id: str
    asset: str
    network: Optional[Network]
    provider_network: Optional[str]
    amount: Decimal
    fee: Optional[Decimal]
    destination: Optional[TransferDestination]
    status: WithdrawalStatus
    provider_status: str
    tx_id: Optional[str] = None
    created_at: Optional[Timestamp] = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "asset", _ascii_upper(self.asset))


@dataclass(frozen=True)
class Deposit(WireModel):
    id: str
    asset: str
    network: Optional[Network]
    provider_network: Optional[str]
    amount: Decimal
    address: Optional[str]
    memo: Optional[str]
    status: DepositStatus
    provider_status: str
    tx_id: Optional[str] = None
    created_at: Optional[Timestamp] = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "asset", _ascii_upper(self.asset))


@dataclass(frozen=True)
class CancelledOrder(WireModel):
    order_id: str
    client_id: Optional[str] = None
    market: Optional[Market] = None
    cancelled_at: Optional[Timestamp] = None


@dataclass(frozen=True)
class OrderCancelFailure(WireModel):
    order_id: Optional[str] = None
    client_id: Optional[str] = None
    market: Optional[Market] = None
    code: Optional[str] = None
    message: Optional[str] = None


@dataclass(frozen=True)
class CancelOrdersResult(WireModel):
    cancelled: list[CancelledOrder]
    failed: list[OrderCancelFailure]


@dataclass(frozen=True)
class OrderLookupRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    kind: OrderIdKind
    ids: list[str]
    market: Optional[Market] = None


@dataclass(frozen=True)
class CancelOrdersRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    kind: OrderIdKind
    ids: list[str]


@dataclass(frozen=True)
class OrderHistoryRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    market: Optional[Market] = None
    statuses: list[OrderStatus] = field(default_factory=list)
    from_: Optional[Timestamp] = field(default=None, metadata={"wire_name": "from"})
    to: Optional[Timestamp] = None
    cursor: Optional[Cursor] = None
    limit: Optional[int] = None


@dataclass(frozen=True)
class DepositAddressRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    asset: str
    network: Network
    amount: Optional[Decimal] = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "asset", _ascii_upper(self.asset))


@dataclass(frozen=True)
class WithdrawRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    asset: str
    network: Network
    amount: Decimal
    destination: TransferDestination
    client_id: Optional[str] = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "asset", _ascii_upper(self.asset))


@dataclass(frozen=True)
class TransferLookupRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    asset: str
    id: Optional[str] = None
    tx_id: Optional[str] = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "asset", _ascii_upper(self.asset))


@dataclass(frozen=True)
class TransferHistoryRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    asset: Optional[str] = None
    network: Optional[Network] = None
    cursor: Optional[Cursor] = None
    limit: Optional[int] = None

    def __post_init__(self) -> None:
        if self.asset is not None:
            object.__setattr__(self, "asset", _ascii_upper(self.asset))


@dataclass(frozen=True)
class UpbitYearCandle(WireModel):
    market: Market
    open_time: Timestamp
    korea_open_time: Optional[Timestamp]
    timestamp: Timestamp
    open: Decimal
    high: Decimal
    low: Decimal
    close: Decimal
    volume: Decimal
    quote_volume: Decimal
    first_day_of_period: str


@dataclass(frozen=True)
class UpbitOrderBookInstrument(WireModel):
    market: Market
    quote_currency: str
    tick_size: Decimal
    supported_levels: list[Decimal]


@dataclass(frozen=True)
class UpbitDepositInfo(WireModel):
    asset: str
    network: Optional[Network]
    provider_network: Optional[str]
    is_deposit_possible: bool
    deposit_impossible_reason: Optional[str]
    minimum_deposit_amount: Decimal
    minimum_deposit_confirmations: int
    decimal_precision: int

    def __post_init__(self) -> None:
        object.__setattr__(self, "asset", _ascii_upper(self.asset))


@dataclass(frozen=True)
class UpbitTravelRuleVasp(WireModel):
    vasp_name: str
    vasp_uuid: str
    depositable: bool
    withdrawable: bool


@dataclass(frozen=True)
class UpbitTravelRuleVerification(WireModel):
    deposit_uuid: str
    deposit_state: str
    verification_result: str


@dataclass(frozen=True)
class UpbitBatchCancelScope(WireModel):
    _wire_union: ClassVar[bool] = True
    kind: str
    values: Optional[Union[list[Market], list[str]]] = None

    @classmethod
    def all(cls) -> UpbitBatchCancelScope:
        return cls("all")

    @classmethod
    def quote_currencies(cls, values: list[str]) -> UpbitBatchCancelScope:
        return cls("quote_currencies", values=values)

    @classmethod
    def pairs(cls, values: list[Market]) -> UpbitBatchCancelScope:
        return cls("pairs", values=values)

    @classmethod
    def from_wire(cls, value: dict[str, Any]) -> UpbitBatchCancelScope:
        kind = value.get("kind")
        if kind == "all":
            for key in value:
                if key not in {"kind"}:
                    raise ValueError(f"UpbitBatchCancelScope.all does not accept {key}")
            return cls.all(
            )
        if kind == "quote_currencies":
            for key in value:
                if key not in {"kind", "values"}:
                    raise ValueError(f"UpbitBatchCancelScope.quote_currencies does not accept {key}")
            return cls.quote_currencies(
                values=_decode_value(list[str], value["values"]),
            )
        if kind == "pairs":
            for key in value:
                if key not in {"kind", "values"}:
                    raise ValueError(f"UpbitBatchCancelScope.pairs does not accept {key}")
            return cls.pairs(
                values=_decode_value(list[Market], value["values"]),
            )
        raise ValueError(f"unknown UpbitBatchCancelScope kind: {kind}")

    def to_wire(self) -> dict[str, Any]:
        if self.kind == "all":
            if self.values is not None:
                raise ValueError("UpbitBatchCancelScope.all does not accept values")
            return {
                "kind": "all",
            }
        if self.kind == "quote_currencies":
            if self.values is None:
                raise ValueError("UpbitBatchCancelScope.quote_currencies requires values")
            return {
                "kind": "quote_currencies",
                "values": _model_to_wire(self.values),
            }
        if self.kind == "pairs":
            if self.values is None:
                raise ValueError("UpbitBatchCancelScope.pairs requires values")
            return {
                "kind": "pairs",
                "values": _model_to_wire(self.values),
            }
        raise ValueError(f"unknown UpbitBatchCancelScope kind: {self.kind}")


@dataclass(frozen=True)
class UpbitBatchCancelRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    scope: UpbitBatchCancelScope
    excluded_pairs: Optional[list[Market]] = None
    side: Optional[Side] = None
    count: Optional[int] = None
    order_by: Optional[UpbitOrderDirection] = None


@dataclass(frozen=True)
class UpbitOrderReference(WireModel):
    _wire_union: ClassVar[bool] = True
    kind: str
    value: Optional[str] = None

    @classmethod
    def uuid(cls, value: str) -> UpbitOrderReference:
        return cls("uuid", value=value)

    @classmethod
    def identifier(cls, value: str) -> UpbitOrderReference:
        return cls("identifier", value=value)

    @classmethod
    def from_wire(cls, value: dict[str, Any]) -> UpbitOrderReference:
        kind = value.get("kind")
        if kind == "uuid":
            for key in value:
                if key not in {"kind", "value"}:
                    raise ValueError(f"UpbitOrderReference.uuid does not accept {key}")
            return cls.uuid(
                value=_decode_value(str, value["value"]),
            )
        if kind == "identifier":
            for key in value:
                if key not in {"kind", "value"}:
                    raise ValueError(f"UpbitOrderReference.identifier does not accept {key}")
            return cls.identifier(
                value=_decode_value(str, value["value"]),
            )
        raise ValueError(f"unknown UpbitOrderReference kind: {kind}")

    def to_wire(self) -> dict[str, Any]:
        if self.kind == "uuid":
            if self.value is None:
                raise ValueError("UpbitOrderReference.uuid requires value")
            return {
                "kind": "uuid",
                "value": _model_to_wire(self.value),
            }
        if self.kind == "identifier":
            if self.value is None:
                raise ValueError("UpbitOrderReference.identifier requires value")
            return {
                "kind": "identifier",
                "value": _model_to_wire(self.value),
            }
        raise ValueError(f"unknown UpbitOrderReference kind: {self.kind}")


@dataclass(frozen=True)
class UpbitOrderVolume(WireModel):
    _wire_union: ClassVar[bool] = True
    kind: str
    value: Optional[Decimal] = None

    @classmethod
    def amount(cls, value: Decimal) -> UpbitOrderVolume:
        return cls("amount", value=value)

    @classmethod
    def remain_only(cls) -> UpbitOrderVolume:
        return cls("remain_only")

    @classmethod
    def from_wire(cls, value: dict[str, Any]) -> UpbitOrderVolume:
        kind = value.get("kind")
        if kind == "amount":
            for key in value:
                if key not in {"kind", "value"}:
                    raise ValueError(f"UpbitOrderVolume.amount does not accept {key}")
            return cls.amount(
                value=_decode_value(Decimal, value["value"]),
            )
        if kind == "remain_only":
            for key in value:
                if key not in {"kind"}:
                    raise ValueError(f"UpbitOrderVolume.remain_only does not accept {key}")
            return cls.remain_only(
            )
        raise ValueError(f"unknown UpbitOrderVolume kind: {kind}")

    def to_wire(self) -> dict[str, Any]:
        if self.kind == "amount":
            if self.value is None:
                raise ValueError("UpbitOrderVolume.amount requires value")
            return {
                "kind": "amount",
                "value": _model_to_wire(self.value),
            }
        if self.kind == "remain_only":
            if self.value is not None:
                raise ValueError("UpbitOrderVolume.remain_only does not accept value")
            return {
                "kind": "remain_only",
            }
        raise ValueError(f"unknown UpbitOrderVolume kind: {self.kind}")


@dataclass(frozen=True)
class UpbitCancelAndNewOrder(WireModel):
    _wire_union: ClassVar[bool] = True
    kind: str
    volume: Optional[UpbitOrderVolume] = None
    price: Optional[Decimal] = None
    time_in_force: Optional[TimeInForce] = None

    @classmethod
    def limit(cls, volume: UpbitOrderVolume, price: Decimal, time_in_force: Optional[TimeInForce] = None) -> UpbitCancelAndNewOrder:
        return cls("limit", volume=volume, price=price, time_in_force=time_in_force)

    @classmethod
    def market_buy(cls, price: Decimal) -> UpbitCancelAndNewOrder:
        return cls("market_buy", price=price)

    @classmethod
    def market_sell(cls, volume: UpbitOrderVolume) -> UpbitCancelAndNewOrder:
        return cls("market_sell", volume=volume)

    @classmethod
    def best_buy(cls, price: Decimal, time_in_force: TimeInForce) -> UpbitCancelAndNewOrder:
        return cls("best_buy", price=price, time_in_force=time_in_force)

    @classmethod
    def best_sell(cls, volume: UpbitOrderVolume, time_in_force: TimeInForce) -> UpbitCancelAndNewOrder:
        return cls("best_sell", volume=volume, time_in_force=time_in_force)

    @classmethod
    def from_wire(cls, value: dict[str, Any]) -> UpbitCancelAndNewOrder:
        kind = value.get("kind")
        if kind == "limit":
            for key in value:
                if key not in {"kind", "volume", "price", "time_in_force"}:
                    raise ValueError(f"UpbitCancelAndNewOrder.limit does not accept {key}")
            return cls.limit(
                volume=_decode_value(UpbitOrderVolume, value["volume"]),
                price=_decode_value(Decimal, value["price"]),
                time_in_force=_decode_value(Optional[TimeInForce], value.get("time_in_force")),
            )
        if kind == "market_buy":
            for key in value:
                if key not in {"kind", "price"}:
                    raise ValueError(f"UpbitCancelAndNewOrder.market_buy does not accept {key}")
            return cls.market_buy(
                price=_decode_value(Decimal, value["price"]),
            )
        if kind == "market_sell":
            for key in value:
                if key not in {"kind", "volume"}:
                    raise ValueError(f"UpbitCancelAndNewOrder.market_sell does not accept {key}")
            return cls.market_sell(
                volume=_decode_value(UpbitOrderVolume, value["volume"]),
            )
        if kind == "best_buy":
            for key in value:
                if key not in {"kind", "price", "time_in_force"}:
                    raise ValueError(f"UpbitCancelAndNewOrder.best_buy does not accept {key}")
            return cls.best_buy(
                price=_decode_value(Decimal, value["price"]),
                time_in_force=_decode_value(TimeInForce, value["time_in_force"]),
            )
        if kind == "best_sell":
            for key in value:
                if key not in {"kind", "volume", "time_in_force"}:
                    raise ValueError(f"UpbitCancelAndNewOrder.best_sell does not accept {key}")
            return cls.best_sell(
                volume=_decode_value(UpbitOrderVolume, value["volume"]),
                time_in_force=_decode_value(TimeInForce, value["time_in_force"]),
            )
        raise ValueError(f"unknown UpbitCancelAndNewOrder kind: {kind}")

    def to_wire(self) -> dict[str, Any]:
        if self.kind == "limit":
            if self.volume is None:
                raise ValueError("UpbitCancelAndNewOrder.limit requires volume")
            if self.price is None:
                raise ValueError("UpbitCancelAndNewOrder.limit requires price")
            return {
                "kind": "limit",
                "volume": _model_to_wire(self.volume),
                "price": _model_to_wire(self.price),
                "time_in_force": _model_to_wire(self.time_in_force),
            }
        if self.kind == "market_buy":
            if self.volume is not None:
                raise ValueError("UpbitCancelAndNewOrder.market_buy does not accept volume")
            if self.time_in_force is not None:
                raise ValueError("UpbitCancelAndNewOrder.market_buy does not accept time_in_force")
            if self.price is None:
                raise ValueError("UpbitCancelAndNewOrder.market_buy requires price")
            return {
                "kind": "market_buy",
                "price": _model_to_wire(self.price),
            }
        if self.kind == "market_sell":
            if self.price is not None:
                raise ValueError("UpbitCancelAndNewOrder.market_sell does not accept price")
            if self.time_in_force is not None:
                raise ValueError("UpbitCancelAndNewOrder.market_sell does not accept time_in_force")
            if self.volume is None:
                raise ValueError("UpbitCancelAndNewOrder.market_sell requires volume")
            return {
                "kind": "market_sell",
                "volume": _model_to_wire(self.volume),
            }
        if self.kind == "best_buy":
            if self.volume is not None:
                raise ValueError("UpbitCancelAndNewOrder.best_buy does not accept volume")
            if self.price is None:
                raise ValueError("UpbitCancelAndNewOrder.best_buy requires price")
            if self.time_in_force is None:
                raise ValueError("UpbitCancelAndNewOrder.best_buy requires time_in_force")
            return {
                "kind": "best_buy",
                "price": _model_to_wire(self.price),
                "time_in_force": _model_to_wire(self.time_in_force),
            }
        if self.kind == "best_sell":
            if self.price is not None:
                raise ValueError("UpbitCancelAndNewOrder.best_sell does not accept price")
            if self.volume is None:
                raise ValueError("UpbitCancelAndNewOrder.best_sell requires volume")
            if self.time_in_force is None:
                raise ValueError("UpbitCancelAndNewOrder.best_sell requires time_in_force")
            return {
                "kind": "best_sell",
                "volume": _model_to_wire(self.volume),
                "time_in_force": _model_to_wire(self.time_in_force),
            }
        raise ValueError(f"unknown UpbitCancelAndNewOrder kind: {self.kind}")


@dataclass(frozen=True)
class UpbitCancelAndNewOrderRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    previous_order: UpbitOrderReference
    new_order: UpbitCancelAndNewOrder
    new_identifier: Optional[str] = None
    new_smp_type: Optional[UpbitSmpType] = None


@dataclass(frozen=True)
class UpbitCancelAndNewOrderResult(WireModel):
    previous_order: Order
    new_order_uuid: Optional[str] = None
    new_order_identifier: Optional[str] = None


@dataclass(frozen=True)
class BithumbNotice(WireModel):
    categories: list[str]
    title: str
    url: str
    published_at: Timestamp
    modified_at: Timestamp


@dataclass(frozen=True)
class BithumbApiKey(WireModel):
    access_key: str
    expires_at: Timestamp


@dataclass(frozen=True)
class BithumbKrwWithdrawalsRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    state: Optional[str] = None
    uuids: list[str] = field(default_factory=list)
    txids: list[str] = field(default_factory=list)
    page: Optional[int] = None
    limit: Optional[int] = None
    order_by: Optional[BithumbOrderDirection] = None


@dataclass(frozen=True)
class BithumbKrwDepositsRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    state: Optional[str] = None
    uuids: list[str] = field(default_factory=list)
    txids: list[str] = field(default_factory=list)
    page: Optional[int] = None
    limit: Optional[int] = None
    order_by: Optional[BithumbOrderDirection] = None


@dataclass(frozen=True)
class BithumbKrwTransferRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    amount: Decimal


@dataclass(frozen=True)
class BithumbKrwWithdrawal(WireModel):
    transfer_type: str
    uuid: str
    currency: str
    net_type: Optional[str]
    txid: Optional[str]
    state: str
    created_at: Optional[Timestamp]
    done_at: Optional[Timestamp]
    amount: Decimal
    fee: Decimal
    transaction_type: Optional[str] = None


@dataclass(frozen=True)
class BithumbKrwDeposit(WireModel):
    transfer_type: str
    uuid: str
    currency: str
    net_type: Optional[str]
    txid: Optional[str]
    state: str
    created_at: Optional[Timestamp]
    done_at: Optional[Timestamp]
    amount: Decimal
    fee: Decimal
    transaction_type: Optional[str] = None


@dataclass(frozen=True)
class BithumbPendingOrdersRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    market: Optional[Market] = None
    state: Optional[BithumbPendingOrderState] = None
    limit: Optional[int] = None
    order_by: Optional[BithumbOrderDirection] = None
    cursor: Optional[Cursor] = None


@dataclass(frozen=True)
class BithumbBatchOrdersRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    orders: list[OrderRequest]


@dataclass(frozen=True)
class BithumbBatchOrder(WireModel):
    order_id: str
    client_order_id: Optional[str]
    market: Market
    side: Side
    order_type: OrderType
    time_in_force: Optional[str] = None
    stp_type: Optional[str] = None
    created_at: Optional[Timestamp] = None


@dataclass(frozen=True)
class BithumbBatchOrderFailure(WireModel):
    client_order_id: Optional[str]
    time_in_force: Optional[str]
    code: str
    message: str


@dataclass(frozen=True)
class BithumbBatchOrderOutcome(WireModel):
    _wire_union: ClassVar[bool] = True
    kind: str
    value: Optional[Union[BithumbBatchOrder, BithumbBatchOrderFailure]] = None

    @classmethod
    def accepted(cls, value: BithumbBatchOrder) -> BithumbBatchOrderOutcome:
        return cls("accepted", value=value)

    @classmethod
    def rejected(cls, value: BithumbBatchOrderFailure) -> BithumbBatchOrderOutcome:
        return cls("rejected", value=value)

    @classmethod
    def from_wire(cls, value: dict[str, Any]) -> BithumbBatchOrderOutcome:
        kind = value.get("kind")
        if kind == "accepted":
            for key in value:
                if key not in {"kind", "value"}:
                    raise ValueError(f"BithumbBatchOrderOutcome.accepted does not accept {key}")
            return cls.accepted(
                value=_decode_value(BithumbBatchOrder, value["value"]),
            )
        if kind == "rejected":
            for key in value:
                if key not in {"kind", "value"}:
                    raise ValueError(f"BithumbBatchOrderOutcome.rejected does not accept {key}")
            return cls.rejected(
                value=_decode_value(BithumbBatchOrderFailure, value["value"]),
            )
        raise ValueError(f"unknown BithumbBatchOrderOutcome kind: {kind}")

    def to_wire(self) -> dict[str, Any]:
        if self.kind == "accepted":
            if self.value is None:
                raise ValueError("BithumbBatchOrderOutcome.accepted requires value")
            return {
                "kind": "accepted",
                "value": _model_to_wire(self.value),
            }
        if self.kind == "rejected":
            if self.value is None:
                raise ValueError("BithumbBatchOrderOutcome.rejected requires value")
            return {
                "kind": "rejected",
                "value": _model_to_wire(self.value),
            }
        raise ValueError(f"unknown BithumbBatchOrderOutcome kind: {self.kind}")


@dataclass(frozen=True)
class BithumbBatchOrdersResult(WireModel):
    outcomes: list[BithumbBatchOrderOutcome]


@dataclass(frozen=True)
class BithumbTwapOrdersRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    market: Optional[Market] = None
    uuids: list[str] = field(default_factory=list)
    state: Optional[BithumbTwapState] = None
    cursor: Optional[Cursor] = None
    limit: Optional[int] = None
    order_by: Optional[BithumbTwapOrderDirection] = None


@dataclass(frozen=True)
class BithumbTwapOrderRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    market: Market
    side: Side
    volume: Optional[Decimal]
    price: Optional[Decimal]
    duration: int
    frequency: int


@dataclass(frozen=True)
class BithumbTwapOrder(WireModel):
    id: str
    side: Side
    price: Decimal
    state: BithumbTwapState
    market: Market
    created_at: Timestamp
    volume: Decimal
    finished_at: Optional[Timestamp]
    total_order_count: int
    total_trades_count: int
    progress_count: int
    total_executed_amount: Decimal
    total_executed_volume: Decimal
    avg_trade_price: Decimal
    wallet_id: Optional[str] = None
    canceled_at: Optional[Timestamp] = None
    cancel_type: Optional[str] = None


@dataclass(frozen=True)
class BithumbAssetFee(WireModel):
    display_name: str
    asset: str
    networks: list[BithumbNetworkFee]

    def __post_init__(self) -> None:
        object.__setattr__(self, "asset", _ascii_upper(self.asset))


@dataclass(frozen=True)
class BithumbNetworkFee(WireModel):
    network: Network
    provider_name: str
    deposit_fee: Decimal
    minimum_deposit: Decimal
    withdrawal_fee: WithdrawalFee
    minimum_withdrawal: Decimal


@dataclass(frozen=True)
class BinanceMarkPrice(WireModel):
    market: Market
    mark_price: Decimal
    index_price: Decimal
    estimated_settle_price: Optional[Decimal]
    last_funding_rate: Decimal
    interest_rate: Decimal
    next_funding_time: Timestamp
    time: Timestamp


@dataclass(frozen=True)
class BinanceOpenInterest(WireModel):
    market: Market
    open_interest: Decimal
    time: Timestamp


@dataclass(frozen=True)
class BinanceAggregateTradesRequest(WireModel):
    __wire_strict__: ClassVar[bool] = True
    market: Market
    from_id: Optional[int] = None
    start_time: Optional[Timestamp] = None
    end_time: Optional[Timestamp] = None
    limit: Optional[int] = None


@dataclass(frozen=True)
class BinanceAggregateTrade(WireModel):
    market: Market
    aggregate_id: int
    first_trade_id: int
    last_trade_id: int
    timestamp: Timestamp
    price: Decimal
    quantity: Decimal
    normal_quantity: Optional[Decimal]
    taker_side: Side


@dataclass(frozen=True)
class HyperliquidMidPrice(WireModel):
    market: Market
    price: Decimal


__all__ = [
    "OrderAccount",
    "OrderOption",
    "OrderRules",
    "AssetNetwork",
    "DepositAddress",
    "DepositAddressEntry",
    "ExchangeDestination",
    "ChainDestination",
    "ExchangeTransferRequest",
    "ChainTransferRequest",
    "TransferDestination",
    "WithdrawalFee",
    "TravelRuleRequirement",
    "WithdrawalQuote",
    "TransferPlan",
    "Withdrawal",
    "Deposit",
    "CancelledOrder",
    "OrderCancelFailure",
    "CancelOrdersResult",
    "OrderLookupRequest",
    "CancelOrdersRequest",
    "OrderHistoryRequest",
    "DepositAddressRequest",
    "WithdrawRequest",
    "TransferLookupRequest",
    "TransferHistoryRequest",
    "UpbitYearCandle",
    "UpbitOrderBookInstrument",
    "UpbitDepositInfo",
    "UpbitTravelRuleVasp",
    "UpbitTravelRuleVerification",
    "UpbitBatchCancelScope",
    "UpbitBatchCancelRequest",
    "UpbitOrderReference",
    "UpbitOrderVolume",
    "UpbitCancelAndNewOrder",
    "UpbitCancelAndNewOrderRequest",
    "UpbitCancelAndNewOrderResult",
    "BithumbNotice",
    "BithumbApiKey",
    "BithumbKrwWithdrawalsRequest",
    "BithumbKrwDepositsRequest",
    "BithumbKrwTransferRequest",
    "BithumbKrwWithdrawal",
    "BithumbKrwDeposit",
    "BithumbPendingOrdersRequest",
    "BithumbBatchOrdersRequest",
    "BithumbBatchOrder",
    "BithumbBatchOrderFailure",
    "BithumbBatchOrderOutcome",
    "BithumbBatchOrdersResult",
    "BithumbTwapOrdersRequest",
    "BithumbTwapOrderRequest",
    "BithumbTwapOrder",
    "BithumbAssetFee",
    "BithumbNetworkFee",
    "BinanceMarkPrice",
    "BinanceOpenInterest",
    "BinanceAggregateTradesRequest",
    "BinanceAggregateTrade",
    "HyperliquidMidPrice",
]
