# Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.

from __future__ import annotations

from typing import Any, Optional, TYPE_CHECKING, Union

from . import _api
from . import models as _models

class _GeneratedProviderRuntime:
    if TYPE_CHECKING:
        _handle: Any

        async def _call(self, *args: Any, **kwargs: Any) -> Any: ...

        def _provider_market_stream(self, *args: Any, **kwargs: Any) -> Any: ...

        def _provider_account_stream(self, *args: Any, **kwargs: Any) -> Any: ...

class UpbitMarketStream(_api.MarketStream[Union[_api.StreamEvent[_models.UpbitMarketStreamEvent], _api.StreamError]]):
    """Full-fidelity provider stream."""


class UpbitAccountStream(_api.AccountStream[Union[_api.StreamEvent[_models.UpbitAccountStreamEvent], _api.StreamError]]):
    """Full-fidelity provider stream."""


class BithumbMarketStream(_api.MarketStream[Union[_api.StreamEvent[_models.BithumbMarketEvent], _api.StreamError]]):
    """Full-fidelity provider stream."""


class BithumbAccountStream(_api.AccountStream[Union[_api.StreamEvent[_models.BithumbAccountEvent], _api.StreamError]]):
    """Full-fidelity provider stream."""


class BinanceMarketStream(_api.MarketStream[Union[_api.StreamEvent[_models.BinanceMarketEvent], _api.StreamError]]):
    """Full-fidelity provider stream."""


class BinanceAccountStream(_api.AccountStream[Union[_api.StreamEvent[_models.BinanceAccountStreamEvent], _api.StreamError]]):
    """Full-fidelity provider stream."""


__all__ = (
    "UpbitMarketStream",
    "UpbitAccountStream",
    "BithumbMarketStream",
    "BithumbAccountStream",
    "BinanceMarketStream",
    "BinanceAccountStream",
)

class _GeneratedUpbitProviderMethods(_GeneratedProviderRuntime):
    async def subscribe_detailed(self, subscription: _models.Subscription) -> UpbitMarketStream:
        value = await self._call(self._handle.subscribe_detailed(subscription.to_wire()))
        return self._provider_market_stream(value, UpbitMarketStream, _models.UpbitMarketStreamEvent.from_wire)
    async def subscribe_detailed_with(self, subscription: _models.Subscription, config: _models.StreamConfig) -> UpbitMarketStream:
        value = await self._call(self._handle.subscribe_detailed_with(subscription.to_wire(), config.to_wire()))
        return self._provider_market_stream(value, UpbitMarketStream, _models.UpbitMarketStreamEvent.from_wire)
    async def subscribe_detailed_account(self) -> UpbitAccountStream:
        value = await self._call(self._handle.subscribe_detailed_account)
        return self._provider_account_stream(value, UpbitAccountStream, _models.UpbitAccountStreamEvent.from_wire)
    async def subscribe_detailed_account_with(self, config: _models.StreamConfig) -> UpbitAccountStream:
        value = await self._call(self._handle.subscribe_detailed_account_with(config.to_wire()))
        return self._provider_account_stream(value, UpbitAccountStream, _models.UpbitAccountStreamEvent.from_wire)
    async def test_order_detail(self, request: _models.OrderRequest) -> _models.UpbitOrderResponse:
        value = await self._call(self._handle.test_order_detail(request.to_wire()))
        return _models.UpbitOrderResponse.from_wire(value)
    async def place_order_detail(self, request: _models.OrderRequest) -> _models.UpbitOrderResponse:
        value = await self._call(self._handle.place_order_detail(request.to_wire()))
        return _models.UpbitOrderResponse.from_wire(value)
    async def cancel_order_detail(self, market: _models.Market, order_id: str) -> _models.UpbitOrderResponse:
        value = await self._call(self._handle.cancel_order_detail(market.to_wire(), order_id))
        return _models.UpbitOrderResponse.from_wire(value)
    async def cancel_order_by_client_id_detail(self, market: _models.Market, client_id: str) -> _models.UpbitOrderResponse:
        value = await self._call(self._handle.cancel_order_by_client_id_detail(market.to_wire(), client_id))
        return _models.UpbitOrderResponse.from_wire(value)
    async def orders_by_ids_detail(self, request: _models.OrderLookupRequest) -> list[_models.UpbitOrderResponse]:
        value = await self._call(self._handle.orders_by_ids_detail(request.to_wire()))
        return [_models.UpbitOrderResponse.from_wire(item) for item in value]
    async def cancel_orders_detail(self, request: _models.CancelOrdersRequest) -> _models.UpbitCancelOrdersResponse:
        value = await self._call(self._handle.cancel_orders_detail(request.to_wire()))
        return _models.UpbitCancelOrdersResponse.from_wire(value)
    async def deposit_detail(self, request: _models.TransferLookupRequest) -> _models.UpbitDepositResponse:
        value = await self._call(self._handle.deposit_detail(request.to_wire()))
        return _models.UpbitDepositResponse.from_wire(value)
    async def withdrawal_detail(self, request: _models.TransferLookupRequest) -> _models.UpbitWithdrawalResponse:
        value = await self._call(self._handle.withdrawal_detail(request.to_wire()))
        return _models.UpbitWithdrawalResponse.from_wire(value)
    async def cancel_withdrawal_detail(self, withdrawal_id: str) -> _models.UpbitCancelWithdrawalResponse:
        value = await self._call(self._handle.cancel_withdrawal_detail(withdrawal_id))
        return _models.UpbitCancelWithdrawalResponse.from_wire(value)
    async def cancel_and_new_order_detail(self, request: _models.UpbitCancelAndNewOrderRequest) -> _models.UpbitCancelAndNewOrderDetailResult:
        value = await self._call(self._handle.cancel_and_new_order_detail(request.to_wire()))
        return _models.UpbitCancelAndNewOrderDetailResult.from_wire(value)

class _GeneratedBithumbProviderMethods(_GeneratedProviderRuntime):
    async def order_book_snapshot(self, market: _models.Market, depth: Optional[int] = None) -> _models.BithumbOrderBookSnapshot:
        value = await self._call(self._handle.order_book_snapshot(market.to_wire(), depth))
        return _models.BithumbOrderBookSnapshot.from_wire(value)
    async def subscribe_detailed(self, subscription: _models.Subscription) -> BithumbMarketStream:
        value = await self._call(self._handle.subscribe_detailed(subscription.to_wire()))
        return self._provider_market_stream(value, BithumbMarketStream, _models.BithumbMarketEvent.from_wire)
    async def subscribe_detailed_with(self, subscription: _models.Subscription, config: _models.StreamConfig) -> BithumbMarketStream:
        value = await self._call(self._handle.subscribe_detailed_with(subscription.to_wire(), config.to_wire()))
        return self._provider_market_stream(value, BithumbMarketStream, _models.BithumbMarketEvent.from_wire)
    async def subscribe_detailed_account(self) -> BithumbAccountStream:
        value = await self._call(self._handle.subscribe_detailed_account)
        return self._provider_account_stream(value, BithumbAccountStream, _models.BithumbAccountEvent.from_wire)
    async def subscribe_detailed_account_with(self, config: _models.StreamConfig) -> BithumbAccountStream:
        value = await self._call(self._handle.subscribe_detailed_account_with(config.to_wire()))
        return self._provider_account_stream(value, BithumbAccountStream, _models.BithumbAccountEvent.from_wire)
    async def orders_by_ids_detail(self, request: _models.OrderLookupRequest) -> _models.BithumbOrdersResponse:
        value = await self._call(self._handle.orders_by_ids_detail(request.to_wire()))
        return _models.BithumbOrdersResponse.from_wire(value)
    async def place_order_detail(self, request: _models.OrderRequest) -> _models.BithumbOrderResponse:
        value = await self._call(self._handle.place_order_detail(request.to_wire()))
        return _models.BithumbOrderResponse.from_wire(value)
    async def cancel_order_detail(self, market: _models.Market, order_id: str) -> _models.BithumbCancelOrderResponse:
        value = await self._call(self._handle.cancel_order_detail(market.to_wire(), order_id))
        return _models.BithumbCancelOrderResponse.from_wire(value)
    async def cancel_order_by_client_id_detail(self, market: _models.Market, client_id: str) -> _models.BithumbCancelOrderResponse:
        value = await self._call(self._handle.cancel_order_by_client_id_detail(market.to_wire(), client_id))
        return _models.BithumbCancelOrderResponse.from_wire(value)
    async def cancel_orders_detail(self, request: _models.CancelOrdersRequest) -> _models.BithumbCancelOrdersResponse:
        value = await self._call(self._handle.cancel_orders_detail(request.to_wire()))
        return _models.BithumbCancelOrdersResponse.from_wire(value)
    async def deposit_detail(self, request: _models.TransferLookupRequest) -> _models.BithumbDepositResponse:
        value = await self._call(self._handle.deposit_detail(request.to_wire()))
        return _models.BithumbDepositResponse.from_wire(value)
    async def withdrawal_detail(self, request: _models.TransferLookupRequest) -> _models.BithumbWithdrawalResponse:
        value = await self._call(self._handle.withdrawal_detail(request.to_wire()))
        return _models.BithumbWithdrawalResponse.from_wire(value)
    async def cancel_withdrawal_detail(self, withdrawal_id: str) -> _models.BithumbCancelWithdrawalResponse:
        value = await self._call(self._handle.cancel_withdrawal_detail(withdrawal_id))
        return _models.BithumbCancelWithdrawalResponse.from_wire(value)

class _GeneratedBinanceProviderMethods(_GeneratedProviderRuntime):
    async def place_order_detail(self, request: _models.OrderRequest) -> _models.BinanceOrderResponse:
        value = await self._call(self._handle.place_order_detail(request.to_wire()))
        return _models.BinanceOrderResponse.from_wire(value)
    async def cancel_order_detail(self, market: _models.Market, order_id: str) -> _models.BinanceOrderResponse:
        value = await self._call(self._handle.cancel_order_detail(market.to_wire(), order_id))
        return _models.BinanceOrderResponse.from_wire(value)
    async def cancel_order_by_client_id_detail(self, market: _models.Market, client_id: str) -> _models.BinanceOrderResponse:
        value = await self._call(self._handle.cancel_order_by_client_id_detail(market.to_wire(), client_id))
        return _models.BinanceOrderResponse.from_wire(value)
    async def subscribe_detailed(self, subscription: _models.Subscription) -> BinanceMarketStream:
        value = await self._call(self._handle.subscribe_detailed(subscription.to_wire()))
        return self._provider_market_stream(value, BinanceMarketStream, _models.BinanceMarketEvent.from_wire)
    async def subscribe_detailed_with(self, subscription: _models.Subscription, config: _models.StreamConfig) -> BinanceMarketStream:
        value = await self._call(self._handle.subscribe_detailed_with(subscription.to_wire(), config.to_wire()))
        return self._provider_market_stream(value, BinanceMarketStream, _models.BinanceMarketEvent.from_wire)
    async def subscribe_detailed_account(self) -> BinanceAccountStream:
        value = await self._call(self._handle.subscribe_detailed_account)
        return self._provider_account_stream(value, BinanceAccountStream, _models.BinanceAccountStreamEvent.from_wire)
    async def subscribe_detailed_account_with(self, config: _models.StreamConfig) -> BinanceAccountStream:
        value = await self._call(self._handle.subscribe_detailed_account_with(config.to_wire()))
        return self._provider_account_stream(value, BinanceAccountStream, _models.BinanceAccountStreamEvent.from_wire)

class _GeneratedHyperliquidProviderMethods(_GeneratedProviderRuntime):
    async def all_mids_detail(self) -> _models.HyperliquidAllMids:
        value = await self._call(self._handle.all_mids_detail)
        return _models.HyperliquidAllMids.from_wire(value)
    async def perpetual_meta(self) -> _models.HyperliquidProviderResponse:
        value = await self._call(self._handle.perpetual_meta)
        return _models.HyperliquidProviderResponse.from_wire(value)
    async def perpetual_meta_and_asset_contexts(self) -> _models.HyperliquidProviderResponse:
        value = await self._call(self._handle.perpetual_meta_and_asset_contexts)
        return _models.HyperliquidProviderResponse.from_wire(value)
    async def clearinghouse_state_detail(self) -> _models.HyperliquidProviderResponse:
        value = await self._call(self._handle.clearinghouse_state_detail)
        return _models.HyperliquidProviderResponse.from_wire(value)
    async def frontend_open_orders_detail(self) -> _models.HyperliquidProviderResponse:
        value = await self._call(self._handle.frontend_open_orders_detail)
        return _models.HyperliquidProviderResponse.from_wire(value)
    async def place_order_detail(self, request: _models.OrderRequest) -> _models.HyperliquidOrderActionResponse:
        value = await self._call(self._handle.place_order_detail(request.to_wire()))
        return _models.HyperliquidOrderActionResponse.from_wire(value)
    async def cancel_order_detail(self, market: _models.Market, order_id: str) -> _models.HyperliquidProviderResponse:
        value = await self._call(self._handle.cancel_order_detail(market.to_wire(), order_id))
        return _models.HyperliquidProviderResponse.from_wire(value)
