# Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.

from __future__ import annotations

from typing import Any, Awaitable, Callable, Optional, TypeVar, Union

from ._api import AccountStream, InvalidRequestError, MarketStream, StreamError, StreamEvent
from .models import *  # noqa: F403
from .models import _model_from_wire

T = TypeVar("T")


class _GeneratedNativeClientDelegateApi:
    _client: Any
    _native_module: Any

    async def _call(self, method: Callable[..., Awaitable[T]], *args: Any) -> T:
        raise NotImplementedError

    def _market_stream(self, source: Any) -> MarketStream[Union[StreamEvent[MarketEvent], StreamError]]:
        raise NotImplementedError

    def _account_stream(self, source: Any) -> AccountStream[Union[StreamEvent[AccountEvent], StreamError]]:
        raise NotImplementedError

    async def markets(self, kind: MarketKind) -> list[MarketInfo]:
        value = await self._call(self._client.markets, kind)
        return [_model_from_wire("MarketInfo", item) for item in value]

    async def trades(self, market: Market, limit: Optional[int] = None) -> list[Trade]:
        value = await self._call(self._client.trades, market, limit)
        return [_model_from_wire("Trade", item) for item in value]

    async def order_book(self, market: Market, depth: Optional[int] = None) -> OrderBook:
        value = await self._call(self._client.order_book, market, depth)
        return _model_from_wire("OrderBook", value)

    async def ticker(self, market: Market) -> Ticker:
        value = await self._call(self._client.ticker, market)
        return _model_from_wire("Ticker", value)

    async def candles(self, request: CandleRequest) -> list[Candle]:
        value = await self._call(self._client.candles, request)
        return [_model_from_wire("Candle", item) for item in value]

    async def subscribe(self, subscription: Subscription, config: StreamConfig) -> MarketStream[Union[StreamEvent[MarketEvent], StreamError]]:
        if not subscription.markets:
            raise InvalidRequestError("markets", "a subscription needs at least one market")
        if not subscription.feeds:
            raise InvalidRequestError("feeds", "a subscription needs at least one feed")
        value = await self._call(self._client.subscribe, subscription, config)
        return self._market_stream(value)

    async def balances(self) -> list[Balance]:
        value = await self._call(self._client.balances)
        return [_model_from_wire("Balance", item) for item in value]

    async def asset_networks(self, asset: str) -> list[AssetNetwork]:
        value = await self._call(self._client.asset_networks, asset)
        return [_model_from_wire("AssetNetwork", item) for item in value]

    async def deposit_address(self, request: DepositAddressRequest) -> DepositAddress:
        value = await self._call(self._client.deposit_address, request)
        return _model_from_wire("DepositAddress", value)

    async def prepare_withdrawal(self, request: WithdrawRequest) -> WithdrawalQuote:
        value = await self._call(self._client.prepare_withdrawal, request)
        return _model_from_wire("WithdrawalQuote", value)

    async def withdraw(self, request: WithdrawRequest) -> Withdrawal:
        value = await self._call(self._client.withdraw, request)
        return _model_from_wire("Withdrawal", value)

    async def deposits(self, request: TransferHistoryRequest) -> Page[Deposit]:
        value = await self._call(self._client.deposits, request)
        return _model_from_wire("DepositPage", value)

    async def withdrawals(self, request: TransferHistoryRequest) -> Page[Withdrawal]:
        value = await self._call(self._client.withdrawals, request)
        return _model_from_wire("WithdrawalPage", value)

    async def open_orders(self, market: Optional[Market] = None) -> list[Order]:
        method = self._client.open_orders if market is None else self._client.open_orders_on
        value = await self._call(method, *(() if market is None else (market,)))
        return [_model_from_wire("Order", item) for item in value]

    async def order(self, market: Market, order_id: str) -> Order:
        value = await self._call(self._client.order, market, order_id)
        return _model_from_wire("Order", value)

    async def order_by_client_id(self, market: Market, client_id: str) -> Order:
        value = await self._call(self._client.order_by_client_id, market, client_id)
        return _model_from_wire("Order", value)

    async def orders_by_ids(self, request: OrderLookupRequest) -> list[Order]:
        value = await self._call(self._client.orders_by_ids, request)
        return [_model_from_wire("Order", item) for item in value]

    async def order_history(self, request: OrderHistoryRequest) -> Page[Order]:
        value = await self._call(self._client.order_history, request)
        return _model_from_wire("OrderPage", value)

    async def subscribe_account(self, config: StreamConfig) -> AccountStream[Union[StreamEvent[AccountEvent], StreamError]]:
        value = await self._call(self._client.subscribe_account, config)
        return self._account_stream(value)

    async def place_order(self, request: OrderRequest) -> Order:
        value = await self._call(self._client.place_order, request)
        return _model_from_wire("Order", value)

    async def cancel_order(self, market: Market, order_id: str) -> None:
        await self._call(self._client.cancel_order, market, order_id)
        return None

    async def cancel_order_by_client_id(self, market: Market, client_id: str) -> None:
        await self._call(self._client.cancel_order_by_client_id, market, client_id)
        return None

    async def positions(self, market: Optional[Market] = None) -> list[Position]:
        method = self._client.positions if market is None else self._client.positions_on
        value = await self._call(method, *(() if market is None else (market,)))
        return [_model_from_wire("Position", item) for item in value]

    async def margin_summary(self) -> MarginSummary:
        value = await self._call(self._client.margin_summary)
        return _model_from_wire("MarginSummary", value)

    async def funding_rates(self, request: HistoryRequest) -> Page[FundingRate]:
        value = await self._call(self._client.funding_rates, request)
        return _model_from_wire("FundingRatePage", value)

    async def funding_payments(self, request: HistoryRequest) -> Page[FundingPayment]:
        value = await self._call(self._client.funding_payments, request)
        return _model_from_wire("FundingPaymentPage", value)

    async def set_margin(self, request: MarginRequest) -> None:
        await self._call(self._client.set_margin, request)
        return None

    async def prepare_transfer_to(self, destination: _GeneratedNativeClientDelegateApi, request: ExchangeTransferRequest) -> TransferPlan:
        value = await self._call(self._client.prepare_transfer_to, destination._client, request)
        return _model_from_wire("TransferPlan", value)

    async def prepare_transfer_to_chain(self, request: ChainTransferRequest) -> TransferPlan:
        value = await self._call(self._client.prepare_transfer_to_chain, request)
        return _model_from_wire("TransferPlan", value)

    async def execute_transfer(self, plan: TransferPlan) -> Withdrawal:
        value = await self._call(self._client.execute_transfer, plan)
        return _model_from_wire("Withdrawal", value)


__all__ = ["_GeneratedNativeClientDelegateApi"]
