from typing import Any, AsyncIterator, Awaitable, Optional


Wire = dict[str, Any]


class MaxtError(Exception):
    kind: str
    wire: Wire


class NativeMarketStream(AsyncIterator[Wire]):
    def __aiter__(self) -> NativeMarketStream: ...
    def __anext__(self) -> Awaitable[Wire]: ...
    def aclose(self) -> Awaitable[None]: ...


class NativeAccountStream(AsyncIterator[Wire]):
    def __aiter__(self) -> NativeAccountStream: ...
    def __anext__(self) -> Awaitable[Wire]: ...
    def aclose(self) -> Awaitable[None]: ...


class NativeClient:
    @staticmethod
    def from_adapter(adapter: Any) -> NativeClient: ...

    @property
    def exchange(self) -> str: ...

    def supports(self, feature: Any) -> bool: ...
    def markets(self, kind: Any) -> Awaitable[list[Wire]]: ...
    def trades(
        self,
        market: Any,
        limit: Optional[int] = ...,
    ) -> Awaitable[list[Wire]]: ...
    def order_book(
        self,
        market: Any,
        depth: Optional[int] = ...,
    ) -> Awaitable[Wire]: ...
    def ticker(self, market: Any) -> Awaitable[Wire]: ...
    def candles(self, request: Any) -> Awaitable[list[Wire]]: ...
    def subscribe(
        self,
        subscription: Any,
        config: Any,
    ) -> Awaitable[NativeMarketStream]: ...
    def subscribe_with(
        self,
        subscription: Any,
        config: Any,
    ) -> Awaitable[NativeMarketStream]: ...
    def balances(self) -> Awaitable[list[Wire]]: ...
    def open_orders(self) -> Awaitable[list[Wire]]: ...
    def open_orders_on(self, market: Any) -> Awaitable[list[Wire]]: ...
    def subscribe_account(self, config: Any) -> Awaitable[NativeAccountStream]: ...
    def subscribe_account_with(self, config: Any) -> Awaitable[NativeAccountStream]: ...
    def place_order(self, request: Any) -> Awaitable[Wire]: ...
    def cancel_order(self, market: Any, order_id: str) -> Awaitable[Wire]: ...
    def positions(self) -> Awaitable[list[Wire]]: ...
    def positions_on(self, market: Any) -> Awaitable[list[Wire]]: ...
    def margin_summary(self) -> Awaitable[Wire]: ...
    def funding_rates(self, request: Any) -> Awaitable[Wire]: ...
    def funding_payments(self, request: Any) -> Awaitable[Wire]: ...
    def set_margin(self, request: Any) -> Awaitable[None]: ...


class NativeUpbitAdapter:
    def __init__(
        self,
        *,
        region: str = ...,
        access_key: Optional[str] = ...,
        secret_key: Optional[str] = ...,
    ) -> None: ...

    @property
    def region(self) -> str: ...

    @property
    def authenticated(self) -> bool: ...

    def client(self) -> NativeClient: ...
    def order_books(
        self,
        markets: Any,
        depth: Optional[int] = ...,
    ) -> Awaitable[list[Wire]]: ...
    def tickers(self, markets: Any) -> Awaitable[list[Wire]]: ...
    def market_events(self) -> Awaitable[list[Wire]]: ...


class NativeBithumbAdapter:
    def __init__(
        self,
        *,
        access_key: Optional[str] = ...,
        secret_key: Optional[str] = ...,
    ) -> None: ...

    @property
    def authenticated(self) -> bool: ...

    def client(self) -> NativeClient: ...
    def market_warnings(self) -> Awaitable[list[Wire]]: ...
    def market_alerts(self) -> Awaitable[list[Wire]]: ...


class NativeBinanceListenKey:
    @property
    def value(self) -> str: ...


class NativeBinanceAdapter:
    def __init__(
        self,
        *,
        venue: str = ...,
        api_key: Optional[str] = ...,
        secret_key: Optional[str] = ...,
    ) -> None: ...

    @property
    def venue(self) -> str: ...

    @property
    def authenticated(self) -> bool: ...

    def client(self) -> NativeClient: ...
    def spot_symbol_filters(self, market: Any) -> Awaitable[Wire]: ...
    def spot_order(self, market: Any, order_id: str) -> Awaitable[Wire]: ...
    def usd_m_create_listen_key(self) -> Awaitable[NativeBinanceListenKey]: ...
    def usd_m_keepalive_listen_key(
        self,
        key: NativeBinanceListenKey,
    ) -> Awaitable[None]: ...
    def usd_m_close_listen_key(
        self,
        key: NativeBinanceListenKey,
    ) -> Awaitable[None]: ...


class NativeHyperliquidAdapter:
    def __init__(
        self,
        *,
        testnet: bool = ...,
        address: Optional[str] = ...,
        private_key: Optional[str] = ...,
    ) -> None: ...

    @property
    def is_testnet(self) -> bool: ...

    @property
    def authenticated(self) -> bool: ...

    def client(self) -> NativeClient: ...
    def non_funding_ledger(
        self,
        from_ns: Optional[int] = ...,
        to_ns: Optional[int] = ...,
        cursor: Optional[str] = ...,
        limit: Optional[int] = ...,
    ) -> Awaitable[Wire]: ...
    def asset_context(self, market: Any) -> Awaitable[Wire]: ...
