// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.

use super::*;

pub(crate) fn network_from_wire(value: String) -> maxt::Network {
    match value.as_str() {
        "bitcoin" => maxt::Network::Bitcoin,
        "ethereum" => maxt::Network::Ethereum,
        "arbitrum" => maxt::Network::Arbitrum,
        "bnb_smart_chain" => maxt::Network::BnbSmartChain,
        "tron" => maxt::Network::Tron,
        "solana" => maxt::Network::Solana,
        "polygon" => maxt::Network::Polygon,
        "base" => maxt::Network::Base,
        "optimism" => maxt::Network::Optimism,
        "avalanche_c" => maxt::Network::AvalancheC,
        "xrp_ledger" => maxt::Network::XrpLedger,
        "stellar" => maxt::Network::Stellar,
        "cosmos" => maxt::Network::Cosmos,
        "aptos" => maxt::Network::Aptos,
        "sui" => maxt::Network::Sui,
        "ton" => maxt::Network::Ton,
        "near" => maxt::Network::Near,
        "polkadot" => maxt::Network::Polkadot,
        _ => maxt::Network::Other(value),
    }
}

pub(crate) fn network_to_wire(value: maxt::Network) -> String {
    value.id().to_owned()
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WireWithdrawalStatus {
    Pending,
    Processing,
    Completed,
    Cancelled,
    Failed,
    Unknown,
}

impl From<maxt::WithdrawalStatus> for WireWithdrawalStatus {
    fn from(value: maxt::WithdrawalStatus) -> Self {
        match value {
            maxt::WithdrawalStatus::Pending => Self::Pending,
            maxt::WithdrawalStatus::Processing => Self::Processing,
            maxt::WithdrawalStatus::Completed => Self::Completed,
            maxt::WithdrawalStatus::Cancelled => Self::Cancelled,
            maxt::WithdrawalStatus::Failed => Self::Failed,
            maxt::WithdrawalStatus::Unknown => Self::Unknown,
            _ => Self::Unknown,
        }
    }
}

impl From<WireWithdrawalStatus> for maxt::WithdrawalStatus {
    fn from(value: WireWithdrawalStatus) -> Self {
        match value {
            WireWithdrawalStatus::Pending => Self::Pending,
            WireWithdrawalStatus::Processing => Self::Processing,
            WireWithdrawalStatus::Completed => Self::Completed,
            WireWithdrawalStatus::Cancelled => Self::Cancelled,
            WireWithdrawalStatus::Failed => Self::Failed,
            WireWithdrawalStatus::Unknown => Self::Unknown,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WireDepositStatus {
    Pending,
    Completed,
    Failed,
    Unknown,
}

impl From<maxt::DepositStatus> for WireDepositStatus {
    fn from(value: maxt::DepositStatus) -> Self {
        match value {
            maxt::DepositStatus::Pending => Self::Pending,
            maxt::DepositStatus::Completed => Self::Completed,
            maxt::DepositStatus::Failed => Self::Failed,
            maxt::DepositStatus::Unknown => Self::Unknown,
            _ => Self::Unknown,
        }
    }
}

impl From<WireDepositStatus> for maxt::DepositStatus {
    fn from(value: WireDepositStatus) -> Self {
        match value {
            WireDepositStatus::Pending => Self::Pending,
            WireDepositStatus::Completed => Self::Completed,
            WireDepositStatus::Failed => Self::Failed,
            WireDepositStatus::Unknown => Self::Unknown,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireOrderAccount {
    pub balance: WireBalance,
    pub average_buy_price: String,
    pub average_buy_price_modified: bool,
    pub average_buy_price_unit: Option<String>,
}

impl From<maxt::OrderAccount> for WireOrderAccount {
    fn from(value: maxt::OrderAccount) -> Self {
        Self {
            balance: value.balance.into(),
            average_buy_price: decimal_to_wire(value.average_buy_price),
            average_buy_price_modified: value.average_buy_price_modified,
            average_buy_price_unit: value.average_buy_price_unit,
        }
    }
}

impl TryFrom<WireOrderAccount> for maxt::OrderAccount {
    type Error = NativeError;

    fn try_from(value: WireOrderAccount) -> Result<Self, Self::Error> {
        Ok(Self {
            balance: value.balance.try_into()?,
            average_buy_price: decimal_from_wire(&value.average_buy_price, "average_buy_price")
                .map_err(NativeError::from)?,
            average_buy_price_modified: value.average_buy_price_modified,
            average_buy_price_unit: value.average_buy_price_unit,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireOrderOption {
    pub provider_id: String,
    pub order_type: Option<WireOrderType>,
    pub time_in_force: Option<WireTimeInForce>,
}

impl From<maxt::OrderOption> for WireOrderOption {
    fn from(value: maxt::OrderOption) -> Self {
        Self {
            provider_id: value.provider_id,
            order_type: value.order_type.map(Into::into),
            time_in_force: value.time_in_force.map(Into::into),
        }
    }
}

impl TryFrom<WireOrderOption> for maxt::OrderOption {
    type Error = NativeError;

    fn try_from(value: WireOrderOption) -> Result<Self, Self::Error> {
        Ok(Self {
            provider_id: value.provider_id,
            order_type: value.order_type.map(Into::into),
            time_in_force: value.time_in_force.map(Into::into),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireOrderRules {
    pub market: WireMarket,
    pub market_name: String,
    pub status: WireMarketStatus,
    pub buy_fee_rate: String,
    pub sell_fee_rate: String,
    pub maker_buy_fee_rate: String,
    pub maker_sell_fee_rate: String,
    pub sides: Vec<WireSide>,
    pub buy_options: Vec<WireOrderOption>,
    pub sell_options: Vec<WireOrderOption>,
    pub buy_price_unit: Option<String>,
    pub sell_price_unit: Option<String>,
    pub minimum_buy_total: String,
    pub minimum_sell_total: String,
    pub maximum_total: String,
    pub quote_account: WireOrderAccount,
    pub base_account: WireOrderAccount,
}

impl From<maxt::OrderRules> for WireOrderRules {
    fn from(value: maxt::OrderRules) -> Self {
        Self {
            market: value.market.into(),
            market_name: value.market_name,
            status: value.status.into(),
            buy_fee_rate: decimal_to_wire(value.buy_fee_rate),
            sell_fee_rate: decimal_to_wire(value.sell_fee_rate),
            maker_buy_fee_rate: decimal_to_wire(value.maker_buy_fee_rate),
            maker_sell_fee_rate: decimal_to_wire(value.maker_sell_fee_rate),
            sides: value.sides.into_iter().map(Into::into).collect(),
            buy_options: value.buy_options.into_iter().map(Into::into).collect(),
            sell_options: value.sell_options.into_iter().map(Into::into).collect(),
            buy_price_unit: value.buy_price_unit.map(decimal_to_wire),
            sell_price_unit: value.sell_price_unit.map(decimal_to_wire),
            minimum_buy_total: decimal_to_wire(value.minimum_buy_total),
            minimum_sell_total: decimal_to_wire(value.minimum_sell_total),
            maximum_total: decimal_to_wire(value.maximum_total),
            quote_account: value.quote_account.into(),
            base_account: value.base_account.into(),
        }
    }
}

impl TryFrom<WireOrderRules> for maxt::OrderRules {
    type Error = NativeError;

    fn try_from(value: WireOrderRules) -> Result<Self, Self::Error> {
        Ok(Self {
            market: value.market.into(),
            market_name: value.market_name,
            status: value.status.into(),
            buy_fee_rate: decimal_from_wire(&value.buy_fee_rate, "buy_fee_rate")
                .map_err(NativeError::from)?,
            sell_fee_rate: decimal_from_wire(&value.sell_fee_rate, "sell_fee_rate")
                .map_err(NativeError::from)?,
            maker_buy_fee_rate: decimal_from_wire(&value.maker_buy_fee_rate, "maker_buy_fee_rate")
                .map_err(NativeError::from)?,
            maker_sell_fee_rate: decimal_from_wire(
                &value.maker_sell_fee_rate,
                "maker_sell_fee_rate",
            )
            .map_err(NativeError::from)?,
            sides: value.sides.into_iter().map(Into::into).collect(),
            buy_options: value
                .buy_options
                .into_iter()
                .map(TryInto::try_into)
                .collect::<Result<_, _>>()?,
            sell_options: value
                .sell_options
                .into_iter()
                .map(TryInto::try_into)
                .collect::<Result<_, _>>()?,
            buy_price_unit: value
                .buy_price_unit
                .as_deref()
                .map(|value| decimal_from_wire(value, "buy_price_unit"))
                .transpose()
                .map_err(NativeError::from)?,
            sell_price_unit: value
                .sell_price_unit
                .as_deref()
                .map(|value| decimal_from_wire(value, "sell_price_unit"))
                .transpose()
                .map_err(NativeError::from)?,
            minimum_buy_total: decimal_from_wire(&value.minimum_buy_total, "minimum_buy_total")
                .map_err(NativeError::from)?,
            minimum_sell_total: decimal_from_wire(&value.minimum_sell_total, "minimum_sell_total")
                .map_err(NativeError::from)?,
            maximum_total: decimal_from_wire(&value.maximum_total, "maximum_total")
                .map_err(NativeError::from)?,
            quote_account: value.quote_account.try_into()?,
            base_account: value.base_account.try_into()?,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireAssetNetwork {
    pub exchange: WireExchange,
    pub asset: String,
    pub network: String,
    pub provider_id: String,
    pub deposit_enabled: bool,
    pub withdrawal_enabled: bool,
    pub withdrawal_fee: Option<WireWithdrawalFee>,
    pub minimum_withdrawal: Option<String>,
    pub maximum_withdrawal: Option<String>,
    pub memo_required: bool,
}

impl From<maxt::AssetNetwork> for WireAssetNetwork {
    fn from(value: maxt::AssetNetwork) -> Self {
        Self {
            exchange: value.exchange.into(),
            asset: value.asset,
            network: network_to_wire(value.network),
            provider_id: value.provider_id,
            deposit_enabled: value.deposit_enabled,
            withdrawal_enabled: value.withdrawal_enabled,
            withdrawal_fee: value.withdrawal_fee.map(Into::into),
            minimum_withdrawal: value.minimum_withdrawal.map(decimal_to_wire),
            maximum_withdrawal: value.maximum_withdrawal.map(decimal_to_wire),
            memo_required: value.memo_required,
        }
    }
}

impl TryFrom<WireAssetNetwork> for maxt::AssetNetwork {
    type Error = NativeError;

    fn try_from(value: WireAssetNetwork) -> Result<Self, Self::Error> {
        Ok(Self {
            exchange: value.exchange.into(),
            asset: value.asset,
            network: network_from_wire(value.network),
            provider_id: value.provider_id,
            deposit_enabled: value.deposit_enabled,
            withdrawal_enabled: value.withdrawal_enabled,
            withdrawal_fee: value.withdrawal_fee.map(TryInto::try_into).transpose()?,
            minimum_withdrawal: value
                .minimum_withdrawal
                .as_deref()
                .map(|value| decimal_from_wire(value, "minimum_withdrawal"))
                .transpose()
                .map_err(NativeError::from)?,
            maximum_withdrawal: value
                .maximum_withdrawal
                .as_deref()
                .map(|value| decimal_from_wire(value, "maximum_withdrawal"))
                .transpose()
                .map_err(NativeError::from)?,
            memo_required: value.memo_required,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireDepositAddress {
    pub exchange: WireExchange,
    pub asset: String,
    pub network: String,
    pub address: Option<String>,
    pub memo: Option<String>,
}

impl From<maxt::DepositAddress> for WireDepositAddress {
    fn from(value: maxt::DepositAddress) -> Self {
        Self {
            exchange: value.exchange.into(),
            asset: value.asset,
            network: network_to_wire(value.network),
            address: value.address,
            memo: value.memo,
        }
    }
}

impl TryFrom<WireDepositAddress> for maxt::DepositAddress {
    type Error = NativeError;

    fn try_from(value: WireDepositAddress) -> Result<Self, Self::Error> {
        Ok(Self {
            exchange: value.exchange.into(),
            asset: value.asset,
            network: network_from_wire(value.network),
            address: value.address,
            memo: value.memo,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireDepositAddressEntry {
    pub exchange: WireExchange,
    pub asset: String,
    pub network: Option<String>,
    pub provider_network: Option<String>,
    pub address: Option<String>,
    pub memo: Option<String>,
}

impl From<maxt::DepositAddressEntry> for WireDepositAddressEntry {
    fn from(value: maxt::DepositAddressEntry) -> Self {
        Self {
            exchange: value.exchange.into(),
            asset: value.asset,
            network: value.network.map(network_to_wire),
            provider_network: value.provider_network,
            address: value.address,
            memo: value.memo,
        }
    }
}

impl TryFrom<WireDepositAddressEntry> for maxt::DepositAddressEntry {
    type Error = NativeError;

    fn try_from(value: WireDepositAddressEntry) -> Result<Self, Self::Error> {
        Ok(Self {
            exchange: value.exchange.into(),
            asset: value.asset,
            network: value.network.map(network_from_wire),
            provider_network: value.provider_network,
            address: value.address,
            memo: value.memo,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireExchangeDestination {
    pub exchange: WireExchange,
    pub asset: String,
    pub network: String,
    pub address: String,
    pub memo: Option<String>,
}

impl From<maxt::ExchangeDestination> for WireExchangeDestination {
    fn from(value: maxt::ExchangeDestination) -> Self {
        Self {
            exchange: value.exchange.into(),
            asset: value.asset,
            network: network_to_wire(value.network),
            address: value.address,
            memo: value.memo,
        }
    }
}

impl TryFrom<WireExchangeDestination> for maxt::ExchangeDestination {
    type Error = NativeError;

    fn try_from(value: WireExchangeDestination) -> Result<Self, Self::Error> {
        Ok(Self {
            exchange: value.exchange.into(),
            asset: value.asset,
            network: network_from_wire(value.network),
            address: value.address,
            memo: value.memo,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireChainDestination {
    pub asset: String,
    pub network: String,
    pub address: String,
    pub memo: Option<String>,
}

impl From<maxt::ChainDestination> for WireChainDestination {
    fn from(value: maxt::ChainDestination) -> Self {
        Self {
            asset: value.asset,
            network: network_to_wire(value.network),
            address: value.address,
            memo: value.memo,
        }
    }
}

impl TryFrom<WireChainDestination> for maxt::ChainDestination {
    type Error = NativeError;

    fn try_from(value: WireChainDestination) -> Result<Self, Self::Error> {
        Ok(Self {
            asset: value.asset,
            network: network_from_wire(value.network),
            address: value.address,
            memo: value.memo,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireExchangeTransferRequest {
    pub asset: String,
    pub source_network: Option<String>,
    pub destination_network: Option<String>,
    pub amount: String,
}

impl From<maxt::ExchangeTransferRequest> for WireExchangeTransferRequest {
    fn from(value: maxt::ExchangeTransferRequest) -> Self {
        Self {
            asset: value.asset,
            source_network: value.source_network.map(network_to_wire),
            destination_network: value.destination_network.map(network_to_wire),
            amount: decimal_to_wire(value.amount),
        }
    }
}

impl TryFrom<WireExchangeTransferRequest> for maxt::ExchangeTransferRequest {
    type Error = NativeError;

    fn try_from(value: WireExchangeTransferRequest) -> Result<Self, Self::Error> {
        Ok(Self {
            asset: value.asset,
            source_network: value.source_network.map(network_from_wire),
            destination_network: value.destination_network.map(network_from_wire),
            amount: decimal_from_wire(&value.amount, "amount").map_err(NativeError::from)?,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireChainTransferRequest {
    pub asset: String,
    pub source_network: Option<String>,
    pub destination: WireChainDestination,
    pub amount: String,
}

impl From<maxt::ChainTransferRequest> for WireChainTransferRequest {
    fn from(value: maxt::ChainTransferRequest) -> Self {
        Self {
            asset: value.asset,
            source_network: value.source_network.map(network_to_wire),
            destination: value.destination.into(),
            amount: decimal_to_wire(value.amount),
        }
    }
}

impl TryFrom<WireChainTransferRequest> for maxt::ChainTransferRequest {
    type Error = NativeError;

    fn try_from(value: WireChainTransferRequest) -> Result<Self, Self::Error> {
        Ok(Self {
            asset: value.asset,
            source_network: value.source_network.map(network_from_wire),
            destination: value.destination.try_into()?,
            amount: decimal_from_wire(&value.amount, "amount").map_err(NativeError::from)?,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WireTransferDestination {
    Exchange(WireExchangeDestination),
    Chain(WireChainDestination),
}

impl From<maxt::TransferDestination> for WireTransferDestination {
    fn from(value: maxt::TransferDestination) -> Self {
        match value {
            maxt::TransferDestination::Exchange(value) => Self::Exchange(value.into()),
            maxt::TransferDestination::Chain(value) => Self::Chain(value.into()),
            _ => unreachable!("new TransferDestination variant requires a Dart wire variant"),
        }
    }
}

impl TryFrom<WireTransferDestination> for maxt::TransferDestination {
    type Error = NativeError;

    fn try_from(value: WireTransferDestination) -> Result<Self, Self::Error> {
        Ok(match value {
            WireTransferDestination::Exchange(value) => Self::Exchange(value.try_into()?),
            WireTransferDestination::Chain(value) => Self::Chain(value.try_into()?),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WireWithdrawalFee {
    Fixed(String),
    Rate {
        rate: String,
        minimum: Option<String>,
        maximum: Option<String>,
    },
}

impl From<maxt::WithdrawalFee> for WireWithdrawalFee {
    fn from(value: maxt::WithdrawalFee) -> Self {
        match value {
            maxt::WithdrawalFee::Fixed(value) => Self::Fixed(decimal_to_wire(value)),
            maxt::WithdrawalFee::Rate {
                rate,
                minimum,
                maximum,
            } => Self::Rate {
                rate: decimal_to_wire(rate),
                minimum: minimum.map(decimal_to_wire),
                maximum: maximum.map(decimal_to_wire),
            },
            _ => unreachable!("new WithdrawalFee variant requires a Dart wire variant"),
        }
    }
}

impl TryFrom<WireWithdrawalFee> for maxt::WithdrawalFee {
    type Error = NativeError;

    fn try_from(value: WireWithdrawalFee) -> Result<Self, Self::Error> {
        Ok(match value {
            WireWithdrawalFee::Fixed(value) => {
                Self::Fixed(decimal_from_wire(&value, "value").map_err(NativeError::from)?)
            }
            WireWithdrawalFee::Rate {
                rate,
                minimum,
                maximum,
            } => Self::Rate {
                rate: decimal_from_wire(&rate, "rate").map_err(NativeError::from)?,
                minimum: minimum
                    .as_deref()
                    .map(|value| decimal_from_wire(value, "minimum"))
                    .transpose()
                    .map_err(NativeError::from)?,
                maximum: maximum
                    .as_deref()
                    .map(|value| decimal_from_wire(value, "maximum"))
                    .transpose()
                    .map_err(NativeError::from)?,
            },
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WireTravelRuleRequirement {
    NotRequired,
    Required { consent_url: Option<String> },
}

impl From<maxt::TravelRuleRequirement> for WireTravelRuleRequirement {
    fn from(value: maxt::TravelRuleRequirement) -> Self {
        match value {
            maxt::TravelRuleRequirement::NotRequired => Self::NotRequired,
            maxt::TravelRuleRequirement::Required { consent_url } => Self::Required { consent_url },
            _ => unreachable!("new TravelRuleRequirement variant requires a Dart wire variant"),
        }
    }
}

impl TryFrom<WireTravelRuleRequirement> for maxt::TravelRuleRequirement {
    type Error = NativeError;

    fn try_from(value: WireTravelRuleRequirement) -> Result<Self, Self::Error> {
        Ok(match value {
            WireTravelRuleRequirement::NotRequired => Self::NotRequired,
            WireTravelRuleRequirement::Required { consent_url } => Self::Required { consent_url },
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireWithdrawalQuote {
    pub fee: Option<String>,
    pub expected_receive: Option<String>,
    pub minimum_amount: Option<String>,
    pub maximum_amount: Option<String>,
    pub address_allowed: Option<bool>,
    pub travel_rule: WireTravelRuleRequirement,
    pub expires_at_ns: Option<i64>,
}

impl From<maxt::WithdrawalQuote> for WireWithdrawalQuote {
    fn from(value: maxt::WithdrawalQuote) -> Self {
        Self {
            fee: value.fee.map(decimal_to_wire),
            expected_receive: value.expected_receive.map(decimal_to_wire),
            minimum_amount: value.minimum_amount.map(decimal_to_wire),
            maximum_amount: value.maximum_amount.map(decimal_to_wire),
            address_allowed: value.address_allowed,
            travel_rule: value.travel_rule.into(),
            expires_at_ns: value.expires_at.map(timestamp_to_wire),
        }
    }
}

impl TryFrom<WireWithdrawalQuote> for maxt::WithdrawalQuote {
    type Error = NativeError;

    fn try_from(value: WireWithdrawalQuote) -> Result<Self, Self::Error> {
        Ok(Self {
            fee: value
                .fee
                .as_deref()
                .map(|value| decimal_from_wire(value, "fee"))
                .transpose()
                .map_err(NativeError::from)?,
            expected_receive: value
                .expected_receive
                .as_deref()
                .map(|value| decimal_from_wire(value, "expected_receive"))
                .transpose()
                .map_err(NativeError::from)?,
            minimum_amount: value
                .minimum_amount
                .as_deref()
                .map(|value| decimal_from_wire(value, "minimum_amount"))
                .transpose()
                .map_err(NativeError::from)?,
            maximum_amount: value
                .maximum_amount
                .as_deref()
                .map(|value| decimal_from_wire(value, "maximum_amount"))
                .transpose()
                .map_err(NativeError::from)?,
            address_allowed: value.address_allowed,
            travel_rule: value.travel_rule.try_into()?,
            expires_at: value.expires_at_ns.map(Timestamp::from_nanos),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireTransferPlan {
    pub source: WireExchange,
    pub destination: Option<WireExchange>,
    pub request: WireWithdrawRequest,
    pub quote: WireWithdrawalQuote,
    pub created_at_ns: i64,
    pub expires_at_ns: i64,
}

impl From<maxt::TransferPlan> for WireTransferPlan {
    fn from(value: maxt::TransferPlan) -> Self {
        Self {
            source: value.source.into(),
            destination: value.destination.map(Into::into),
            request: value.request.into(),
            quote: value.quote.into(),
            created_at_ns: timestamp_to_wire(value.created_at),
            expires_at_ns: timestamp_to_wire(value.expires_at),
        }
    }
}

impl TryFrom<WireTransferPlan> for maxt::TransferPlan {
    type Error = NativeError;

    fn try_from(value: WireTransferPlan) -> Result<Self, Self::Error> {
        Ok(Self {
            source: value.source.into(),
            destination: value.destination.map(Into::into),
            request: value.request.try_into()?,
            quote: value.quote.try_into()?,
            created_at: Timestamp::from_nanos(value.created_at_ns),
            expires_at: Timestamp::from_nanos(value.expires_at_ns),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireWithdrawal {
    pub id: String,
    pub asset: String,
    pub network: Option<String>,
    pub provider_network: Option<String>,
    pub amount: String,
    pub fee: Option<String>,
    pub destination: Option<WireTransferDestination>,
    pub status: WireWithdrawalStatus,
    pub provider_status: String,
    pub tx_id: Option<String>,
    pub created_at_ns: Option<i64>,
}

impl From<maxt::Withdrawal> for WireWithdrawal {
    fn from(value: maxt::Withdrawal) -> Self {
        Self {
            id: value.id,
            asset: value.asset,
            network: value.network.map(network_to_wire),
            provider_network: value.provider_network,
            amount: decimal_to_wire(value.amount),
            fee: value.fee.map(decimal_to_wire),
            destination: value.destination.map(Into::into),
            status: value.status.into(),
            provider_status: value.provider_status,
            tx_id: value.tx_id,
            created_at_ns: value.created_at.map(timestamp_to_wire),
        }
    }
}

impl TryFrom<WireWithdrawal> for maxt::Withdrawal {
    type Error = NativeError;

    fn try_from(value: WireWithdrawal) -> Result<Self, Self::Error> {
        Ok(Self {
            id: value.id,
            asset: value.asset,
            network: value.network.map(network_from_wire),
            provider_network: value.provider_network,
            amount: decimal_from_wire(&value.amount, "amount").map_err(NativeError::from)?,
            fee: value
                .fee
                .as_deref()
                .map(|value| decimal_from_wire(value, "fee"))
                .transpose()
                .map_err(NativeError::from)?,
            destination: value.destination.map(TryInto::try_into).transpose()?,
            status: value.status.into(),
            provider_status: value.provider_status,
            tx_id: value.tx_id,
            created_at: value.created_at_ns.map(Timestamp::from_nanos),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireDeposit {
    pub id: String,
    pub asset: String,
    pub network: Option<String>,
    pub provider_network: Option<String>,
    pub amount: String,
    pub address: Option<String>,
    pub memo: Option<String>,
    pub status: WireDepositStatus,
    pub provider_status: String,
    pub tx_id: Option<String>,
    pub created_at_ns: Option<i64>,
}

impl From<maxt::Deposit> for WireDeposit {
    fn from(value: maxt::Deposit) -> Self {
        Self {
            id: value.id,
            asset: value.asset,
            network: value.network.map(network_to_wire),
            provider_network: value.provider_network,
            amount: decimal_to_wire(value.amount),
            address: value.address,
            memo: value.memo,
            status: value.status.into(),
            provider_status: value.provider_status,
            tx_id: value.tx_id,
            created_at_ns: value.created_at.map(timestamp_to_wire),
        }
    }
}

impl TryFrom<WireDeposit> for maxt::Deposit {
    type Error = NativeError;

    fn try_from(value: WireDeposit) -> Result<Self, Self::Error> {
        Ok(Self {
            id: value.id,
            asset: value.asset,
            network: value.network.map(network_from_wire),
            provider_network: value.provider_network,
            amount: decimal_from_wire(&value.amount, "amount").map_err(NativeError::from)?,
            address: value.address,
            memo: value.memo,
            status: value.status.into(),
            provider_status: value.provider_status,
            tx_id: value.tx_id,
            created_at: value.created_at_ns.map(Timestamp::from_nanos),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireCancelledOrder {
    pub order_id: String,
    pub client_id: Option<String>,
    pub market: Option<WireMarket>,
    pub cancelled_at_ns: Option<i64>,
}

impl From<maxt::CancelledOrder> for WireCancelledOrder {
    fn from(value: maxt::CancelledOrder) -> Self {
        Self {
            order_id: value.order_id,
            client_id: value.client_id,
            market: value.market.map(Into::into),
            cancelled_at_ns: value.cancelled_at.map(timestamp_to_wire),
        }
    }
}

impl TryFrom<WireCancelledOrder> for maxt::CancelledOrder {
    type Error = NativeError;

    fn try_from(value: WireCancelledOrder) -> Result<Self, Self::Error> {
        Ok(Self {
            order_id: value.order_id,
            client_id: value.client_id,
            market: value.market.map(Into::into),
            cancelled_at: value.cancelled_at_ns.map(Timestamp::from_nanos),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireOrderCancelFailure {
    pub order_id: Option<String>,
    pub client_id: Option<String>,
    pub market: Option<WireMarket>,
    pub code: Option<String>,
    pub message: Option<String>,
}

impl From<maxt::OrderCancelFailure> for WireOrderCancelFailure {
    fn from(value: maxt::OrderCancelFailure) -> Self {
        Self {
            order_id: value.order_id,
            client_id: value.client_id,
            market: value.market.map(Into::into),
            code: value.code,
            message: value.message,
        }
    }
}

impl TryFrom<WireOrderCancelFailure> for maxt::OrderCancelFailure {
    type Error = NativeError;

    fn try_from(value: WireOrderCancelFailure) -> Result<Self, Self::Error> {
        Ok(Self {
            order_id: value.order_id,
            client_id: value.client_id,
            market: value.market.map(Into::into),
            code: value.code,
            message: value.message,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireCancelOrdersResult {
    pub cancelled: Vec<WireCancelledOrder>,
    pub failed: Vec<WireOrderCancelFailure>,
}

impl From<maxt::CancelOrdersResult> for WireCancelOrdersResult {
    fn from(value: maxt::CancelOrdersResult) -> Self {
        Self {
            cancelled: value.cancelled.into_iter().map(Into::into).collect(),
            failed: value.failed.into_iter().map(Into::into).collect(),
        }
    }
}

impl TryFrom<WireCancelOrdersResult> for maxt::CancelOrdersResult {
    type Error = NativeError;

    fn try_from(value: WireCancelOrdersResult) -> Result<Self, Self::Error> {
        Ok(Self {
            cancelled: value
                .cancelled
                .into_iter()
                .map(TryInto::try_into)
                .collect::<Result<_, _>>()?,
            failed: value
                .failed
                .into_iter()
                .map(TryInto::try_into)
                .collect::<Result<_, _>>()?,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireOrderLookupRequest {
    pub kind: WireOrderIdKind,
    pub ids: Vec<String>,
    pub market: Option<WireMarket>,
}

impl From<maxt::OrderLookupRequest> for WireOrderLookupRequest {
    fn from(value: maxt::OrderLookupRequest) -> Self {
        Self {
            kind: value.kind.into(),
            ids: value.ids,
            market: value.market.map(Into::into),
        }
    }
}

impl TryFrom<WireOrderLookupRequest> for maxt::OrderLookupRequest {
    type Error = NativeError;

    fn try_from(value: WireOrderLookupRequest) -> Result<Self, Self::Error> {
        Ok(Self {
            kind: value.kind.into(),
            ids: value.ids,
            market: value.market.map(Into::into),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireCancelOrdersRequest {
    pub kind: WireOrderIdKind,
    pub ids: Vec<String>,
}

impl From<maxt::CancelOrdersRequest> for WireCancelOrdersRequest {
    fn from(value: maxt::CancelOrdersRequest) -> Self {
        Self {
            kind: value.kind.into(),
            ids: value.ids,
        }
    }
}

impl TryFrom<WireCancelOrdersRequest> for maxt::CancelOrdersRequest {
    type Error = NativeError;

    fn try_from(value: WireCancelOrdersRequest) -> Result<Self, Self::Error> {
        Ok(Self {
            kind: value.kind.into(),
            ids: value.ids,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireOrderHistoryRequest {
    pub market: Option<WireMarket>,
    pub statuses: Vec<WireOrderStatus>,
    pub from_ns: Option<i64>,
    pub to_ns: Option<i64>,
    pub cursor: Option<String>,
    pub limit: Option<u32>,
}

impl From<maxt::OrderHistoryRequest> for WireOrderHistoryRequest {
    fn from(value: maxt::OrderHistoryRequest) -> Self {
        Self {
            market: value.market.map(Into::into),
            statuses: value.statuses.into_iter().map(Into::into).collect(),
            from_ns: value.from.map(timestamp_to_wire),
            to_ns: value.to.map(timestamp_to_wire),
            cursor: value.cursor.map(|cursor| cursor.as_str().to_owned()),
            limit: value.limit,
        }
    }
}

impl TryFrom<WireOrderHistoryRequest> for maxt::OrderHistoryRequest {
    type Error = NativeError;

    fn try_from(value: WireOrderHistoryRequest) -> Result<Self, Self::Error> {
        Ok(Self {
            market: value.market.map(Into::into),
            statuses: value.statuses.into_iter().map(Into::into).collect(),
            from: value.from_ns.map(Timestamp::from_nanos),
            to: value.to_ns.map(Timestamp::from_nanos),
            cursor: value.cursor.map(maxt::Cursor::new),
            limit: value.limit,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireDepositAddressRequest {
    pub asset: String,
    pub network: String,
    pub amount: Option<String>,
}

impl From<maxt::DepositAddressRequest> for WireDepositAddressRequest {
    fn from(value: maxt::DepositAddressRequest) -> Self {
        Self {
            asset: value.asset,
            network: network_to_wire(value.network),
            amount: value.amount.map(decimal_to_wire),
        }
    }
}

impl TryFrom<WireDepositAddressRequest> for maxt::DepositAddressRequest {
    type Error = NativeError;

    fn try_from(value: WireDepositAddressRequest) -> Result<Self, Self::Error> {
        Ok(Self {
            asset: value.asset,
            network: network_from_wire(value.network),
            amount: value
                .amount
                .as_deref()
                .map(|value| decimal_from_wire(value, "amount"))
                .transpose()
                .map_err(NativeError::from)?,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireWithdrawRequest {
    pub asset: String,
    pub network: String,
    pub amount: String,
    pub destination: WireTransferDestination,
    pub client_id: Option<String>,
}

impl From<maxt::WithdrawRequest> for WireWithdrawRequest {
    fn from(value: maxt::WithdrawRequest) -> Self {
        Self {
            asset: value.asset,
            network: network_to_wire(value.network),
            amount: decimal_to_wire(value.amount),
            destination: value.destination.into(),
            client_id: value.client_id,
        }
    }
}

impl TryFrom<WireWithdrawRequest> for maxt::WithdrawRequest {
    type Error = NativeError;

    fn try_from(value: WireWithdrawRequest) -> Result<Self, Self::Error> {
        Ok(Self {
            asset: value.asset,
            network: network_from_wire(value.network),
            amount: decimal_from_wire(&value.amount, "amount").map_err(NativeError::from)?,
            destination: value.destination.try_into()?,
            client_id: value.client_id,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireTransferLookupRequest {
    pub asset: String,
    pub id: Option<String>,
    pub tx_id: Option<String>,
}

impl From<maxt::TransferLookupRequest> for WireTransferLookupRequest {
    fn from(value: maxt::TransferLookupRequest) -> Self {
        Self {
            asset: value.asset,
            id: value.id,
            tx_id: value.tx_id,
        }
    }
}

impl TryFrom<WireTransferLookupRequest> for maxt::TransferLookupRequest {
    type Error = NativeError;

    fn try_from(value: WireTransferLookupRequest) -> Result<Self, Self::Error> {
        let request = Self {
            asset: value.asset,
            id: value.id,
            tx_id: value.tx_id,
        };
        request.validate().map_err(NativeError::from)?;
        Ok(request)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireTransferHistoryRequest {
    pub asset: Option<String>,
    pub network: Option<String>,
    pub cursor: Option<String>,
    pub limit: Option<u32>,
}

impl From<maxt::TransferHistoryRequest> for WireTransferHistoryRequest {
    fn from(value: maxt::TransferHistoryRequest) -> Self {
        Self {
            asset: value.asset,
            network: value.network.map(network_to_wire),
            cursor: value.cursor.map(|cursor| cursor.as_str().to_owned()),
            limit: value.limit,
        }
    }
}

impl TryFrom<WireTransferHistoryRequest> for maxt::TransferHistoryRequest {
    type Error = NativeError;

    fn try_from(value: WireTransferHistoryRequest) -> Result<Self, Self::Error> {
        Ok(Self {
            asset: value.asset,
            network: value.network.map(network_from_wire),
            cursor: value.cursor.map(maxt::Cursor::new),
            limit: value.limit,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireUpbitYearCandle {
    pub market: WireMarket,
    pub open_time_ns: i64,
    pub korea_open_time_ns: Option<i64>,
    pub timestamp_ns: i64,
    pub open: String,
    pub high: String,
    pub low: String,
    pub close: String,
    pub volume: String,
    pub quote_volume: String,
    pub first_day_of_period: String,
}

impl From<maxt::UpbitYearCandle> for WireUpbitYearCandle {
    fn from(value: maxt::UpbitYearCandle) -> Self {
        Self {
            market: value.market.into(),
            open_time_ns: timestamp_to_wire(value.open_time),
            korea_open_time_ns: value.korea_open_time.map(timestamp_to_wire),
            timestamp_ns: timestamp_to_wire(value.timestamp),
            open: decimal_to_wire(value.open),
            high: decimal_to_wire(value.high),
            low: decimal_to_wire(value.low),
            close: decimal_to_wire(value.close),
            volume: decimal_to_wire(value.volume),
            quote_volume: decimal_to_wire(value.quote_volume),
            first_day_of_period: value.first_day_of_period,
        }
    }
}

impl TryFrom<WireUpbitYearCandle> for maxt::UpbitYearCandle {
    type Error = NativeError;

    fn try_from(value: WireUpbitYearCandle) -> Result<Self, Self::Error> {
        Ok(Self {
            market: value.market.into(),
            open_time: Timestamp::from_nanos(value.open_time_ns),
            korea_open_time: value.korea_open_time_ns.map(Timestamp::from_nanos),
            timestamp: Timestamp::from_nanos(value.timestamp_ns),
            open: decimal_from_wire(&value.open, "open").map_err(NativeError::from)?,
            high: decimal_from_wire(&value.high, "high").map_err(NativeError::from)?,
            low: decimal_from_wire(&value.low, "low").map_err(NativeError::from)?,
            close: decimal_from_wire(&value.close, "close").map_err(NativeError::from)?,
            volume: decimal_from_wire(&value.volume, "volume").map_err(NativeError::from)?,
            quote_volume: decimal_from_wire(&value.quote_volume, "quote_volume")
                .map_err(NativeError::from)?,
            first_day_of_period: value.first_day_of_period,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireUpbitOrderBookInstrument {
    pub market: WireMarket,
    pub quote_currency: String,
    pub tick_size: String,
    pub supported_levels: Vec<String>,
}

impl From<maxt::UpbitOrderBookInstrument> for WireUpbitOrderBookInstrument {
    fn from(value: maxt::UpbitOrderBookInstrument) -> Self {
        Self {
            market: value.market.into(),
            quote_currency: value.quote_currency,
            tick_size: decimal_to_wire(value.tick_size),
            supported_levels: value
                .supported_levels
                .into_iter()
                .map(decimal_to_wire)
                .collect(),
        }
    }
}

impl TryFrom<WireUpbitOrderBookInstrument> for maxt::UpbitOrderBookInstrument {
    type Error = NativeError;

    fn try_from(value: WireUpbitOrderBookInstrument) -> Result<Self, Self::Error> {
        Ok(Self {
            market: value.market.into(),
            quote_currency: value.quote_currency,
            tick_size: decimal_from_wire(&value.tick_size, "tick_size")
                .map_err(NativeError::from)?,
            supported_levels: value
                .supported_levels
                .into_iter()
                .map(|value| {
                    decimal_from_wire(&value, "supported_levels").map_err(NativeError::from)
                })
                .collect::<Result<_, _>>()?,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireUpbitDepositInfo {
    pub asset: String,
    pub network: Option<String>,
    pub provider_network: Option<String>,
    pub is_deposit_possible: bool,
    pub deposit_impossible_reason: Option<String>,
    pub minimum_deposit_amount: String,
    pub minimum_deposit_confirmations: u64,
    pub decimal_precision: u64,
}

impl From<maxt::UpbitDepositInfo> for WireUpbitDepositInfo {
    fn from(value: maxt::UpbitDepositInfo) -> Self {
        Self {
            asset: value.asset,
            network: value.network.map(network_to_wire),
            provider_network: value.provider_network,
            is_deposit_possible: value.is_deposit_possible,
            deposit_impossible_reason: value.deposit_impossible_reason,
            minimum_deposit_amount: decimal_to_wire(value.minimum_deposit_amount),
            minimum_deposit_confirmations: value.minimum_deposit_confirmations,
            decimal_precision: value.decimal_precision,
        }
    }
}

impl TryFrom<WireUpbitDepositInfo> for maxt::UpbitDepositInfo {
    type Error = NativeError;

    fn try_from(value: WireUpbitDepositInfo) -> Result<Self, Self::Error> {
        Ok(Self {
            asset: value.asset,
            network: value.network.map(network_from_wire),
            provider_network: value.provider_network,
            is_deposit_possible: value.is_deposit_possible,
            deposit_impossible_reason: value.deposit_impossible_reason,
            minimum_deposit_amount: decimal_from_wire(
                &value.minimum_deposit_amount,
                "minimum_deposit_amount",
            )
            .map_err(NativeError::from)?,
            minimum_deposit_confirmations: value.minimum_deposit_confirmations,
            decimal_precision: value.decimal_precision,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WireUpbitBatchCancelScope {
    All,
    QuoteCurrencies { values: Vec<String> },
    Pairs { values: Vec<WireMarket> },
}

impl From<maxt::UpbitBatchCancelScope> for WireUpbitBatchCancelScope {
    fn from(value: maxt::UpbitBatchCancelScope) -> Self {
        match value {
            maxt::UpbitBatchCancelScope::All => Self::All,
            maxt::UpbitBatchCancelScope::QuoteCurrencies { values } => {
                Self::QuoteCurrencies { values }
            }
            maxt::UpbitBatchCancelScope::Pairs { values } => Self::Pairs {
                values: values.into_iter().map(Into::into).collect(),
            },
        }
    }
}

impl TryFrom<WireUpbitBatchCancelScope> for maxt::UpbitBatchCancelScope {
    type Error = NativeError;

    fn try_from(value: WireUpbitBatchCancelScope) -> Result<Self, Self::Error> {
        Ok(match value {
            WireUpbitBatchCancelScope::All => Self::All,
            WireUpbitBatchCancelScope::QuoteCurrencies { values } => {
                Self::QuoteCurrencies { values }
            }
            WireUpbitBatchCancelScope::Pairs { values } => Self::Pairs {
                values: values.into_iter().map(Into::into).collect(),
            },
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireUpbitBatchCancelRequest {
    pub scope: WireUpbitBatchCancelScope,
    pub excluded_pairs: Option<Vec<WireMarket>>,
    pub side: Option<WireSide>,
    pub count: Option<u32>,
    pub order_by: Option<WireUpbitOrderDirection>,
}

impl From<maxt::UpbitBatchCancelRequest> for WireUpbitBatchCancelRequest {
    fn from(value: maxt::UpbitBatchCancelRequest) -> Self {
        Self {
            scope: value.scope.into(),
            excluded_pairs: value
                .excluded_pairs
                .map(|values| values.into_iter().map(Into::into).collect()),
            side: value.side.map(Into::into),
            count: value.count,
            order_by: value.order_by.map(Into::into),
        }
    }
}

impl TryFrom<WireUpbitBatchCancelRequest> for maxt::UpbitBatchCancelRequest {
    type Error = NativeError;

    fn try_from(value: WireUpbitBatchCancelRequest) -> Result<Self, Self::Error> {
        Ok(Self {
            scope: value.scope.try_into()?,
            excluded_pairs: value
                .excluded_pairs
                .map(|values| Ok::<_, NativeError>(values.into_iter().map(Into::into).collect()))
                .transpose()?,
            side: value.side.map(Into::into),
            count: value.count,
            order_by: value.order_by.map(Into::into),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireBithumbNotice {
    pub categories: Vec<String>,
    pub title: String,
    pub url: String,
    pub published_at_ns: i64,
    pub modified_at_ns: i64,
}

impl From<maxt::BithumbNotice> for WireBithumbNotice {
    fn from(value: maxt::BithumbNotice) -> Self {
        Self {
            categories: value.categories,
            title: value.title,
            url: value.url,
            published_at_ns: timestamp_to_wire(value.published_at),
            modified_at_ns: timestamp_to_wire(value.modified_at),
        }
    }
}

impl TryFrom<WireBithumbNotice> for maxt::BithumbNotice {
    type Error = NativeError;

    fn try_from(value: WireBithumbNotice) -> Result<Self, Self::Error> {
        Ok(Self {
            categories: value.categories,
            title: value.title,
            url: value.url,
            published_at: Timestamp::from_nanos(value.published_at_ns),
            modified_at: Timestamp::from_nanos(value.modified_at_ns),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireBithumbApiKey {
    pub access_key: String,
    pub expires_at_ns: i64,
}

impl From<maxt::BithumbApiKey> for WireBithumbApiKey {
    fn from(value: maxt::BithumbApiKey) -> Self {
        Self {
            access_key: value.access_key,
            expires_at_ns: timestamp_to_wire(value.expires_at),
        }
    }
}

impl TryFrom<WireBithumbApiKey> for maxt::BithumbApiKey {
    type Error = NativeError;

    fn try_from(value: WireBithumbApiKey) -> Result<Self, Self::Error> {
        Ok(Self {
            access_key: value.access_key,
            expires_at: Timestamp::from_nanos(value.expires_at_ns),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireBithumbPendingOrdersRequest {
    pub market: Option<WireMarket>,
    pub state: Option<WireBithumbPendingOrderState>,
    pub limit: Option<u32>,
    pub order_by: Option<WireBithumbOrderDirection>,
    pub cursor: Option<String>,
}

impl From<maxt::BithumbPendingOrdersRequest> for WireBithumbPendingOrdersRequest {
    fn from(value: maxt::BithumbPendingOrdersRequest) -> Self {
        Self {
            market: value.market.map(Into::into),
            state: value.state.map(Into::into),
            limit: value.limit,
            order_by: value.order_by.map(Into::into),
            cursor: value.cursor.map(|cursor| cursor.as_str().to_owned()),
        }
    }
}

impl TryFrom<WireBithumbPendingOrdersRequest> for maxt::BithumbPendingOrdersRequest {
    type Error = NativeError;

    fn try_from(value: WireBithumbPendingOrdersRequest) -> Result<Self, Self::Error> {
        Ok(Self {
            market: value.market.map(Into::into),
            state: value.state.map(Into::into),
            limit: value.limit,
            order_by: value.order_by.map(Into::into),
            cursor: value.cursor.map(maxt::Cursor::new),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireBithumbTwapOrdersRequest {
    pub market: Option<WireMarket>,
    pub uuids: Vec<String>,
    pub state: Option<WireBithumbTwapState>,
    pub cursor: Option<String>,
    pub limit: Option<u32>,
    pub order_by: Option<WireBithumbTwapOrderDirection>,
}

impl From<maxt::BithumbTwapOrdersRequest> for WireBithumbTwapOrdersRequest {
    fn from(value: maxt::BithumbTwapOrdersRequest) -> Self {
        Self {
            market: value.market.map(Into::into),
            uuids: value.uuids,
            state: value.state.map(Into::into),
            cursor: value.cursor.map(|cursor| cursor.as_str().to_owned()),
            limit: value.limit,
            order_by: value.order_by.map(Into::into),
        }
    }
}

impl TryFrom<WireBithumbTwapOrdersRequest> for maxt::BithumbTwapOrdersRequest {
    type Error = NativeError;

    fn try_from(value: WireBithumbTwapOrdersRequest) -> Result<Self, Self::Error> {
        Ok(Self {
            market: value.market.map(Into::into),
            uuids: value.uuids,
            state: value.state.map(Into::into),
            cursor: value.cursor.map(maxt::Cursor::new),
            limit: value.limit,
            order_by: value.order_by.map(Into::into),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireBithumbTwapOrderRequest {
    pub market: WireMarket,
    pub side: WireSide,
    pub volume: Option<String>,
    pub price: Option<String>,
    pub duration: u32,
    pub frequency: u32,
}

impl From<maxt::BithumbTwapOrderRequest> for WireBithumbTwapOrderRequest {
    fn from(value: maxt::BithumbTwapOrderRequest) -> Self {
        Self {
            market: value.market.into(),
            side: value.side.into(),
            volume: value.volume.map(decimal_to_wire),
            price: value.price.map(decimal_to_wire),
            duration: value.duration,
            frequency: value.frequency,
        }
    }
}

impl TryFrom<WireBithumbTwapOrderRequest> for maxt::BithumbTwapOrderRequest {
    type Error = NativeError;

    fn try_from(value: WireBithumbTwapOrderRequest) -> Result<Self, Self::Error> {
        Ok(Self {
            market: value.market.into(),
            side: value.side.into(),
            volume: value
                .volume
                .as_deref()
                .map(|value| decimal_from_wire(value, "volume"))
                .transpose()
                .map_err(NativeError::from)?,
            price: value
                .price
                .as_deref()
                .map(|value| decimal_from_wire(value, "price"))
                .transpose()
                .map_err(NativeError::from)?,
            duration: value.duration,
            frequency: value.frequency,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireBithumbTwapOrder {
    pub id: String,
    pub side: WireSide,
    pub price: String,
    pub state: WireBithumbTwapState,
    pub market: WireMarket,
    pub created_at_ns: i64,
    pub volume: String,
    pub finished_at_ns: Option<i64>,
    pub total_order_count: u32,
    pub total_trades_count: u32,
    pub progress_count: u32,
    pub total_executed_amount: String,
    pub total_executed_volume: String,
    pub avg_trade_price: String,
    pub wallet_id: Option<String>,
    pub canceled_at_ns: Option<i64>,
    pub cancel_type: Option<String>,
}

impl From<maxt::BithumbTwapOrder> for WireBithumbTwapOrder {
    fn from(value: maxt::BithumbTwapOrder) -> Self {
        Self {
            id: value.id,
            side: value.side.into(),
            price: decimal_to_wire(value.price),
            state: value.state.into(),
            market: value.market.into(),
            created_at_ns: timestamp_to_wire(value.created_at),
            volume: decimal_to_wire(value.volume),
            finished_at_ns: value.finished_at.map(timestamp_to_wire),
            total_order_count: value.total_order_count,
            total_trades_count: value.total_trades_count,
            progress_count: value.progress_count,
            total_executed_amount: decimal_to_wire(value.total_executed_amount),
            total_executed_volume: decimal_to_wire(value.total_executed_volume),
            avg_trade_price: decimal_to_wire(value.avg_trade_price),
            wallet_id: value.wallet_id,
            canceled_at_ns: value.canceled_at.map(timestamp_to_wire),
            cancel_type: value.cancel_type,
        }
    }
}

impl TryFrom<WireBithumbTwapOrder> for maxt::BithumbTwapOrder {
    type Error = NativeError;

    fn try_from(value: WireBithumbTwapOrder) -> Result<Self, Self::Error> {
        Ok(Self {
            id: value.id,
            side: value.side.into(),
            price: decimal_from_wire(&value.price, "price").map_err(NativeError::from)?,
            state: value.state.into(),
            market: value.market.into(),
            created_at: Timestamp::from_nanos(value.created_at_ns),
            volume: decimal_from_wire(&value.volume, "volume").map_err(NativeError::from)?,
            finished_at: value.finished_at_ns.map(Timestamp::from_nanos),
            total_order_count: value.total_order_count,
            total_trades_count: value.total_trades_count,
            progress_count: value.progress_count,
            total_executed_amount: decimal_from_wire(
                &value.total_executed_amount,
                "total_executed_amount",
            )
            .map_err(NativeError::from)?,
            total_executed_volume: decimal_from_wire(
                &value.total_executed_volume,
                "total_executed_volume",
            )
            .map_err(NativeError::from)?,
            avg_trade_price: decimal_from_wire(&value.avg_trade_price, "avg_trade_price")
                .map_err(NativeError::from)?,
            wallet_id: value.wallet_id,
            canceled_at: value.canceled_at_ns.map(Timestamp::from_nanos),
            cancel_type: value.cancel_type,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireBithumbAssetFee {
    pub display_name: String,
    pub asset: String,
    pub networks: Vec<WireBithumbNetworkFee>,
}

impl From<maxt::BithumbAssetFee> for WireBithumbAssetFee {
    fn from(value: maxt::BithumbAssetFee) -> Self {
        Self {
            display_name: value.display_name,
            asset: value.asset,
            networks: value.networks.into_iter().map(Into::into).collect(),
        }
    }
}

impl TryFrom<WireBithumbAssetFee> for maxt::BithumbAssetFee {
    type Error = NativeError;

    fn try_from(value: WireBithumbAssetFee) -> Result<Self, Self::Error> {
        Ok(Self {
            display_name: value.display_name,
            asset: value.asset,
            networks: value
                .networks
                .into_iter()
                .map(TryInto::try_into)
                .collect::<Result<_, _>>()?,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireBithumbNetworkFee {
    pub network: String,
    pub provider_name: String,
    pub deposit_fee: String,
    pub minimum_deposit: String,
    pub withdrawal_fee: WireWithdrawalFee,
    pub minimum_withdrawal: String,
}

impl From<maxt::BithumbNetworkFee> for WireBithumbNetworkFee {
    fn from(value: maxt::BithumbNetworkFee) -> Self {
        Self {
            network: network_to_wire(value.network),
            provider_name: value.provider_name,
            deposit_fee: decimal_to_wire(value.deposit_fee),
            minimum_deposit: decimal_to_wire(value.minimum_deposit),
            withdrawal_fee: value.withdrawal_fee.into(),
            minimum_withdrawal: decimal_to_wire(value.minimum_withdrawal),
        }
    }
}

impl TryFrom<WireBithumbNetworkFee> for maxt::BithumbNetworkFee {
    type Error = NativeError;

    fn try_from(value: WireBithumbNetworkFee) -> Result<Self, Self::Error> {
        Ok(Self {
            network: network_from_wire(value.network),
            provider_name: value.provider_name,
            deposit_fee: decimal_from_wire(&value.deposit_fee, "deposit_fee")
                .map_err(NativeError::from)?,
            minimum_deposit: decimal_from_wire(&value.minimum_deposit, "minimum_deposit")
                .map_err(NativeError::from)?,
            withdrawal_fee: value.withdrawal_fee.try_into()?,
            minimum_withdrawal: decimal_from_wire(&value.minimum_withdrawal, "minimum_withdrawal")
                .map_err(NativeError::from)?,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireBinanceMarkPrice {
    pub market: WireMarket,
    pub mark_price: String,
    pub index_price: String,
    pub estimated_settle_price: Option<String>,
    pub last_funding_rate: String,
    pub interest_rate: String,
    pub next_funding_time_ns: i64,
    pub time_ns: i64,
}

impl From<maxt::BinanceMarkPrice> for WireBinanceMarkPrice {
    fn from(value: maxt::BinanceMarkPrice) -> Self {
        Self {
            market: value.market.into(),
            mark_price: decimal_to_wire(value.mark_price),
            index_price: decimal_to_wire(value.index_price),
            estimated_settle_price: value.estimated_settle_price.map(decimal_to_wire),
            last_funding_rate: decimal_to_wire(value.last_funding_rate),
            interest_rate: decimal_to_wire(value.interest_rate),
            next_funding_time_ns: timestamp_to_wire(value.next_funding_time),
            time_ns: timestamp_to_wire(value.time),
        }
    }
}

impl TryFrom<WireBinanceMarkPrice> for maxt::BinanceMarkPrice {
    type Error = NativeError;

    fn try_from(value: WireBinanceMarkPrice) -> Result<Self, Self::Error> {
        Ok(Self {
            market: value.market.into(),
            mark_price: decimal_from_wire(&value.mark_price, "mark_price")
                .map_err(NativeError::from)?,
            index_price: decimal_from_wire(&value.index_price, "index_price")
                .map_err(NativeError::from)?,
            estimated_settle_price: value
                .estimated_settle_price
                .as_deref()
                .map(|value| decimal_from_wire(value, "estimated_settle_price"))
                .transpose()
                .map_err(NativeError::from)?,
            last_funding_rate: decimal_from_wire(&value.last_funding_rate, "last_funding_rate")
                .map_err(NativeError::from)?,
            interest_rate: decimal_from_wire(&value.interest_rate, "interest_rate")
                .map_err(NativeError::from)?,
            next_funding_time: Timestamp::from_nanos(value.next_funding_time_ns),
            time: Timestamp::from_nanos(value.time_ns),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireBinanceOpenInterest {
    pub market: WireMarket,
    pub open_interest: String,
    pub time_ns: i64,
}

impl From<maxt::BinanceOpenInterest> for WireBinanceOpenInterest {
    fn from(value: maxt::BinanceOpenInterest) -> Self {
        Self {
            market: value.market.into(),
            open_interest: decimal_to_wire(value.open_interest),
            time_ns: timestamp_to_wire(value.time),
        }
    }
}

impl TryFrom<WireBinanceOpenInterest> for maxt::BinanceOpenInterest {
    type Error = NativeError;

    fn try_from(value: WireBinanceOpenInterest) -> Result<Self, Self::Error> {
        Ok(Self {
            market: value.market.into(),
            open_interest: decimal_from_wire(&value.open_interest, "open_interest")
                .map_err(NativeError::from)?,
            time: Timestamp::from_nanos(value.time_ns),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireHyperliquidMidPrice {
    pub market: WireMarket,
    pub price: String,
}

impl From<maxt::HyperliquidMidPrice> for WireHyperliquidMidPrice {
    fn from(value: maxt::HyperliquidMidPrice) -> Self {
        Self {
            market: value.market.into(),
            price: decimal_to_wire(value.price),
        }
    }
}

impl TryFrom<WireHyperliquidMidPrice> for maxt::HyperliquidMidPrice {
    type Error = NativeError;

    fn try_from(value: WireHyperliquidMidPrice) -> Result<Self, Self::Error> {
        Ok(Self {
            market: value.market.into(),
            price: decimal_from_wire(&value.price, "price").map_err(NativeError::from)?,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireDepositPage {
    pub items: Vec<WireDeposit>,
    pub next: Option<String>,
}

impl From<maxt::Page<maxt::Deposit>> for WireDepositPage {
    fn from(value: maxt::Page<maxt::Deposit>) -> Self {
        Self {
            items: value.items.into_iter().map(Into::into).collect(),
            next: value.next.map(|cursor| cursor.as_str().to_owned()),
        }
    }
}

impl TryFrom<WireDepositPage> for maxt::Page<maxt::Deposit> {
    type Error = NativeError;

    fn try_from(value: WireDepositPage) -> Result<Self, Self::Error> {
        Ok(Self {
            items: value
                .items
                .into_iter()
                .map(TryInto::try_into)
                .collect::<Result<_, _>>()?,
            next: value.next.map(maxt::Cursor::new),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireWithdrawalPage {
    pub items: Vec<WireWithdrawal>,
    pub next: Option<String>,
}

impl From<maxt::Page<maxt::Withdrawal>> for WireWithdrawalPage {
    fn from(value: maxt::Page<maxt::Withdrawal>) -> Self {
        Self {
            items: value.items.into_iter().map(Into::into).collect(),
            next: value.next.map(|cursor| cursor.as_str().to_owned()),
        }
    }
}

impl TryFrom<WireWithdrawalPage> for maxt::Page<maxt::Withdrawal> {
    type Error = NativeError;

    fn try_from(value: WireWithdrawalPage) -> Result<Self, Self::Error> {
        Ok(Self {
            items: value
                .items
                .into_iter()
                .map(TryInto::try_into)
                .collect::<Result<_, _>>()?,
            next: value.next.map(maxt::Cursor::new),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireOrderPage {
    pub items: Vec<WireOrder>,
    pub next: Option<String>,
}

impl From<maxt::Page<maxt::Order>> for WireOrderPage {
    fn from(value: maxt::Page<maxt::Order>) -> Self {
        Self {
            items: value.items.into_iter().map(Into::into).collect(),
            next: value.next.map(|cursor| cursor.as_str().to_owned()),
        }
    }
}

impl TryFrom<WireOrderPage> for maxt::Page<maxt::Order> {
    type Error = NativeError;

    fn try_from(value: WireOrderPage) -> Result<Self, Self::Error> {
        Ok(Self {
            items: value
                .items
                .into_iter()
                .map(TryInto::try_into)
                .collect::<Result<_, _>>()?,
            next: value.next.map(maxt::Cursor::new),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WireBithumbTwapOrderPage {
    pub items: Vec<WireBithumbTwapOrder>,
    pub next: Option<String>,
}

impl From<maxt::Page<maxt::BithumbTwapOrder>> for WireBithumbTwapOrderPage {
    fn from(value: maxt::Page<maxt::BithumbTwapOrder>) -> Self {
        Self {
            items: value.items.into_iter().map(Into::into).collect(),
            next: value.next.map(|cursor| cursor.as_str().to_owned()),
        }
    }
}

impl TryFrom<WireBithumbTwapOrderPage> for maxt::Page<maxt::BithumbTwapOrder> {
    type Error = NativeError;

    fn try_from(value: WireBithumbTwapOrderPage) -> Result<Self, Self::Error> {
        Ok(Self {
            items: value
                .items
                .into_iter()
                .map(TryInto::try_into)
                .collect::<Result<_, _>>()?,
            next: value.next.map(maxt::Cursor::new),
        })
    }
}
