[package]
name = "maxt_dart_bridge"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
publish = false

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
anyhow = "1"
flutter_rust_bridge = "=2.12.0"
futures-channel = "0.3"
futures-core = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
maxt = "0.1.0"
maxt-bindings-common = "0.1.0"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
