// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.

part of 'adapters.dart';

extension UpbitAdapterGeneratedMethods on UpbitAdapter {
  Future<List<OrderBook>> orderBooks(List<Market> markets, [int? depth]) =>
      _nativeFuture(
        () => _handle.upbitOrderBooks(
          markets: markets.map(_marketToWire).toList(growable: false),
          depth: checkedUint32(depth, field: 'depth'),
        ),
      ).then(
        (values) => values.map(_orderBookFromWire).toList(growable: false),
      );

  Future<List<OrderBook>> orderBooksAtLevel(
    List<Market> markets,
    Decimal level, [
    int? depth,
  ]) => _nativeFuture(
    () => _handle.upbitOrderBooksAtLevel(
      markets: markets.map(_marketToWire).toList(growable: false),
      level: level.toString(),
      depth: checkedUint32(depth, field: 'depth'),
    ),
  ).then((values) => values.map(_orderBookFromWire).toList(growable: false));

  Future<List<Ticker>> tickers(List<Market> markets) => _nativeFuture(
    () => _handle.upbitTickers(
      markets: markets.map(_marketToWire).toList(growable: false),
    ),
  ).then((values) => values.map(_tickerFromWire).toList(growable: false));

  Future<List<Ticker>> tickersByQuote(List<String> quoteCurrencies) =>
      _nativeFuture(
        () => _handle.upbitTickersByQuote(quoteCurrencies: quoteCurrencies),
      ).then((values) => values.map(_tickerFromWire).toList(growable: false));

  Future<List<UpbitYearCandle>> yearCandles(
    Market market, [
    Timestamp? to,
    int? count,
  ]) =>
      _nativeFuture(
        () => _handle.upbitYearCandles(
          market: _marketToWire(market),
          toNs: to == null
              ? null
              : platformInt64FromBigInt(to.nanosecondsSinceEpoch),
          count: checkedUint32(count, field: 'count'),
        ),
      ).then(
        (values) =>
            values.map(_upbitYearCandleFromWire).toList(growable: false),
      );

  Future<List<UpbitOrderBookInstrument>> orderbookInstruments(
    List<Market> markets,
  ) =>
      _nativeFuture(
        () => _handle.upbitOrderbookInstruments(
          markets: markets.map(_marketToWire).toList(growable: false),
        ),
      ).then(
        (values) => values
            .map(_upbitOrderBookInstrumentFromWire)
            .toList(growable: false),
      );

  Future<List<UpbitMarketEvent>> marketEvents() =>
      _nativeFuture(_handle.upbitMarketEvents).then(
        (values) =>
            values.map(_upbitMarketEventFromWire).toList(growable: false),
      );

  /// Validates an Upbit order without creating it.
  ///
  /// The returned [Order] is a dry-run result. Do not query or cancel its ID,
  /// and do not treat its status as a live order.
  Future<Order> testOrder(OrderRequest request) => _nativeFuture(
    () => _handle.upbitTestOrder(request: _orderRequestToWire(request)),
  ).then(_orderFromWire);

  /// Fetches Upbit deposit availability for one asset and network.
  ///
  /// Upbit may delay this metadata by several minutes, so it is not a
  /// real-time service-status signal.
  Future<UpbitDepositInfo> depositInfo(String asset, Network network) =>
      _nativeFuture(
        () => _handle.upbitDepositInfo(
          asset: asset,
          network: _networkToWire(network),
        ),
      ).then(_upbitDepositInfoFromWire);

  /// Lists VASPs available for Upbit Korea or Singapore Travel Rule verification.
  Future<List<UpbitTravelRuleVasp>> travelRuleVasps() =>
      _nativeFuture(_handle.upbitTravelRuleVasps).then(
        (values) =>
            values.map(_upbitTravelRuleVaspFromWire).toList(growable: false),
      );

  /// Requests Korea or Singapore Travel Rule verification for a deposit UUID.
  ///
  /// This is a financial write; Upbit limits repeated verification for one
  /// deposit.
  Future<UpbitTravelRuleVerification> verifyTravelRuleByUuid(
    String depositUuid,
    String vaspUuid,
  ) => _nativeFuture(
    () => _handle.upbitVerifyTravelRuleByUuid(
      depositUuid: depositUuid,
      vaspUuid: vaspUuid,
    ),
  ).then(_upbitTravelRuleVerificationFromWire);

  /// Requests Korea or Singapore Travel Rule verification for a transaction ID.
  ///
  /// This is a financial write; Upbit limits repeated verification for one
  /// deposit.
  Future<UpbitTravelRuleVerification> verifyTravelRuleByTxid(
    String txid,
    String vaspUuid,
    String currency,
    String netType,
  ) => _nativeFuture(
    () => _handle.upbitVerifyTravelRuleByTxid(
      txid: txid,
      vaspUuid: vaspUuid,
      currency: currency,
      netType: netType,
    ),
  ).then(_upbitTravelRuleVerificationFromWire);

  /// Cancels matching Upbit wait orders in one conditional request.
  ///
  /// [UpbitBatchCancelScope.all] selects every eligible market; Upbit still
  /// applies the request count (default 20, maximum 300). The result separates
  /// completed and failed cancels.
  Future<CancelOrdersResult> batchCancelOpenOrders(
    UpbitBatchCancelRequest request,
  ) => _nativeFuture(
    () => _handle.upbitBatchCancelOpenOrders(
      request: _upbitBatchCancelRequestToWire(request),
    ),
  ).then(_cancelOrdersResultFromWire);

  /// Cancels an Upbit order and requests its replacement.
  ///
  /// A successful response can still contain a filled previous order and no
  /// replacement. Inspect [UpbitCancelAndNewOrderResult.newOrderUuid].
  Future<UpbitCancelAndNewOrderResult> cancelAndNewOrder(
    UpbitCancelAndNewOrderRequest request,
  ) => _nativeFuture(
    () => _handle.upbitCancelAndNewOrder(
      request: _upbitCancelAndNewOrderRequestToWire(request),
    ),
  ).then(_upbitCancelAndNewOrderResultFromWire);
}

extension BithumbAdapterGeneratedMethods on BithumbAdapter {
  Future<List<BithumbMarketWarning>> marketWarnings() =>
      _nativeFuture(_handle.bithumbMarketWarnings).then(
        (values) =>
            values.map(_bithumbMarketWarningFromWire).toList(growable: false),
      );

  Future<List<BithumbMarketAlert>> marketAlerts() =>
      _nativeFuture(_handle.bithumbMarketAlerts).then(
        (values) =>
            values.map(_bithumbMarketAlertFromWire).toList(growable: false),
      );

  Future<List<BithumbNotice>> notices([int? count]) =>
      _nativeFuture(
        () =>
            _handle.bithumbNotices(count: checkedUint32(count, field: 'count')),
      ).then(
        (values) => values.map(_bithumbNoticeFromWire).toList(growable: false),
      );

  Future<List<BithumbAssetFee>> transferFees(String currency) =>
      _nativeFuture(() => _handle.bithumbTransferFees(currency: currency)).then(
        (values) =>
            values.map(_bithumbAssetFeeFromWire).toList(growable: false),
      );

  Future<List<BithumbApiKey>> apiKeys() =>
      _nativeFuture(_handle.bithumbApiKeys).then(
        (values) => values.map(_bithumbApiKeyFromWire).toList(growable: false),
      );

  Future<List<BithumbKrwWithdrawal>> krwWithdrawals(
    BithumbKrwWithdrawalsRequest request,
  ) =>
      _nativeFuture(
        () => _handle.bithumbKrwWithdrawals(
          request: _bithumbKrwWithdrawalsRequestToWire(request),
        ),
      ).then(
        (values) =>
            values.map(_bithumbKrwWithdrawalFromWire).toList(growable: false),
      );

  /// Requests a KRW withdrawal. This is a financial write.
  Future<BithumbKrwWithdrawal> withdrawKrw(BithumbKrwTransferRequest request) =>
      _nativeFuture(
        () => _handle.bithumbWithdrawKrw(
          request: _bithumbKrwTransferRequestToWire(request),
        ),
      ).then(_bithumbKrwWithdrawalFromWire);

  Future<List<BithumbKrwDeposit>> krwDeposits(
    BithumbKrwDepositsRequest request,
  ) =>
      _nativeFuture(
        () => _handle.bithumbKrwDeposits(
          request: _bithumbKrwDepositsRequestToWire(request),
        ),
      ).then(
        (values) =>
            values.map(_bithumbKrwDepositFromWire).toList(growable: false),
      );

  /// Requests a KRW deposit. This is a financial write.
  Future<BithumbKrwDeposit> depositKrw(BithumbKrwTransferRequest request) =>
      _nativeFuture(
        () => _handle.bithumbDepositKrw(
          request: _bithumbKrwTransferRequestToWire(request),
        ),
      ).then(_bithumbKrwDepositFromWire);

  Future<Page<Order>> pendingOrders(BithumbPendingOrdersRequest request) =>
      _nativeFuture(
        () => _handle.bithumbPendingOrders(
          request: _bithumbPendingOrdersRequestToWire(request),
        ),
      ).then(_orderPageFromWire);

  /// Submits Bithumb orders together; each outcome is independent.
  Future<BithumbBatchOrdersResult> batchOrders(
    BithumbBatchOrdersRequest request,
  ) => _nativeFuture(
    () => _handle.bithumbBatchOrders(
      request: _bithumbBatchOrdersRequestToWire(request),
    ),
  ).then(_bithumbBatchOrdersResultFromWire);

  Future<Page<BithumbTwapOrder>> twapOrders(BithumbTwapOrdersRequest request) =>
      _nativeFuture(
        () => _handle.bithumbTwapOrders(
          request: _bithumbTwapOrdersRequestToWire(request),
        ),
      ).then(_bithumbTwapOrderPageFromWire);

  /// Creates a Bithumb TWAP order. This submits a financial request.
  Future<String> createTwapOrder(BithumbTwapOrderRequest request) =>
      _nativeFuture(
        () => _handle.bithumbCreateTwapOrder(
          request: _bithumbTwapOrderRequestToWire(request),
        ),
      );

  /// Cancels a Bithumb TWAP order. This submits a financial request.
  Future<String> cancelTwapOrder(String algoOrderId) => _nativeFuture(
    () => _handle.bithumbCancelTwapOrder(algoOrderId: algoOrderId),
  );
}

extension BinanceAdapterGeneratedMethods on BinanceAdapter {
  Future<BinanceSymbolFilters> spotSymbolFilters(Market market) =>
      _nativeFuture(
        () => _handle.binanceSpotSymbolFilters(market: _marketToWire(market)),
      ).then(_binanceSymbolFiltersFromWire);

  Future<BinanceSpotOrderDetail> spotOrder(Market market, String orderId) =>
      _nativeFuture(
        () => _handle.binanceSpotOrder(
          market: _marketToWire(market),
          orderId: orderId,
        ),
      ).then(_binanceSpotOrderFromWire);

  Future<BinanceMarkPrice> markPrice(Market market) => _nativeFuture(
    () => _handle.binanceMarkPrice(market: _marketToWire(market)),
  ).then(_binanceMarkPriceFromWire);

  Future<List<BinanceMarkPrice>> markPrices() =>
      _nativeFuture(_handle.binanceMarkPrices).then(
        (values) =>
            values.map(_binanceMarkPriceFromWire).toList(growable: false),
      );

  Future<BinanceOpenInterest> openInterest(Market market) => _nativeFuture(
    () => _handle.binanceOpenInterest(market: _marketToWire(market)),
  ).then(_binanceOpenInterestFromWire);

  Future<List<BinanceAggregateTrade>> aggregateTrades(
    BinanceAggregateTradesRequest request,
  ) =>
      _nativeFuture(
        () => _handle.binanceAggregateTrades(
          request: _binanceAggregateTradesRequestToWire(request),
        ),
      ).then(
        (values) =>
            values.map(_binanceAggregateTradeFromWire).toList(growable: false),
      );

  Future<BinanceListenKey> usdMCreateListenKey() => _nativeFuture(
    _handle.binanceUsdMCreateListenKey,
  ).then(BinanceListenKey._);

  Future<void> usdMKeepaliveListenKey() =>
      _nativeFuture(_handle.binanceUsdMKeepaliveListenKey);

  Future<void> usdMCloseListenKey() =>
      _nativeFuture(_handle.binanceUsdMCloseListenKey);
}

extension HyperliquidAdapterGeneratedMethods on HyperliquidAdapter {
  Future<List<HyperliquidMidPrice>> allMids() =>
      _nativeFuture(_handle.hyperliquidAllMids).then(
        (values) =>
            values.map(_hyperliquidMidPriceFromWire).toList(growable: false),
      );

  Future<Page<HyperliquidLedgerEntry>> nonFundingLedger({
    Timestamp? from,
    Timestamp? to,
    Cursor? cursor,
    int? limit,
  }) => _nativeFuture(
    () => _handle.hyperliquidNonFundingLedger(
      fromNs: from == null
          ? null
          : platformInt64FromBigInt(from.nanosecondsSinceEpoch),
      toNs: to == null
          ? null
          : platformInt64FromBigInt(to.nanosecondsSinceEpoch),
      cursor: cursor?.value,
      limit: checkedUint32(limit, field: 'limit'),
    ),
  ).then(_hyperliquidLedgerPageFromWire);

  Future<HyperliquidAssetContext> assetContext(Market market) => _nativeFuture(
    () => _handle.hyperliquidAssetContext(market: _marketToWire(market)),
  ).then(_hyperliquidAssetContextFromWire);
}
