// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.

/// `Exchange` identifier used by an exchange API.
enum Exchange { upbit, bithumb, binance, hyperliquid }

/// Converts this identifier to its exchange wire name.
extension ExchangeWireName on Exchange {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    Exchange.upbit => 'upbit',
    Exchange.bithumb => 'bithumb',
    Exchange.binance => 'binance',
    Exchange.hyperliquid => 'hyperliquid',
  };
}

/// `Feature` identifier used by an exchange API.
enum Feature {
  /// Exchange wire value `markets`.
  markets,

  /// Exchange wire value `trades`.
  trades,

  /// Exchange wire value `order_book`.
  orderBook,

  /// Exchange wire value `ticker`.
  ticker,

  /// Exchange wire value `candles`.
  candles,

  /// Exchange wire value `trade_stream`.
  tradeStream,

  /// Exchange wire value `order_book_stream`.
  orderBookStream,

  /// Exchange wire value `ticker_stream`.
  tickerStream,

  /// Exchange wire value `candle_stream`.
  candleStream,

  /// Exchange wire value `balances`.
  balances,

  /// Exchange wire value `asset_networks`.
  assetNetworks,

  /// Exchange wire value `deposit_addresses`.
  depositAddresses,

  /// Exchange wire value `deposit_history`.
  depositHistory,

  /// Exchange wire value `deposit_lookup`.
  depositLookup,

  /// Exchange wire value `travel_rule`.
  travelRule,

  /// Exchange wire value `withdrawal_quotes`.
  withdrawalQuotes,

  /// Exchange wire value `withdrawals`.
  withdrawals,

  /// Exchange wire value `withdrawal_history`.
  withdrawalHistory,

  /// Exchange wire value `withdrawal_lookup`.
  withdrawalLookup,

  /// Exchange wire value `withdrawal_cancellation`.
  withdrawalCancellation,

  /// Exchange wire value `open_orders`.
  openOrders,

  /// Exchange wire value `order_history`.
  orderHistory,

  /// Exchange wire value `account_stream`.
  accountStream,

  /// Exchange wire value `trading`.
  trading,

  /// Exchange wire value `positions`.
  positions,

  /// Exchange wire value `margin`.
  margin,

  /// Exchange wire value `funding_rates`.
  fundingRates,

  /// Exchange wire value `funding_payments`.
  fundingPayments,

  /// Exchange wire value `margin_config`.
  marginConfig,

  /// Exchange wire value `reduce_only_orders`.
  reduceOnlyOrders,
}

/// Converts this identifier to its exchange wire name.
extension FeatureWireName on Feature {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    Feature.markets => 'markets',
    Feature.trades => 'trades',
    Feature.orderBook => 'order_book',
    Feature.ticker => 'ticker',
    Feature.candles => 'candles',
    Feature.tradeStream => 'trade_stream',
    Feature.orderBookStream => 'order_book_stream',
    Feature.tickerStream => 'ticker_stream',
    Feature.candleStream => 'candle_stream',
    Feature.balances => 'balances',
    Feature.assetNetworks => 'asset_networks',
    Feature.depositAddresses => 'deposit_addresses',
    Feature.depositHistory => 'deposit_history',
    Feature.depositLookup => 'deposit_lookup',
    Feature.travelRule => 'travel_rule',
    Feature.withdrawalQuotes => 'withdrawal_quotes',
    Feature.withdrawals => 'withdrawals',
    Feature.withdrawalHistory => 'withdrawal_history',
    Feature.withdrawalLookup => 'withdrawal_lookup',
    Feature.withdrawalCancellation => 'withdrawal_cancellation',
    Feature.openOrders => 'open_orders',
    Feature.orderHistory => 'order_history',
    Feature.accountStream => 'account_stream',
    Feature.trading => 'trading',
    Feature.positions => 'positions',
    Feature.margin => 'margin',
    Feature.fundingRates => 'funding_rates',
    Feature.fundingPayments => 'funding_payments',
    Feature.marginConfig => 'margin_config',
    Feature.reduceOnlyOrders => 'reduce_only_orders',
  };
}

/// `MarketKind` identifier used by an exchange API.
enum MarketKind { spot, perpetual }

/// Converts this identifier to its exchange wire name.
extension MarketKindWireName on MarketKind {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    MarketKind.spot => 'spot',
    MarketKind.perpetual => 'perpetual',
  };
}

/// `MarketStatus` identifier used by an exchange API.
enum MarketStatus { active, paused, delisted, unknown }

/// Converts this identifier to its exchange wire name.
extension MarketStatusWireName on MarketStatus {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    MarketStatus.active => 'active',
    MarketStatus.paused => 'paused',
    MarketStatus.delisted => 'delisted',
    MarketStatus.unknown => 'unknown',
  };
}

/// `Side` identifier used by an exchange API.
enum Side { buy, sell }

/// Converts this identifier to its exchange wire name.
extension SideWireName on Side {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    Side.buy => 'buy',
    Side.sell => 'sell',
  };
}

/// `Interval` identifier used by an exchange API.
enum Interval {
  /// Exchange wire value `sec1`.
  sec1,

  /// Exchange wire value `min1`.
  min1,

  /// Exchange wire value `min3`.
  min3,

  /// Exchange wire value `min5`.
  min5,

  /// Exchange wire value `min10`.
  min10,

  /// Exchange wire value `min15`.
  min15,

  /// Exchange wire value `min30`.
  min30,

  /// Exchange wire value `hour1`.
  hour1,

  /// Exchange wire value `hour2`.
  hour2,

  /// Exchange wire value `hour4`.
  hour4,

  /// Exchange wire value `hour6`.
  hour6,

  /// Exchange wire value `hour8`.
  hour8,

  /// Exchange wire value `hour12`.
  hour12,

  /// Exchange wire value `day1`.
  day1,

  /// Exchange wire value `day3`.
  day3,

  /// Exchange wire value `week1`.
  week1,

  /// Exchange wire value `month1`.
  month1,
}

/// Converts this identifier to its exchange wire name.
extension IntervalWireName on Interval {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    Interval.sec1 => 'sec1',
    Interval.min1 => 'min1',
    Interval.min3 => 'min3',
    Interval.min5 => 'min5',
    Interval.min10 => 'min10',
    Interval.min15 => 'min15',
    Interval.min30 => 'min30',
    Interval.hour1 => 'hour1',
    Interval.hour2 => 'hour2',
    Interval.hour4 => 'hour4',
    Interval.hour6 => 'hour6',
    Interval.hour8 => 'hour8',
    Interval.hour12 => 'hour12',
    Interval.day1 => 'day1',
    Interval.day3 => 'day3',
    Interval.week1 => 'week1',
    Interval.month1 => 'month1',
  };
}

/// `Overflow` identifier used by an exchange API.
enum Overflow { backpressure, dropNewest }

/// Converts this identifier to its exchange wire name.
extension OverflowWireName on Overflow {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    Overflow.backpressure => 'backpressure',
    Overflow.dropNewest => 'drop_newest',
  };
}

/// `MarginMode` identifier used by an exchange API.
enum MarginMode { cross, isolated }

/// Converts this identifier to its exchange wire name.
extension MarginModeWireName on MarginMode {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    MarginMode.cross => 'cross',
    MarginMode.isolated => 'isolated',
  };
}

/// `OrderStatus` identifier used by an exchange API.
enum OrderStatus {
  /// Exchange wire value `accepted`.
  accepted,

  /// Exchange wire value `open`.
  open,

  /// Exchange wire value `partially_filled`.
  partiallyFilled,

  /// Exchange wire value `filled`.
  filled,

  /// Exchange wire value `cancelled`.
  cancelled,

  /// Exchange wire value `rejected`.
  rejected,

  /// Exchange wire value `unknown`.
  unknown,
}

/// Converts this identifier to its exchange wire name.
extension OrderStatusWireName on OrderStatus {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    OrderStatus.accepted => 'accepted',
    OrderStatus.open => 'open',
    OrderStatus.partiallyFilled => 'partially_filled',
    OrderStatus.filled => 'filled',
    OrderStatus.cancelled => 'cancelled',
    OrderStatus.rejected => 'rejected',
    OrderStatus.unknown => 'unknown',
  };
}

/// `OrderIdKind` identifier used by an exchange API.
enum OrderIdKind { exchange, client }

/// Converts this identifier to its exchange wire name.
extension OrderIdKindWireName on OrderIdKind {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    OrderIdKind.exchange => 'exchange',
    OrderIdKind.client => 'client',
  };
}

/// `OrderType` identifier used by an exchange API.
enum OrderType { market, limit, best }

/// Converts this identifier to its exchange wire name.
extension OrderTypeWireName on OrderType {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    OrderType.market => 'market',
    OrderType.limit => 'limit',
    OrderType.best => 'best',
  };
}

/// `TimeInForce` identifier used by an exchange API.
enum TimeInForce { goodTilCancelled, immediateOrCancel, fillOrKill, postOnly }

/// Converts this identifier to its exchange wire name.
extension TimeInForceWireName on TimeInForce {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    TimeInForce.goodTilCancelled => 'good_til_cancelled',
    TimeInForce.immediateOrCancel => 'immediate_or_cancel',
    TimeInForce.fillOrKill => 'fill_or_kill',
    TimeInForce.postOnly => 'post_only',
  };
}

/// `SizeKind` identifier used by an exchange API.
enum SizeKind { base, quote }

/// Converts this identifier to its exchange wire name.
extension SizeKindWireName on SizeKind {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    SizeKind.base => 'base',
    SizeKind.quote => 'quote',
  };
}

/// `UpbitRegion` identifier used by an exchange API.
enum UpbitRegion { korea, singapore, indonesia, thailand }

/// Converts this identifier to its exchange wire name.
extension UpbitRegionWireName on UpbitRegion {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    UpbitRegion.korea => 'korea',
    UpbitRegion.singapore => 'singapore',
    UpbitRegion.indonesia => 'indonesia',
    UpbitRegion.thailand => 'thailand',
  };
}

/// `UpbitOrderDirection` identifier used by an exchange API.
enum UpbitOrderDirection { ascending, descending }

/// Converts this identifier to its exchange wire name.
extension UpbitOrderDirectionWireName on UpbitOrderDirection {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    UpbitOrderDirection.ascending => 'asc',
    UpbitOrderDirection.descending => 'desc',
  };
}

/// `UpbitClosedOrderState` identifier used by an exchange API.
enum UpbitClosedOrderState { done, cancel }

/// Converts this identifier to its exchange wire name.
extension UpbitClosedOrderStateWireName on UpbitClosedOrderState {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    UpbitClosedOrderState.done => 'done',
    UpbitClosedOrderState.cancel => 'cancel',
  };
}

/// `UpbitSmpType` identifier used by an exchange API.
enum UpbitSmpType { cancelMaker, cancelTaker, reduce }

/// Converts this identifier to its exchange wire name.
extension UpbitSmpTypeWireName on UpbitSmpType {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    UpbitSmpType.cancelMaker => 'cancel_maker',
    UpbitSmpType.cancelTaker => 'cancel_taker',
    UpbitSmpType.reduce => 'reduce',
  };
}

/// `UpbitKrwTwoFactorType` identifier used by an exchange API.
enum UpbitKrwTwoFactorType { kakao, naver, hana }

/// Converts this identifier to its exchange wire name.
extension UpbitKrwTwoFactorTypeWireName on UpbitKrwTwoFactorType {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    UpbitKrwTwoFactorType.kakao => 'kakao',
    UpbitKrwTwoFactorType.naver => 'naver',
    UpbitKrwTwoFactorType.hana => 'hana',
  };
}

/// `UpbitPocketTransferState` identifier used by an exchange API.
enum UpbitPocketTransferState { submitted, processing, done, failed }

/// Converts this identifier to its exchange wire name.
extension UpbitPocketTransferStateWireName on UpbitPocketTransferState {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    UpbitPocketTransferState.submitted => 'submitted',
    UpbitPocketTransferState.processing => 'processing',
    UpbitPocketTransferState.done => 'done',
    UpbitPocketTransferState.failed => 'failed',
  };
}

/// `UpbitPocketTransferDirection` identifier used by an exchange API.
enum UpbitPocketTransferDirection { incoming, outgoing, all }

/// Converts this identifier to its exchange wire name.
extension UpbitPocketTransferDirectionWireName on UpbitPocketTransferDirection {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    UpbitPocketTransferDirection.incoming => 'in',
    UpbitPocketTransferDirection.outgoing => 'out',
    UpbitPocketTransferDirection.all => 'all',
  };
}

/// `UpbitPocketTransferOrder` identifier used by an exchange API.
enum UpbitPocketTransferOrder { ascending, descending }

/// Converts this identifier to its exchange wire name.
extension UpbitPocketTransferOrderWireName on UpbitPocketTransferOrder {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    UpbitPocketTransferOrder.ascending => 'asc',
    UpbitPocketTransferOrder.descending => 'desc',
  };
}

/// `BithumbAlertStep` identifier used by an exchange API.
enum BithumbAlertStep { caution, warning, danger, unknown }

/// Converts this identifier to its exchange wire name.
extension BithumbAlertStepWireName on BithumbAlertStep {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    BithumbAlertStep.caution => 'caution',
    BithumbAlertStep.warning => 'warning',
    BithumbAlertStep.danger => 'danger',
    BithumbAlertStep.unknown => 'unknown',
  };
}

/// `BithumbPendingOrderState` identifier used by an exchange API.
enum BithumbPendingOrderState { wait, watch }

/// Converts this identifier to its exchange wire name.
extension BithumbPendingOrderStateWireName on BithumbPendingOrderState {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    BithumbPendingOrderState.wait => 'wait',
    BithumbPendingOrderState.watch => 'watch',
  };
}

/// `BithumbClosedOrderState` identifier used by an exchange API.
enum BithumbClosedOrderState { done, cancel }

/// Converts this identifier to its exchange wire name.
extension BithumbClosedOrderStateWireName on BithumbClosedOrderState {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    BithumbClosedOrderState.done => 'done',
    BithumbClosedOrderState.cancel => 'cancel',
  };
}

/// `BithumbOrderDirection` identifier used by an exchange API.
enum BithumbOrderDirection { ascending, descending }

/// Converts this identifier to its exchange wire name.
extension BithumbOrderDirectionWireName on BithumbOrderDirection {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    BithumbOrderDirection.ascending => 'asc',
    BithumbOrderDirection.descending => 'desc',
  };
}

/// `BithumbOrderListState` identifier used by an exchange API.
enum BithumbOrderListState { wait, watch, done, cancel }

/// Converts this identifier to its exchange wire name.
extension BithumbOrderListStateWireName on BithumbOrderListState {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    BithumbOrderListState.wait => 'wait',
    BithumbOrderListState.watch => 'watch',
    BithumbOrderListState.done => 'done',
    BithumbOrderListState.cancel => 'cancel',
  };
}

/// `BithumbTwapState` identifier used by an exchange API.
enum BithumbTwapState { progress, done, cancel }

/// Converts this identifier to its exchange wire name.
extension BithumbTwapStateWireName on BithumbTwapState {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    BithumbTwapState.progress => 'progress',
    BithumbTwapState.done => 'done',
    BithumbTwapState.cancel => 'cancel',
  };
}

/// `BithumbTwapOrderDirection` identifier used by an exchange API.
enum BithumbTwapOrderDirection { ascending, descending }

/// Converts this identifier to its exchange wire name.
extension BithumbTwapOrderDirectionWireName on BithumbTwapOrderDirection {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    BithumbTwapOrderDirection.ascending => 'asc',
    BithumbTwapOrderDirection.descending => 'desc',
  };
}

/// `BinanceMarket` identifier used by an exchange API.
enum BinanceMarket { spot, usdMFutures }

/// Converts this identifier to its exchange wire name.
extension BinanceMarketWireName on BinanceMarket {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    BinanceMarket.spot => 'spot',
    BinanceMarket.usdMFutures => 'usd_m',
  };
}

/// `BinanceC2cTradeType` identifier used by an exchange API.
enum BinanceC2cTradeType { buy, sell }

/// Converts this identifier to its exchange wire name.
extension BinanceC2cTradeTypeWireName on BinanceC2cTradeType {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    BinanceC2cTradeType.buy => 'BUY',
    BinanceC2cTradeType.sell => 'SELL',
  };
}

/// Extensible `HyperliquidLedgerKind` identifier supplied by an exchange.
final class HyperliquidLedgerKind {
  const HyperliquidLedgerKind._(this.providerName, [this._isOther = false]);

  /// Exchange wire value `deposit`.
  static const deposit = HyperliquidLedgerKind._('deposit');

  /// Exchange wire value `withdraw`.
  static const withdraw = HyperliquidLedgerKind._('withdraw');

  /// Exchange wire value `internal_transfer`.
  static const internalTransfer = HyperliquidLedgerKind._('internal_transfer');

  /// Exchange wire value `sub_account_transfer`.
  static const subAccountTransfer = HyperliquidLedgerKind._(
    'sub_account_transfer',
  );

  /// Exchange wire value `spot_transfer`.
  static const spotTransfer = HyperliquidLedgerKind._('spot_transfer');

  /// Exchange wire value `account_class_transfer`.
  static const accountClassTransfer = HyperliquidLedgerKind._(
    'account_class_transfer',
  );

  /// Exchange wire value `vault_deposit`.
  static const vaultDeposit = HyperliquidLedgerKind._('vault_deposit');

  /// Exchange wire value `vault_withdraw`.
  static const vaultWithdraw = HyperliquidLedgerKind._('vault_withdraw');

  /// Exchange wire value `vault_distribution`.
  static const vaultDistribution = HyperliquidLedgerKind._(
    'vault_distribution',
  );

  /// Exchange wire value `liquidation`.
  static const liquidation = HyperliquidLedgerKind._('liquidation');

  /// Preserves an unknown exchange wire value.
  factory HyperliquidLedgerKind.other(String providerName) =>
      HyperliquidLedgerKind._(providerName, true);

  /// Original name sent by the exchange.
  final String providerName;
  final bool _isOther;

  /// Whether this is not a predefined exchange value.
  bool get isOther => _isOther;

  @override
  bool operator ==(Object other) =>
      other is HyperliquidLedgerKind &&
      _isOther == other._isOther &&
      providerName == other.providerName;

  @override
  int get hashCode => Object.hash(_isOther, providerName);

  @override
  String toString() => providerName;
}

/// `ExchangeErrorKind` identifier used by an exchange API.
enum ExchangeErrorKind { rejected, rateLimited, unavailable, unknown }

/// Converts this identifier to its exchange wire name.
extension ExchangeErrorKindWireName on ExchangeErrorKind {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    ExchangeErrorKind.rejected => 'rejected',
    ExchangeErrorKind.rateLimited => 'rate_limited',
    ExchangeErrorKind.unavailable => 'unavailable',
    ExchangeErrorKind.unknown => 'unknown',
  };
}

/// Extensible `Network` identifier supplied by an exchange.
final class Network {
  const Network._(this.providerName, [this._isOther = false]);

  /// Exchange wire value `bitcoin`.
  static const bitcoin = Network._('bitcoin');

  /// Exchange wire value `ethereum`.
  static const ethereum = Network._('ethereum');

  /// Exchange wire value `arbitrum`.
  static const arbitrum = Network._('arbitrum');

  /// Exchange wire value `bnb_smart_chain`.
  static const bnbSmartChain = Network._('bnb_smart_chain');

  /// Exchange wire value `tron`.
  static const tron = Network._('tron');

  /// Exchange wire value `solana`.
  static const solana = Network._('solana');

  /// Exchange wire value `polygon`.
  static const polygon = Network._('polygon');

  /// Exchange wire value `base`.
  static const base = Network._('base');

  /// Exchange wire value `optimism`.
  static const optimism = Network._('optimism');

  /// Exchange wire value `avalanche_c`.
  static const avalancheC = Network._('avalanche_c');

  /// Exchange wire value `xrp_ledger`.
  static const xrpLedger = Network._('xrp_ledger');

  /// Exchange wire value `stellar`.
  static const stellar = Network._('stellar');

  /// Exchange wire value `cosmos`.
  static const cosmos = Network._('cosmos');

  /// Exchange wire value `aptos`.
  static const aptos = Network._('aptos');

  /// Exchange wire value `sui`.
  static const sui = Network._('sui');

  /// Exchange wire value `ton`.
  static const ton = Network._('ton');

  /// Exchange wire value `near`.
  static const near = Network._('near');

  /// Exchange wire value `polkadot`.
  static const polkadot = Network._('polkadot');

  /// Preserves an unknown exchange wire value.
  factory Network.other(String providerName) => Network._(providerName, true);

  /// Original name sent by the exchange.
  final String providerName;
  final bool _isOther;

  /// Whether this is not a predefined exchange value.
  bool get isOther => _isOther;

  @override
  bool operator ==(Object other) =>
      other is Network &&
      _isOther == other._isOther &&
      providerName == other.providerName;

  @override
  int get hashCode => Object.hash(_isOther, providerName);

  @override
  String toString() => providerName;
}

/// `WithdrawalStatus` identifier used by an exchange API.
enum WithdrawalStatus {
  /// Exchange wire value `pending`.
  pending,

  /// Exchange wire value `processing`.
  processing,

  /// Exchange wire value `completed`.
  completed,

  /// Exchange wire value `cancelled`.
  cancelled,

  /// Exchange wire value `failed`.
  failed,

  /// Exchange wire value `unknown`.
  unknown,
}

/// Converts this identifier to its exchange wire name.
extension WithdrawalStatusWireName on WithdrawalStatus {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    WithdrawalStatus.pending => 'pending',
    WithdrawalStatus.processing => 'processing',
    WithdrawalStatus.completed => 'completed',
    WithdrawalStatus.cancelled => 'cancelled',
    WithdrawalStatus.failed => 'failed',
    WithdrawalStatus.unknown => 'unknown',
  };
}

/// `DepositStatus` identifier used by an exchange API.
enum DepositStatus { pending, completed, failed, unknown }

/// Converts this identifier to its exchange wire name.
extension DepositStatusWireName on DepositStatus {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    DepositStatus.pending => 'pending',
    DepositStatus.completed => 'completed',
    DepositStatus.failed => 'failed',
    DepositStatus.unknown => 'unknown',
  };
}

/// `TransferErrorKind` identifier used by an exchange API.
enum TransferErrorKind {
  /// Exchange wire value `asset_mismatch`.
  assetMismatch,

  /// Exchange wire value `network_mismatch`.
  networkMismatch,

  /// Exchange wire value `ambiguous_network`.
  ambiguousNetwork,

  /// Exchange wire value `network_unavailable`.
  networkUnavailable,

  /// Exchange wire value `memo_required`.
  memoRequired,

  /// Exchange wire value `destination_unavailable`.
  destinationUnavailable,

  /// Exchange wire value `address_not_allowed`.
  addressNotAllowed,

  /// Exchange wire value `travel_rule_required`.
  travelRuleRequired,

  /// Exchange wire value `amount_out_of_range`.
  amountOutOfRange,

  /// Exchange wire value `plan_expired`.
  planExpired,
}

/// Converts this identifier to its exchange wire name.
extension TransferErrorKindWireName on TransferErrorKind {
  /// Wire name sent to the exchange API.
  String get wireName => switch (this) {
    TransferErrorKind.assetMismatch => 'asset_mismatch',
    TransferErrorKind.networkMismatch => 'network_mismatch',
    TransferErrorKind.ambiguousNetwork => 'ambiguous_network',
    TransferErrorKind.networkUnavailable => 'network_unavailable',
    TransferErrorKind.memoRequired => 'memo_required',
    TransferErrorKind.destinationUnavailable => 'destination_unavailable',
    TransferErrorKind.addressNotAllowed => 'address_not_allowed',
    TransferErrorKind.travelRuleRequired => 'travel_rule_required',
    TransferErrorKind.amountOutOfRange => 'amount_out_of_range',
    TransferErrorKind.planExpired => 'plan_expired',
  };
}
