// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.
// ignore_for_file: unused_element

part of 'adapters.dart';

wire.WireExchange _exchangeToWire(Exchange value) =>
    _enumByName(wire.WireExchange.values, value);
Exchange _exchangeFromWire(wire.WireExchange value) =>
    _enumByName(Exchange.values, value);

wire.WireFeature _featureToWire(Feature value) =>
    _enumByName(wire.WireFeature.values, value);
Feature _featureFromWire(wire.WireFeature value) =>
    _enumByName(Feature.values, value);

wire.WireMarketKind _marketKindToWire(MarketKind value) =>
    _enumByName(wire.WireMarketKind.values, value);
MarketKind _marketKindFromWire(wire.WireMarketKind value) =>
    _enumByName(MarketKind.values, value);

wire.WireMarketStatus _marketStatusToWire(MarketStatus value) =>
    _enumByName(wire.WireMarketStatus.values, value);
MarketStatus _marketStatusFromWire(wire.WireMarketStatus value) =>
    _enumByName(MarketStatus.values, value);

wire.WireSide _sideToWire(Side value) =>
    _enumByName(wire.WireSide.values, value);
Side _sideFromWire(wire.WireSide value) => _enumByName(Side.values, value);

wire.WireInterval _intervalToWire(Interval value) =>
    _enumByName(wire.WireInterval.values, value);
Interval _intervalFromWire(wire.WireInterval value) =>
    _enumByName(Interval.values, value);

wire.WireOrderIdKind _orderIdKindToWire(OrderIdKind value) =>
    _enumByName(wire.WireOrderIdKind.values, value);
OrderIdKind _orderIdKindFromWire(wire.WireOrderIdKind value) =>
    _enumByName(OrderIdKind.values, value);

wire.WireOrderStatus _orderStatusToWire(OrderStatus value) =>
    _enumByName(wire.WireOrderStatus.values, value);
OrderStatus _orderStatusFromWire(wire.WireOrderStatus value) =>
    _enumByName(OrderStatus.values, value);

wire.WireOrderType _orderTypeToWire(OrderType value) =>
    _enumByName(wire.WireOrderType.values, value);
OrderType _orderTypeFromWire(wire.WireOrderType value) =>
    _enumByName(OrderType.values, value);

wire.WireTimeInForce _timeInForceToWire(TimeInForce value) =>
    _enumByName(wire.WireTimeInForce.values, value);
TimeInForce _timeInForceFromWire(wire.WireTimeInForce value) =>
    _enumByName(TimeInForce.values, value);

wire.WireMarginMode _marginModeToWire(MarginMode value) =>
    _enumByName(wire.WireMarginMode.values, value);
MarginMode _marginModeFromWire(wire.WireMarginMode value) =>
    _enumByName(MarginMode.values, value);

wire.WireUpbitOrderDirection _upbitOrderDirectionToWire(
  UpbitOrderDirection value,
) => _enumByName(wire.WireUpbitOrderDirection.values, value);
UpbitOrderDirection _upbitOrderDirectionFromWire(
  wire.WireUpbitOrderDirection value,
) => _enumByName(UpbitOrderDirection.values, value);

wire.WireBithumbPendingOrderState _bithumbPendingOrderStateToWire(
  BithumbPendingOrderState value,
) => _enumByName(wire.WireBithumbPendingOrderState.values, value);
BithumbPendingOrderState _bithumbPendingOrderStateFromWire(
  wire.WireBithumbPendingOrderState value,
) => _enumByName(BithumbPendingOrderState.values, value);

wire.WireBithumbOrderDirection _bithumbOrderDirectionToWire(
  BithumbOrderDirection value,
) => _enumByName(wire.WireBithumbOrderDirection.values, value);
BithumbOrderDirection _bithumbOrderDirectionFromWire(
  wire.WireBithumbOrderDirection value,
) => _enumByName(BithumbOrderDirection.values, value);

wire.WireBithumbTwapState _bithumbTwapStateToWire(BithumbTwapState value) =>
    _enumByName(wire.WireBithumbTwapState.values, value);
BithumbTwapState _bithumbTwapStateFromWire(wire.WireBithumbTwapState value) =>
    _enumByName(BithumbTwapState.values, value);

wire.WireBithumbTwapOrderDirection _bithumbTwapOrderDirectionToWire(
  BithumbTwapOrderDirection value,
) => _enumByName(wire.WireBithumbTwapOrderDirection.values, value);
BithumbTwapOrderDirection _bithumbTwapOrderDirectionFromWire(
  wire.WireBithumbTwapOrderDirection value,
) => _enumByName(BithumbTwapOrderDirection.values, value);

wire.WireWithdrawalStatus _withdrawalStatusToWire(WithdrawalStatus value) =>
    _enumByName(wire.WireWithdrawalStatus.values, value);
WithdrawalStatus _withdrawalStatusFromWire(wire.WireWithdrawalStatus value) =>
    _enumByName(WithdrawalStatus.values, value);

wire.WireDepositStatus _depositStatusToWire(DepositStatus value) =>
    _enumByName(wire.WireDepositStatus.values, value);
DepositStatus _depositStatusFromWire(wire.WireDepositStatus value) =>
    _enumByName(DepositStatus.values, value);

Network _networkFromWire(String value) => switch (value) {
  'bitcoin' => Network.bitcoin,
  'ethereum' => Network.ethereum,
  'arbitrum' => Network.arbitrum,
  'bnb_smart_chain' => Network.bnbSmartChain,
  'tron' => Network.tron,
  'solana' => Network.solana,
  'polygon' => Network.polygon,
  'base' => Network.base,
  'optimism' => Network.optimism,
  'avalanche_c' => Network.avalancheC,
  'xrp_ledger' => Network.xrpLedger,
  'stellar' => Network.stellar,
  'cosmos' => Network.cosmos,
  'aptos' => Network.aptos,
  'sui' => Network.sui,
  'ton' => Network.ton,
  'near' => Network.near,
  'polkadot' => Network.polkadot,
  _ => Network.other(value),
};

String _networkToWire(Network value) => value.providerName;

Market _marketFromWire(wire.WireMarket value) => Market(
  _exchangeFromWire(value.exchange),
  _marketKindFromWire(value.kind),
  value.base,
  value.quote,
);
wire.WireMarket _marketToWire(Market value) => wire.WireMarket(
  exchange: _exchangeToWire(value.exchange),
  kind: _marketKindToWire(value.kind),
  base: value.base,
  quote: value.quote,
);

MarketInfo _marketInfoFromWire(wire.WireMarketInfo value) => MarketInfo(
  market: _marketFromWire(value.market),
  nativeSymbol: value.nativeSymbol,
  status: _marketStatusFromWire(value.status),
  koreanName: value.koreanName,
  englishName: value.englishName,
);
wire.WireMarketInfo _marketInfoToWire(MarketInfo value) => wire.WireMarketInfo(
  market: _marketToWire(value.market),
  nativeSymbol: value.nativeSymbol,
  status: _marketStatusToWire(value.status),
  koreanName: value.koreanName,
  englishName: value.englishName,
);

Trade _tradeFromWire(wire.WireTrade value) => Trade(
  market: _marketFromWire(value.market),
  timestamp: _timestampFromWire(value.timestampNs)!,
  price: Decimal.parse(value.price),
  quantity: Decimal.parse(value.quantity),
  takerSide: _sideFromWire(value.takerSide),
  id: value.id,
);
wire.WireTrade _tradeToWire(Trade value) => wire.WireTrade(
  market: _marketToWire(value.market),
  timestampNs: _timestampToWire(value.timestamp),
  price: value.price.toString(),
  quantity: value.quantity.toString(),
  takerSide: _sideToWire(value.takerSide),
  id: value.id,
);

Level _levelFromWire(wire.WireLevel value) => Level(
  price: Decimal.parse(value.price),
  quantity: Decimal.parse(value.quantity),
);
wire.WireLevel _levelToWire(Level value) => wire.WireLevel(
  price: value.price.toString(),
  quantity: value.quantity.toString(),
);

OrderBook _orderBookFromWire(wire.WireOrderBook value) => OrderBook(
  market: _marketFromWire(value.market),
  timestamp: _timestampFromWire(value.timestampNs)!,
  bids: value.bids.map(_levelFromWire).toList(growable: false),
  asks: value.asks.map(_levelFromWire).toList(growable: false),
);
wire.WireOrderBook _orderBookToWire(OrderBook value) => wire.WireOrderBook(
  market: _marketToWire(value.market),
  timestampNs: _timestampToWire(value.timestamp),
  bids: value.bids.map(_levelToWire).toList(growable: false),
  asks: value.asks.map(_levelToWire).toList(growable: false),
);

Ticker _tickerFromWire(wire.WireTicker value) => Ticker(
  market: _marketFromWire(value.market),
  timestamp: _timestampFromWire(value.timestampNs)!,
  lastTradeTime: _timestampFromWire(value.lastTradeTimeNs),
  lastPrice: Decimal.parse(value.lastPrice),
  change: _decimalFromWire(value.change),
  changeRate: _decimalFromWire(value.changeRate),
  high: _decimalFromWire(value.high),
  low: _decimalFromWire(value.low),
  volume: _decimalFromWire(value.volume),
  quoteVolume: _decimalFromWire(value.quoteVolume),
);
wire.WireTicker _tickerToWire(Ticker value) => wire.WireTicker(
  market: _marketToWire(value.market),
  timestampNs: _timestampToWire(value.timestamp),
  lastTradeTimeNs: _optionalTimestampToWire(value.lastTradeTime),
  lastPrice: value.lastPrice.toString(),
  change: value.change?.toString(),
  changeRate: value.changeRate?.toString(),
  high: value.high?.toString(),
  low: value.low?.toString(),
  volume: value.volume?.toString(),
  quoteVolume: value.quoteVolume?.toString(),
);

Candle _candleFromWire(wire.WireCandle value) => Candle(
  market: _marketFromWire(value.market),
  interval: _intervalFromWire(value.interval),
  openTime: _timestampFromWire(value.openTimeNs)!,
  open: Decimal.parse(value.open),
  high: Decimal.parse(value.high),
  low: Decimal.parse(value.low),
  close: Decimal.parse(value.close),
  volume: Decimal.parse(value.volume),
  quoteVolume: _decimalFromWire(value.quoteVolume),
  closed: value.closed,
);
wire.WireCandle _candleToWire(Candle value) => wire.WireCandle(
  market: _marketToWire(value.market),
  interval: _intervalToWire(value.interval),
  openTimeNs: _timestampToWire(value.openTime),
  open: value.open.toString(),
  high: value.high.toString(),
  low: value.low.toString(),
  close: value.close.toString(),
  volume: value.volume.toString(),
  quoteVolume: value.quoteVolume?.toString(),
  closed: value.closed,
);

Balance _balanceFromWire(wire.WireBalance value) => Balance(
  asset: value.asset,
  available: Decimal.parse(value.available),
  locked: Decimal.parse(value.locked),
);
wire.WireBalance _balanceToWire(Balance value) => wire.WireBalance(
  asset: value.asset,
  available: value.available.toString(),
  locked: value.locked.toString(),
);

Order _orderFromWire(wire.WireOrder value) => Order(
  id: value.id,
  market: _marketFromWire(value.market),
  side: _sideFromWire(value.side),
  status: _orderStatusFromWire(value.status),
  filledQuantity: Decimal.parse(value.filledQuantity),
  remainingQuantity: Decimal.parse(value.remainingQuantity),
  price: _decimalFromWire(value.price),
  createdAt: _timestampFromWire(value.createdAtNs),
);
wire.WireOrder _orderToWire(Order value) => wire.WireOrder(
  id: value.id,
  market: _marketToWire(value.market),
  side: _sideToWire(value.side),
  status: _orderStatusToWire(value.status),
  filledQuantity: value.filledQuantity.toString(),
  remainingQuantity: value.remainingQuantity.toString(),
  price: value.price?.toString(),
  createdAtNs: _optionalTimestampToWire(value.createdAt),
);

Position _positionFromWire(wire.WirePosition value) => Position(
  market: _marketFromWire(value.market),
  side: value.side == null ? null : _sideFromWire(value.side!),
  quantity: Decimal.parse(value.quantity),
  entryPrice: _decimalFromWire(value.entryPrice),
  markPrice: _decimalFromWire(value.markPrice),
  notional: _decimalFromWire(value.notional),
  unrealizedPnl: _decimalFromWire(value.unrealizedPnl),
  leverage: _decimalFromWire(value.leverage),
  marginMode: value.marginMode == null
      ? null
      : _marginModeFromWire(value.marginMode!),
);
wire.WirePosition _positionToWire(Position value) => wire.WirePosition(
  market: _marketToWire(value.market),
  side: value.side == null ? null : _sideToWire(value.side!),
  quantity: value.quantity.toString(),
  entryPrice: value.entryPrice?.toString(),
  markPrice: value.markPrice?.toString(),
  notional: value.notional?.toString(),
  unrealizedPnl: value.unrealizedPnl?.toString(),
  leverage: value.leverage?.toString(),
  marginMode: value.marginMode == null
      ? null
      : _marginModeToWire(value.marginMode!),
);

MarginSummary _marginSummaryFromWire(wire.WireMarginSummary value) =>
    MarginSummary(
      asset: value.asset,
      equity: _decimalFromWire(value.equity),
      marginBalance: _decimalFromWire(value.marginBalance),
      availableBalance: _decimalFromWire(value.availableBalance),
    );
wire.WireMarginSummary _marginSummaryToWire(MarginSummary value) =>
    wire.WireMarginSummary(
      asset: value.asset,
      equity: value.equity?.toString(),
      marginBalance: value.marginBalance?.toString(),
      availableBalance: value.availableBalance?.toString(),
    );

FundingRate _fundingRateFromWire(wire.WireFundingRate value) => FundingRate(
  market: _marketFromWire(value.market),
  timestamp: _timestampFromWire(value.timestampNs)!,
  rate: Decimal.parse(value.rate),
  markPrice: _decimalFromWire(value.markPrice),
);
wire.WireFundingRate _fundingRateToWire(FundingRate value) =>
    wire.WireFundingRate(
      market: _marketToWire(value.market),
      timestampNs: _timestampToWire(value.timestamp),
      rate: value.rate.toString(),
      markPrice: value.markPrice?.toString(),
    );

FundingPayment _fundingPaymentFromWire(wire.WireFundingPayment value) =>
    FundingPayment(
      market: _marketFromWire(value.market),
      timestamp: _timestampFromWire(value.timestampNs)!,
      amount: Decimal.parse(value.amount),
      rate: _decimalFromWire(value.rate),
      id: value.id,
    );
wire.WireFundingPayment _fundingPaymentToWire(FundingPayment value) =>
    wire.WireFundingPayment(
      market: _marketToWire(value.market),
      timestampNs: _timestampToWire(value.timestamp),
      amount: value.amount.toString(),
      rate: value.rate?.toString(),
      id: value.id,
    );

OrderAccount _orderAccountFromWire(wire.WireOrderAccount value) => OrderAccount(
  balance: _balanceFromWire(value.balance),
  averageBuyPrice: Decimal.parse(value.averageBuyPrice),
  averageBuyPriceModified: value.averageBuyPriceModified,
  averageBuyPriceUnit: value.averageBuyPriceUnit,
);
wire.WireOrderAccount _orderAccountToWire(OrderAccount value) =>
    wire.WireOrderAccount(
      balance: _balanceToWire(value.balance),
      averageBuyPrice: value.averageBuyPrice.toString(),
      averageBuyPriceModified: value.averageBuyPriceModified,
      averageBuyPriceUnit: value.averageBuyPriceUnit,
    );

OrderOption _orderOptionFromWire(wire.WireOrderOption value) => OrderOption(
  providerId: value.providerId,
  orderType: value.orderType == null
      ? null
      : _orderTypeFromWire(value.orderType!),
  timeInForce: value.timeInForce == null
      ? null
      : _timeInForceFromWire(value.timeInForce!),
);
wire.WireOrderOption _orderOptionToWire(OrderOption value) =>
    wire.WireOrderOption(
      providerId: value.providerId,
      orderType: value.orderType == null
          ? null
          : _orderTypeToWire(value.orderType!),
      timeInForce: value.timeInForce == null
          ? null
          : _timeInForceToWire(value.timeInForce!),
    );

OrderRules _orderRulesFromWire(wire.WireOrderRules value) => OrderRules(
  market: _marketFromWire(value.market),
  marketName: value.marketName,
  status: _marketStatusFromWire(value.status),
  buyFeeRate: Decimal.parse(value.buyFeeRate),
  sellFeeRate: Decimal.parse(value.sellFeeRate),
  makerBuyFeeRate: Decimal.parse(value.makerBuyFeeRate),
  makerSellFeeRate: Decimal.parse(value.makerSellFeeRate),
  sides: value.sides.map(_sideFromWire).toList(growable: false),
  buyOptions: value.buyOptions
      .map(_orderOptionFromWire)
      .toList(growable: false),
  sellOptions: value.sellOptions
      .map(_orderOptionFromWire)
      .toList(growable: false),
  buyPriceUnit: _decimalFromWire(value.buyPriceUnit),
  sellPriceUnit: _decimalFromWire(value.sellPriceUnit),
  minimumBuyTotal: Decimal.parse(value.minimumBuyTotal),
  minimumSellTotal: Decimal.parse(value.minimumSellTotal),
  maximumTotal: Decimal.parse(value.maximumTotal),
  quoteAccount: _orderAccountFromWire(value.quoteAccount),
  baseAccount: _orderAccountFromWire(value.baseAccount),
);
wire.WireOrderRules _orderRulesToWire(OrderRules value) => wire.WireOrderRules(
  market: _marketToWire(value.market),
  marketName: value.marketName,
  status: _marketStatusToWire(value.status),
  buyFeeRate: value.buyFeeRate.toString(),
  sellFeeRate: value.sellFeeRate.toString(),
  makerBuyFeeRate: value.makerBuyFeeRate.toString(),
  makerSellFeeRate: value.makerSellFeeRate.toString(),
  sides: value.sides.map(_sideToWire).toList(growable: false),
  buyOptions: value.buyOptions.map(_orderOptionToWire).toList(growable: false),
  sellOptions: value.sellOptions
      .map(_orderOptionToWire)
      .toList(growable: false),
  buyPriceUnit: value.buyPriceUnit?.toString(),
  sellPriceUnit: value.sellPriceUnit?.toString(),
  minimumBuyTotal: value.minimumBuyTotal.toString(),
  minimumSellTotal: value.minimumSellTotal.toString(),
  maximumTotal: value.maximumTotal.toString(),
  quoteAccount: _orderAccountToWire(value.quoteAccount),
  baseAccount: _orderAccountToWire(value.baseAccount),
);

AssetNetwork _assetNetworkFromWire(wire.WireAssetNetwork value) => AssetNetwork(
  exchange: _exchangeFromWire(value.exchange),
  asset: value.asset,
  network: _networkFromWire(value.network),
  providerId: value.providerId,
  depositEnabled: value.depositEnabled,
  withdrawalEnabled: value.withdrawalEnabled,
  withdrawalFee: value.withdrawalFee == null
      ? null
      : _withdrawalFeeFromWire(value.withdrawalFee!),
  minimumWithdrawal: _decimalFromWire(value.minimumWithdrawal),
  maximumWithdrawal: _decimalFromWire(value.maximumWithdrawal),
  memoRequired: value.memoRequired,
);
wire.WireAssetNetwork _assetNetworkToWire(AssetNetwork value) =>
    wire.WireAssetNetwork(
      exchange: _exchangeToWire(value.exchange),
      asset: value.asset,
      network: _networkToWire(value.network),
      providerId: value.providerId,
      depositEnabled: value.depositEnabled,
      withdrawalEnabled: value.withdrawalEnabled,
      withdrawalFee: value.withdrawalFee == null
          ? null
          : _withdrawalFeeToWire(value.withdrawalFee!),
      minimumWithdrawal: value.minimumWithdrawal?.toString(),
      maximumWithdrawal: value.maximumWithdrawal?.toString(),
      memoRequired: value.memoRequired,
    );

DepositAddress _depositAddressFromWire(wire.WireDepositAddress value) =>
    DepositAddress(
      exchange: _exchangeFromWire(value.exchange),
      asset: value.asset,
      network: _networkFromWire(value.network),
      address: value.address,
      memo: value.memo,
    );
wire.WireDepositAddress _depositAddressToWire(DepositAddress value) =>
    wire.WireDepositAddress(
      exchange: _exchangeToWire(value.exchange),
      asset: value.asset,
      network: _networkToWire(value.network),
      address: value.address,
      memo: value.memo,
    );

DepositAddressEntry _depositAddressEntryFromWire(
  wire.WireDepositAddressEntry value,
) => DepositAddressEntry(
  exchange: _exchangeFromWire(value.exchange),
  asset: value.asset,
  network: value.network == null ? null : _networkFromWire(value.network!),
  providerNetwork: value.providerNetwork,
  address: value.address,
  memo: value.memo,
);
wire.WireDepositAddressEntry _depositAddressEntryToWire(
  DepositAddressEntry value,
) => wire.WireDepositAddressEntry(
  exchange: _exchangeToWire(value.exchange),
  asset: value.asset,
  network: value.network == null ? null : _networkToWire(value.network!),
  providerNetwork: value.providerNetwork,
  address: value.address,
  memo: value.memo,
);

ExchangeDestination _exchangeDestinationFromWire(
  wire.WireExchangeDestination value,
) => ExchangeDestination(
  exchange: _exchangeFromWire(value.exchange),
  asset: value.asset,
  network: _networkFromWire(value.network),
  address: value.address,
  memo: value.memo,
);
wire.WireExchangeDestination _exchangeDestinationToWire(
  ExchangeDestination value,
) => wire.WireExchangeDestination(
  exchange: _exchangeToWire(value.exchange),
  asset: value.asset,
  network: _networkToWire(value.network),
  address: value.address,
  memo: value.memo,
);

ChainDestination _chainDestinationFromWire(wire.WireChainDestination value) =>
    ChainDestination(
      asset: value.asset,
      network: _networkFromWire(value.network),
      address: value.address,
      memo: value.memo,
    );
wire.WireChainDestination _chainDestinationToWire(ChainDestination value) =>
    wire.WireChainDestination(
      asset: value.asset,
      network: _networkToWire(value.network),
      address: value.address,
      memo: value.memo,
    );

ExchangeTransferRequest _exchangeTransferRequestFromWire(
  wire.WireExchangeTransferRequest value,
) => ExchangeTransferRequest(
  asset: value.asset,
  sourceNetwork: value.sourceNetwork == null
      ? null
      : _networkFromWire(value.sourceNetwork!),
  destinationNetwork: value.destinationNetwork == null
      ? null
      : _networkFromWire(value.destinationNetwork!),
  amount: Decimal.parse(value.amount),
);
wire.WireExchangeTransferRequest _exchangeTransferRequestToWire(
  ExchangeTransferRequest value,
) => wire.WireExchangeTransferRequest(
  asset: value.asset,
  sourceNetwork: value.sourceNetwork == null
      ? null
      : _networkToWire(value.sourceNetwork!),
  destinationNetwork: value.destinationNetwork == null
      ? null
      : _networkToWire(value.destinationNetwork!),
  amount: value.amount.toString(),
);

ChainTransferRequest _chainTransferRequestFromWire(
  wire.WireChainTransferRequest value,
) => ChainTransferRequest(
  asset: value.asset,
  sourceNetwork: value.sourceNetwork == null
      ? null
      : _networkFromWire(value.sourceNetwork!),
  destination: _chainDestinationFromWire(value.destination),
  amount: Decimal.parse(value.amount),
);
wire.WireChainTransferRequest _chainTransferRequestToWire(
  ChainTransferRequest value,
) => wire.WireChainTransferRequest(
  asset: value.asset,
  sourceNetwork: value.sourceNetwork == null
      ? null
      : _networkToWire(value.sourceNetwork!),
  destination: _chainDestinationToWire(value.destination),
  amount: value.amount.toString(),
);

TransferDestination _transferDestinationFromWire(
  wire.WireTransferDestination value,
) => switch (value) {
  wire.WireTransferDestination_Exchange(:final field0) =>
    TransferDestination.exchange(_exchangeDestinationFromWire(field0)),
  wire.WireTransferDestination_Chain(:final field0) =>
    TransferDestination.chain(_chainDestinationFromWire(field0)),
};

wire.WireTransferDestination _transferDestinationToWire(
  TransferDestination value,
) => switch (value) {
  TransferDestinationExchange(:final value) =>
    wire.WireTransferDestination.exchange(_exchangeDestinationToWire(value)),
  TransferDestinationChain(:final value) => wire.WireTransferDestination.chain(
    _chainDestinationToWire(value),
  ),
};

WithdrawalFee _withdrawalFeeFromWire(wire.WireWithdrawalFee value) =>
    switch (value) {
      wire.WireWithdrawalFee_Fixed(:final field0) => WithdrawalFee.fixed(
        Decimal.parse(field0),
      ),
      wire.WireWithdrawalFee_Rate(
        :final rate,
        :final minimum,
        :final maximum,
      ) =>
        WithdrawalFee.rate(
          rate: Decimal.parse(rate),
          minimum: _decimalFromWire(minimum),
          maximum: _decimalFromWire(maximum),
        ),
    };

wire.WireWithdrawalFee _withdrawalFeeToWire(WithdrawalFee value) =>
    switch (value) {
      WithdrawalFeeFixed(:final value) => wire.WireWithdrawalFee.fixed(
        value.toString(),
      ),
      WithdrawalFeeRate(:final rate, :final minimum, :final maximum) =>
        wire.WireWithdrawalFee.rate(
          rate: rate.toString(),
          minimum: minimum?.toString(),
          maximum: maximum?.toString(),
        ),
    };

TravelRuleRequirement _travelRuleRequirementFromWire(
  wire.WireTravelRuleRequirement value,
) => switch (value) {
  wire.WireTravelRuleRequirement_NotRequired() =>
    const TravelRuleRequirement.notRequired(),
  wire.WireTravelRuleRequirement_Required(:final consentUrl) =>
    TravelRuleRequirement.required(consentUrl: consentUrl),
};

wire.WireTravelRuleRequirement _travelRuleRequirementToWire(
  TravelRuleRequirement value,
) => switch (value) {
  TravelRuleRequirementNotRequired() =>
    const wire.WireTravelRuleRequirement.notRequired(),
  TravelRuleRequirementRequired(:final consentUrl) =>
    wire.WireTravelRuleRequirement.required_(consentUrl: consentUrl),
};

WithdrawalQuote _withdrawalQuoteFromWire(wire.WireWithdrawalQuote value) =>
    WithdrawalQuote(
      fee: _decimalFromWire(value.fee),
      expectedReceive: _decimalFromWire(value.expectedReceive),
      minimumAmount: _decimalFromWire(value.minimumAmount),
      maximumAmount: _decimalFromWire(value.maximumAmount),
      addressAllowed: value.addressAllowed,
      travelRule: _travelRuleRequirementFromWire(value.travelRule),
      expiresAt: _timestampFromWire(value.expiresAtNs),
    );
wire.WireWithdrawalQuote _withdrawalQuoteToWire(WithdrawalQuote value) =>
    wire.WireWithdrawalQuote(
      fee: value.fee?.toString(),
      expectedReceive: value.expectedReceive?.toString(),
      minimumAmount: value.minimumAmount?.toString(),
      maximumAmount: value.maximumAmount?.toString(),
      addressAllowed: value.addressAllowed,
      travelRule: _travelRuleRequirementToWire(value.travelRule),
      expiresAtNs: _optionalTimestampToWire(value.expiresAt),
    );

TransferPlan _transferPlanFromWire(wire.WireTransferPlan value) => TransferPlan(
  source: _exchangeFromWire(value.source),
  destination: value.destination == null
      ? null
      : _exchangeFromWire(value.destination!),
  request: _withdrawRequestFromWire(value.request),
  quote: _withdrawalQuoteFromWire(value.quote),
  createdAt: _timestampFromWire(value.createdAtNs)!,
  expiresAt: _timestampFromWire(value.expiresAtNs)!,
);
wire.WireTransferPlan _transferPlanToWire(TransferPlan value) =>
    wire.WireTransferPlan(
      source: _exchangeToWire(value.source),
      destination: value.destination == null
          ? null
          : _exchangeToWire(value.destination!),
      request: _withdrawRequestToWire(value.request),
      quote: _withdrawalQuoteToWire(value.quote),
      createdAtNs: _timestampToWire(value.createdAt),
      expiresAtNs: _timestampToWire(value.expiresAt),
    );

Withdrawal _withdrawalFromWire(wire.WireWithdrawal value) => Withdrawal(
  id: value.id,
  asset: value.asset,
  network: value.network == null ? null : _networkFromWire(value.network!),
  providerNetwork: value.providerNetwork,
  amount: Decimal.parse(value.amount),
  fee: _decimalFromWire(value.fee),
  destination: value.destination == null
      ? null
      : _transferDestinationFromWire(value.destination!),
  status: _withdrawalStatusFromWire(value.status),
  providerStatus: value.providerStatus,
  txId: value.txId,
  createdAt: _timestampFromWire(value.createdAtNs),
);
wire.WireWithdrawal _withdrawalToWire(Withdrawal value) => wire.WireWithdrawal(
  id: value.id,
  asset: value.asset,
  network: value.network == null ? null : _networkToWire(value.network!),
  providerNetwork: value.providerNetwork,
  amount: value.amount.toString(),
  fee: value.fee?.toString(),
  destination: value.destination == null
      ? null
      : _transferDestinationToWire(value.destination!),
  status: _withdrawalStatusToWire(value.status),
  providerStatus: value.providerStatus,
  txId: value.txId,
  createdAtNs: _optionalTimestampToWire(value.createdAt),
);

Deposit _depositFromWire(wire.WireDeposit value) => Deposit(
  id: value.id,
  asset: value.asset,
  network: value.network == null ? null : _networkFromWire(value.network!),
  providerNetwork: value.providerNetwork,
  amount: Decimal.parse(value.amount),
  address: value.address,
  memo: value.memo,
  status: _depositStatusFromWire(value.status),
  providerStatus: value.providerStatus,
  txId: value.txId,
  createdAt: _timestampFromWire(value.createdAtNs),
);
wire.WireDeposit _depositToWire(Deposit value) => wire.WireDeposit(
  id: value.id,
  asset: value.asset,
  network: value.network == null ? null : _networkToWire(value.network!),
  providerNetwork: value.providerNetwork,
  amount: value.amount.toString(),
  address: value.address,
  memo: value.memo,
  status: _depositStatusToWire(value.status),
  providerStatus: value.providerStatus,
  txId: value.txId,
  createdAtNs: _optionalTimestampToWire(value.createdAt),
);

CancelledOrder _cancelledOrderFromWire(wire.WireCancelledOrder value) =>
    CancelledOrder(
      orderId: value.orderId,
      clientId: value.clientId,
      market: value.market == null ? null : _marketFromWire(value.market!),
      cancelledAt: _timestampFromWire(value.cancelledAtNs),
    );
wire.WireCancelledOrder _cancelledOrderToWire(CancelledOrder value) =>
    wire.WireCancelledOrder(
      orderId: value.orderId,
      clientId: value.clientId,
      market: value.market == null ? null : _marketToWire(value.market!),
      cancelledAtNs: _optionalTimestampToWire(value.cancelledAt),
    );

OrderCancelFailure _orderCancelFailureFromWire(
  wire.WireOrderCancelFailure value,
) => OrderCancelFailure(
  orderId: value.orderId,
  clientId: value.clientId,
  market: value.market == null ? null : _marketFromWire(value.market!),
  code: value.code,
  message: value.message,
);
wire.WireOrderCancelFailure _orderCancelFailureToWire(
  OrderCancelFailure value,
) => wire.WireOrderCancelFailure(
  orderId: value.orderId,
  clientId: value.clientId,
  market: value.market == null ? null : _marketToWire(value.market!),
  code: value.code,
  message: value.message,
);

CancelOrdersResult _cancelOrdersResultFromWire(
  wire.WireCancelOrdersResult value,
) => CancelOrdersResult(
  cancelled: value.cancelled
      .map(_cancelledOrderFromWire)
      .toList(growable: false),
  failed: value.failed.map(_orderCancelFailureFromWire).toList(growable: false),
);
wire.WireCancelOrdersResult _cancelOrdersResultToWire(
  CancelOrdersResult value,
) => wire.WireCancelOrdersResult(
  cancelled: value.cancelled.map(_cancelledOrderToWire).toList(growable: false),
  failed: value.failed.map(_orderCancelFailureToWire).toList(growable: false),
);

OrderLookupRequest _orderLookupRequestFromWire(
  wire.WireOrderLookupRequest value,
) => OrderLookupRequest(
  kind: _orderIdKindFromWire(value.kind),
  ids: value.ids,
  market: value.market == null ? null : _marketFromWire(value.market!),
);
wire.WireOrderLookupRequest _orderLookupRequestToWire(
  OrderLookupRequest value,
) => wire.WireOrderLookupRequest(
  kind: _orderIdKindToWire(value.kind),
  ids: value.ids.toList(growable: false),
  market: value.market == null ? null : _marketToWire(value.market!),
);

CancelOrdersRequest _cancelOrdersRequestFromWire(
  wire.WireCancelOrdersRequest value,
) =>
    CancelOrdersRequest(kind: _orderIdKindFromWire(value.kind), ids: value.ids);
wire.WireCancelOrdersRequest _cancelOrdersRequestToWire(
  CancelOrdersRequest value,
) => wire.WireCancelOrdersRequest(
  kind: _orderIdKindToWire(value.kind),
  ids: value.ids.toList(growable: false),
);

OrderHistoryRequest _orderHistoryRequestFromWire(
  wire.WireOrderHistoryRequest value,
) => OrderHistoryRequest(
  market: value.market == null ? null : _marketFromWire(value.market!),
  statuses: value.statuses.map(_orderStatusFromWire).toList(growable: false),
  from: _timestampFromWire(value.fromNs),
  to: _timestampFromWire(value.toNs),
  cursor: value.cursor == null ? null : Cursor(value.cursor!),
  limit: value.limit,
);
wire.WireOrderHistoryRequest _orderHistoryRequestToWire(
  OrderHistoryRequest value,
) => wire.WireOrderHistoryRequest(
  market: value.market == null ? null : _marketToWire(value.market!),
  statuses: value.statuses.map(_orderStatusToWire).toList(growable: false),
  fromNs: _optionalTimestampToWire(value.from),
  toNs: _optionalTimestampToWire(value.to),
  cursor: value.cursor?.value,
  limit: checkedUint32(value.limit, field: 'limit'),
);

DepositAddressRequest _depositAddressRequestFromWire(
  wire.WireDepositAddressRequest value,
) => DepositAddressRequest(
  asset: value.asset,
  network: _networkFromWire(value.network),
  amount: _decimalFromWire(value.amount),
);
wire.WireDepositAddressRequest _depositAddressRequestToWire(
  DepositAddressRequest value,
) => wire.WireDepositAddressRequest(
  asset: value.asset,
  network: _networkToWire(value.network),
  amount: value.amount?.toString(),
);

WithdrawRequest _withdrawRequestFromWire(wire.WireWithdrawRequest value) =>
    WithdrawRequest(
      asset: value.asset,
      network: _networkFromWire(value.network),
      amount: Decimal.parse(value.amount),
      destination: _transferDestinationFromWire(value.destination),
      clientId: value.clientId,
    );
wire.WireWithdrawRequest _withdrawRequestToWire(WithdrawRequest value) =>
    wire.WireWithdrawRequest(
      asset: value.asset,
      network: _networkToWire(value.network),
      amount: value.amount.toString(),
      destination: _transferDestinationToWire(value.destination),
      clientId: value.clientId,
    );

TransferLookupRequest _transferLookupRequestFromWire(
  wire.WireTransferLookupRequest value,
) => TransferLookupRequest(asset: value.asset, id: value.id, txId: value.txId);
wire.WireTransferLookupRequest _transferLookupRequestToWire(
  TransferLookupRequest value,
) => wire.WireTransferLookupRequest(
  asset: value.asset,
  id: value.id,
  txId: value.txId,
);

TransferHistoryRequest _transferHistoryRequestFromWire(
  wire.WireTransferHistoryRequest value,
) => TransferHistoryRequest(
  asset: value.asset,
  network: value.network == null ? null : _networkFromWire(value.network!),
  cursor: value.cursor == null ? null : Cursor(value.cursor!),
  limit: value.limit,
);
wire.WireTransferHistoryRequest _transferHistoryRequestToWire(
  TransferHistoryRequest value,
) => wire.WireTransferHistoryRequest(
  asset: value.asset,
  network: value.network == null ? null : _networkToWire(value.network!),
  cursor: value.cursor?.value,
  limit: checkedUint32(value.limit, field: 'limit'),
);

UpbitYearCandle _upbitYearCandleFromWire(wire.WireUpbitYearCandle value) =>
    UpbitYearCandle(
      market: _marketFromWire(value.market),
      openTime: _timestampFromWire(value.openTimeNs)!,
      koreaOpenTime: _timestampFromWire(value.koreaOpenTimeNs),
      timestamp: _timestampFromWire(value.timestampNs)!,
      open: Decimal.parse(value.open),
      high: Decimal.parse(value.high),
      low: Decimal.parse(value.low),
      close: Decimal.parse(value.close),
      volume: Decimal.parse(value.volume),
      quoteVolume: Decimal.parse(value.quoteVolume),
      firstDayOfPeriod: value.firstDayOfPeriod,
    );
wire.WireUpbitYearCandle _upbitYearCandleToWire(UpbitYearCandle value) =>
    wire.WireUpbitYearCandle(
      market: _marketToWire(value.market),
      openTimeNs: _timestampToWire(value.openTime),
      koreaOpenTimeNs: _optionalTimestampToWire(value.koreaOpenTime),
      timestampNs: _timestampToWire(value.timestamp),
      open: value.open.toString(),
      high: value.high.toString(),
      low: value.low.toString(),
      close: value.close.toString(),
      volume: value.volume.toString(),
      quoteVolume: value.quoteVolume.toString(),
      firstDayOfPeriod: value.firstDayOfPeriod,
    );

UpbitOrderBookInstrument _upbitOrderBookInstrumentFromWire(
  wire.WireUpbitOrderBookInstrument value,
) => UpbitOrderBookInstrument(
  market: _marketFromWire(value.market),
  quoteCurrency: value.quoteCurrency,
  tickSize: Decimal.parse(value.tickSize),
  supportedLevels: value.supportedLevels
      .map(Decimal.parse)
      .toList(growable: false),
);
wire.WireUpbitOrderBookInstrument _upbitOrderBookInstrumentToWire(
  UpbitOrderBookInstrument value,
) => wire.WireUpbitOrderBookInstrument(
  market: _marketToWire(value.market),
  quoteCurrency: value.quoteCurrency,
  tickSize: value.tickSize.toString(),
  supportedLevels: value.supportedLevels
      .map((item) => item.toString())
      .toList(growable: false),
);

UpbitDepositInfo _upbitDepositInfoFromWire(wire.WireUpbitDepositInfo value) =>
    UpbitDepositInfo(
      asset: value.asset,
      network: value.network == null ? null : _networkFromWire(value.network!),
      providerNetwork: value.providerNetwork,
      isDepositPossible: value.isDepositPossible,
      depositImpossibleReason: value.depositImpossibleReason,
      minimumDepositAmount: Decimal.parse(value.minimumDepositAmount),
      minimumDepositConfirmations: value.minimumDepositConfirmations,
      decimalPrecision: value.decimalPrecision,
    );
wire.WireUpbitDepositInfo _upbitDepositInfoToWire(UpbitDepositInfo value) =>
    wire.WireUpbitDepositInfo(
      asset: value.asset,
      network: value.network == null ? null : _networkToWire(value.network!),
      providerNetwork: value.providerNetwork,
      isDepositPossible: value.isDepositPossible,
      depositImpossibleReason: value.depositImpossibleReason,
      minimumDepositAmount: value.minimumDepositAmount.toString(),
      minimumDepositConfirmations: value.minimumDepositConfirmations,
      decimalPrecision: value.decimalPrecision,
    );

UpbitBatchCancelScope _upbitBatchCancelScopeFromWire(
  wire.WireUpbitBatchCancelScope value,
) => switch (value) {
  wire.WireUpbitBatchCancelScope_All() => const UpbitBatchCancelScope.all(),
  wire.WireUpbitBatchCancelScope_QuoteCurrencies(:final values) =>
    UpbitBatchCancelScope.quoteCurrencies(values: values),
  wire.WireUpbitBatchCancelScope_Pairs(:final values) =>
    UpbitBatchCancelScope.pairs(
      values: values.map(_marketFromWire).toList(growable: false),
    ),
};

wire.WireUpbitBatchCancelScope _upbitBatchCancelScopeToWire(
  UpbitBatchCancelScope value,
) => switch (value) {
  UpbitBatchCancelScopeAll() => const wire.WireUpbitBatchCancelScope.all(),
  UpbitBatchCancelScopeQuoteCurrencies(:final values) =>
    wire.WireUpbitBatchCancelScope.quoteCurrencies(
      values: values.toList(growable: false),
    ),
  UpbitBatchCancelScopePairs(:final values) =>
    wire.WireUpbitBatchCancelScope.pairs(
      values: values.map(_marketToWire).toList(growable: false),
    ),
};

UpbitBatchCancelRequest _upbitBatchCancelRequestFromWire(
  wire.WireUpbitBatchCancelRequest value,
) => UpbitBatchCancelRequest(
  scope: _upbitBatchCancelScopeFromWire(value.scope),
  excludedPairs: value.excludedPairs == null
      ? null
      : value.excludedPairs!.map(_marketFromWire).toList(growable: false),
  side: value.side == null ? null : _sideFromWire(value.side!),
  count: value.count,
  orderBy: value.orderBy == null
      ? null
      : _upbitOrderDirectionFromWire(value.orderBy!),
);
wire.WireUpbitBatchCancelRequest _upbitBatchCancelRequestToWire(
  UpbitBatchCancelRequest value,
) => wire.WireUpbitBatchCancelRequest(
  scope: _upbitBatchCancelScopeToWire(value.scope),
  excludedPairs: value.excludedPairs == null
      ? null
      : value.excludedPairs!.map(_marketToWire).toList(growable: false),
  side: value.side == null ? null : _sideToWire(value.side!),
  count: checkedUint32(value.count, field: 'count'),
  orderBy: value.orderBy == null
      ? null
      : _upbitOrderDirectionToWire(value.orderBy!),
);

BithumbNotice _bithumbNoticeFromWire(wire.WireBithumbNotice value) =>
    BithumbNotice(
      categories: value.categories,
      title: value.title,
      url: value.url,
      publishedAt: _timestampFromWire(value.publishedAtNs)!,
      modifiedAt: _timestampFromWire(value.modifiedAtNs)!,
    );
wire.WireBithumbNotice _bithumbNoticeToWire(BithumbNotice value) =>
    wire.WireBithumbNotice(
      categories: value.categories.toList(growable: false),
      title: value.title,
      url: value.url,
      publishedAtNs: _timestampToWire(value.publishedAt),
      modifiedAtNs: _timestampToWire(value.modifiedAt),
    );

BithumbApiKey _bithumbApiKeyFromWire(wire.WireBithumbApiKey value) =>
    BithumbApiKey(
      accessKey: value.accessKey,
      expiresAt: _timestampFromWire(value.expiresAtNs)!,
    );
wire.WireBithumbApiKey _bithumbApiKeyToWire(BithumbApiKey value) =>
    wire.WireBithumbApiKey(
      accessKey: value.accessKey,
      expiresAtNs: _timestampToWire(value.expiresAt),
    );

BithumbPendingOrdersRequest _bithumbPendingOrdersRequestFromWire(
  wire.WireBithumbPendingOrdersRequest value,
) => BithumbPendingOrdersRequest(
  market: value.market == null ? null : _marketFromWire(value.market!),
  state: value.state == null
      ? null
      : _bithumbPendingOrderStateFromWire(value.state!),
  limit: value.limit,
  orderBy: value.orderBy == null
      ? null
      : _bithumbOrderDirectionFromWire(value.orderBy!),
  cursor: value.cursor == null ? null : Cursor(value.cursor!),
);
wire.WireBithumbPendingOrdersRequest _bithumbPendingOrdersRequestToWire(
  BithumbPendingOrdersRequest value,
) => wire.WireBithumbPendingOrdersRequest(
  market: value.market == null ? null : _marketToWire(value.market!),
  state: value.state == null
      ? null
      : _bithumbPendingOrderStateToWire(value.state!),
  limit: checkedUint32(value.limit, field: 'limit'),
  orderBy: value.orderBy == null
      ? null
      : _bithumbOrderDirectionToWire(value.orderBy!),
  cursor: value.cursor?.value,
);

BithumbTwapOrdersRequest _bithumbTwapOrdersRequestFromWire(
  wire.WireBithumbTwapOrdersRequest value,
) => BithumbTwapOrdersRequest(
  market: value.market == null ? null : _marketFromWire(value.market!),
  uuids: value.uuids,
  state: value.state == null ? null : _bithumbTwapStateFromWire(value.state!),
  cursor: value.cursor == null ? null : Cursor(value.cursor!),
  limit: value.limit,
  orderBy: value.orderBy == null
      ? null
      : _bithumbTwapOrderDirectionFromWire(value.orderBy!),
);
wire.WireBithumbTwapOrdersRequest _bithumbTwapOrdersRequestToWire(
  BithumbTwapOrdersRequest value,
) => wire.WireBithumbTwapOrdersRequest(
  market: value.market == null ? null : _marketToWire(value.market!),
  uuids: value.uuids.toList(growable: false),
  state: value.state == null ? null : _bithumbTwapStateToWire(value.state!),
  cursor: value.cursor?.value,
  limit: checkedUint32(value.limit, field: 'limit'),
  orderBy: value.orderBy == null
      ? null
      : _bithumbTwapOrderDirectionToWire(value.orderBy!),
);

BithumbTwapOrderRequest _bithumbTwapOrderRequestFromWire(
  wire.WireBithumbTwapOrderRequest value,
) => BithumbTwapOrderRequest(
  market: _marketFromWire(value.market),
  side: _sideFromWire(value.side),
  volume: _decimalFromWire(value.volume),
  price: _decimalFromWire(value.price),
  duration: value.duration,
  frequency: value.frequency,
);
wire.WireBithumbTwapOrderRequest _bithumbTwapOrderRequestToWire(
  BithumbTwapOrderRequest value,
) => wire.WireBithumbTwapOrderRequest(
  market: _marketToWire(value.market),
  side: _sideToWire(value.side),
  volume: value.volume?.toString(),
  price: value.price?.toString(),
  duration: checkedRequiredUint32(value.duration, field: 'duration'),
  frequency: checkedRequiredUint32(value.frequency, field: 'frequency'),
);

BithumbTwapOrder _bithumbTwapOrderFromWire(wire.WireBithumbTwapOrder value) =>
    BithumbTwapOrder(
      id: value.id,
      side: _sideFromWire(value.side),
      price: Decimal.parse(value.price),
      state: _bithumbTwapStateFromWire(value.state),
      market: _marketFromWire(value.market),
      createdAt: _timestampFromWire(value.createdAtNs)!,
      volume: Decimal.parse(value.volume),
      finishedAt: _timestampFromWire(value.finishedAtNs),
      totalOrderCount: value.totalOrderCount,
      totalTradesCount: value.totalTradesCount,
      progressCount: value.progressCount,
      totalExecutedAmount: Decimal.parse(value.totalExecutedAmount),
      totalExecutedVolume: Decimal.parse(value.totalExecutedVolume),
      avgTradePrice: Decimal.parse(value.avgTradePrice),
      walletId: value.walletId,
      canceledAt: _timestampFromWire(value.canceledAtNs),
      cancelType: value.cancelType,
    );
wire.WireBithumbTwapOrder _bithumbTwapOrderToWire(BithumbTwapOrder value) =>
    wire.WireBithumbTwapOrder(
      id: value.id,
      side: _sideToWire(value.side),
      price: value.price.toString(),
      state: _bithumbTwapStateToWire(value.state),
      market: _marketToWire(value.market),
      createdAtNs: _timestampToWire(value.createdAt),
      volume: value.volume.toString(),
      finishedAtNs: _optionalTimestampToWire(value.finishedAt),
      totalOrderCount: checkedRequiredUint32(
        value.totalOrderCount,
        field: 'total_order_count',
      ),
      totalTradesCount: checkedRequiredUint32(
        value.totalTradesCount,
        field: 'total_trades_count',
      ),
      progressCount: checkedRequiredUint32(
        value.progressCount,
        field: 'progress_count',
      ),
      totalExecutedAmount: value.totalExecutedAmount.toString(),
      totalExecutedVolume: value.totalExecutedVolume.toString(),
      avgTradePrice: value.avgTradePrice.toString(),
      walletId: value.walletId,
      canceledAtNs: _optionalTimestampToWire(value.canceledAt),
      cancelType: value.cancelType,
    );

BithumbAssetFee _bithumbAssetFeeFromWire(wire.WireBithumbAssetFee value) =>
    BithumbAssetFee(
      displayName: value.displayName,
      asset: value.asset,
      networks: value.networks
          .map(_bithumbNetworkFeeFromWire)
          .toList(growable: false),
    );
wire.WireBithumbAssetFee _bithumbAssetFeeToWire(BithumbAssetFee value) =>
    wire.WireBithumbAssetFee(
      displayName: value.displayName,
      asset: value.asset,
      networks: value.networks
          .map(_bithumbNetworkFeeToWire)
          .toList(growable: false),
    );

BithumbNetworkFee _bithumbNetworkFeeFromWire(
  wire.WireBithumbNetworkFee value,
) => BithumbNetworkFee(
  network: _networkFromWire(value.network),
  providerName: value.providerName,
  depositFee: Decimal.parse(value.depositFee),
  minimumDeposit: Decimal.parse(value.minimumDeposit),
  withdrawalFee: _withdrawalFeeFromWire(value.withdrawalFee),
  minimumWithdrawal: Decimal.parse(value.minimumWithdrawal),
);
wire.WireBithumbNetworkFee _bithumbNetworkFeeToWire(BithumbNetworkFee value) =>
    wire.WireBithumbNetworkFee(
      network: _networkToWire(value.network),
      providerName: value.providerName,
      depositFee: value.depositFee.toString(),
      minimumDeposit: value.minimumDeposit.toString(),
      withdrawalFee: _withdrawalFeeToWire(value.withdrawalFee),
      minimumWithdrawal: value.minimumWithdrawal.toString(),
    );

BinanceMarkPrice _binanceMarkPriceFromWire(wire.WireBinanceMarkPrice value) =>
    BinanceMarkPrice(
      market: _marketFromWire(value.market),
      markPrice: Decimal.parse(value.markPrice),
      indexPrice: Decimal.parse(value.indexPrice),
      estimatedSettlePrice: _decimalFromWire(value.estimatedSettlePrice),
      lastFundingRate: Decimal.parse(value.lastFundingRate),
      interestRate: Decimal.parse(value.interestRate),
      nextFundingTime: _timestampFromWire(value.nextFundingTimeNs)!,
      time: _timestampFromWire(value.timeNs)!,
    );
wire.WireBinanceMarkPrice _binanceMarkPriceToWire(BinanceMarkPrice value) =>
    wire.WireBinanceMarkPrice(
      market: _marketToWire(value.market),
      markPrice: value.markPrice.toString(),
      indexPrice: value.indexPrice.toString(),
      estimatedSettlePrice: value.estimatedSettlePrice?.toString(),
      lastFundingRate: value.lastFundingRate.toString(),
      interestRate: value.interestRate.toString(),
      nextFundingTimeNs: _timestampToWire(value.nextFundingTime),
      timeNs: _timestampToWire(value.time),
    );

BinanceOpenInterest _binanceOpenInterestFromWire(
  wire.WireBinanceOpenInterest value,
) => BinanceOpenInterest(
  market: _marketFromWire(value.market),
  openInterest: Decimal.parse(value.openInterest),
  time: _timestampFromWire(value.timeNs)!,
);
wire.WireBinanceOpenInterest _binanceOpenInterestToWire(
  BinanceOpenInterest value,
) => wire.WireBinanceOpenInterest(
  market: _marketToWire(value.market),
  openInterest: value.openInterest.toString(),
  timeNs: _timestampToWire(value.time),
);

HyperliquidMidPrice _hyperliquidMidPriceFromWire(
  wire.WireHyperliquidMidPrice value,
) => HyperliquidMidPrice(
  market: _marketFromWire(value.market),
  price: Decimal.parse(value.price),
);
wire.WireHyperliquidMidPrice _hyperliquidMidPriceToWire(
  HyperliquidMidPrice value,
) => wire.WireHyperliquidMidPrice(
  market: _marketToWire(value.market),
  price: value.price.toString(),
);

Page<Deposit> _depositPageFromWire(wire.WireDepositPage value) => Page(
  items: value.items.map(_depositFromWire),
  next: value.next == null ? null : Cursor(value.next!),
);
wire.WireDepositPage _depositPageToWire(Page<Deposit> value) =>
    wire.WireDepositPage(
      items: value.items.map(_depositToWire).toList(growable: false),
      next: value.next?.value,
    );

Page<Withdrawal> _withdrawalPageFromWire(wire.WireWithdrawalPage value) => Page(
  items: value.items.map(_withdrawalFromWire),
  next: value.next == null ? null : Cursor(value.next!),
);
wire.WireWithdrawalPage _withdrawalPageToWire(Page<Withdrawal> value) =>
    wire.WireWithdrawalPage(
      items: value.items.map(_withdrawalToWire).toList(growable: false),
      next: value.next?.value,
    );

Page<Order> _orderPageFromWire(wire.WireOrderPage value) => Page(
  items: value.items.map(_orderFromWire),
  next: value.next == null ? null : Cursor(value.next!),
);
wire.WireOrderPage _orderPageToWire(Page<Order> value) => wire.WireOrderPage(
  items: value.items.map(_orderToWire).toList(growable: false),
  next: value.next?.value,
);

Page<FundingRate> _fundingRatePageFromWire(wire.WireFundingRatePage value) =>
    Page(
      items: value.items.map(_fundingRateFromWire),
      next: value.next == null ? null : Cursor(value.next!),
    );
wire.WireFundingRatePage _fundingRatePageToWire(Page<FundingRate> value) =>
    wire.WireFundingRatePage(
      items: value.items.map(_fundingRateToWire).toList(growable: false),
      next: value.next?.value,
    );

Page<FundingPayment> _fundingPaymentPageFromWire(
  wire.WireFundingPaymentPage value,
) => Page(
  items: value.items.map(_fundingPaymentFromWire),
  next: value.next == null ? null : Cursor(value.next!),
);
wire.WireFundingPaymentPage _fundingPaymentPageToWire(
  Page<FundingPayment> value,
) => wire.WireFundingPaymentPage(
  items: value.items.map(_fundingPaymentToWire).toList(growable: false),
  next: value.next?.value,
);

Page<BithumbTwapOrder> _bithumbTwapOrderPageFromWire(
  wire.WireBithumbTwapOrderPage value,
) => Page(
  items: value.items.map(_bithumbTwapOrderFromWire),
  next: value.next == null ? null : Cursor(value.next!),
);
wire.WireBithumbTwapOrderPage _bithumbTwapOrderPageToWire(
  Page<BithumbTwapOrder> value,
) => wire.WireBithumbTwapOrderPage(
  items: value.items.map(_bithumbTwapOrderToWire).toList(growable: false),
  next: value.next?.value,
);

Object _nativeError(wire.NativeError value) => switch (value.kind) {
  wire.NativeErrorKind.invalidRequest => InvalidRequestError(
    field: value.field ?? 'request',
    detail: value.detail ?? value.message,
  ),
  wire.NativeErrorKind.transfer => TransferError(
    kind: _enumByName(TransferErrorKind.values, value.transferKind!),
    detail: value.detail ?? value.message,
  ),
  wire.NativeErrorKind.unsupported => _unsupportedErrorFromWire(value),
  wire.NativeErrorKind.adapter => AdapterError(value.detail ?? value.message),
  wire.NativeErrorKind.auth => AuthenticationError(
    value.detail ?? value.message,
  ),
  wire.NativeErrorKind.exchange => _exchangeErrorFromWire(value),
  wire.NativeErrorKind.transport => TransportError(
    value.detail ?? value.message,
  ),
  wire.NativeErrorKind.decode => DecodeError(value.detail ?? value.message),
};
wire.NativeError _errorToWire(
  Object value, {
  Feature? feature,
  Exchange? exchange,
}) {
  final message = value.toString();
  return switch (value) {
    InvalidRequestError error => wire.NativeError(
      kind: wire.NativeErrorKind.invalidRequest,
      message: message,
      detail: error.detail,
      field: error.field,
      retryable: false,
      rateLimited: false,
    ),
    TransferError error => wire.NativeError(
      kind: wire.NativeErrorKind.transfer,
      message: message,
      detail: error.detail,
      transferKind: _enumByName(wire.WireTransferErrorKind.values, error.kind),
      retryable: false,
      rateLimited: false,
    ),
    UnsupportedError error => wire.NativeError(
      kind: wire.NativeErrorKind.unsupported,
      message: message,
      detail: error.detail,
      feature: _featureToWire(error.feature),
      exchange: error.exchange.id,
      retryable: false,
      rateLimited: false,
    ),
    AdapterError error => wire.NativeError(
      kind: wire.NativeErrorKind.adapter,
      message: message,
      detail: error.detail,
      retryable: false,
      rateLimited: false,
    ),
    AuthenticationError error => wire.NativeError(
      kind: wire.NativeErrorKind.auth,
      message: message,
      detail: error.detail,
      retryable: false,
      rateLimited: false,
    ),
    ExchangeError error => wire.NativeError(
      kind: wire.NativeErrorKind.exchange,
      message: message,
      detail: error.message,
      exchange: error.exchange.id,
      code: error.code,
      status: error.status,
      exchangeKind: _enumByName(wire.WireExchangeErrorKind.values, error.kind),
      retryable: error.isRetryable,
      rateLimited: error.isRateLimited,
    ),
    TransportError error => wire.NativeError(
      kind: wire.NativeErrorKind.transport,
      message: message,
      detail: error.detail,
      retryable: true,
      rateLimited: false,
    ),
    DecodeError error => wire.NativeError(
      kind: wire.NativeErrorKind.decode,
      message: message,
      detail: error.detail,
      retryable: false,
      rateLimited: false,
    ),
    _ => wire.NativeError(
      kind: wire.NativeErrorKind.adapter,
      message: message,
      detail: message,
      retryable: false,
      rateLimited: false,
    ),
  };
}

UpbitMarketEvent _upbitMarketEventFromWire(wire.WireUpbitMarketEvent value) =>
    UpbitMarketEvent(
      market: _marketFromWire(value.market),
      warning: value.warning,
      cautions: value.cautions,
    );

BithumbMarketWarning _bithumbMarketWarningFromWire(
  wire.WireBithumbMarketWarning value,
) => BithumbMarketWarning(
  market: _marketFromWire(value.market),
  warning: value.warning,
);

BithumbMarketAlert _bithumbMarketAlertFromWire(
  wire.WireBithumbMarketAlert value,
) => BithumbMarketAlert(
  market: _marketFromWire(value.market),
  kind: value.kind,
  step: _enumByName(BithumbAlertStep.values, value.step),
  endsAt: _timestampFromWire(value.endsAtNs)!,
);

BinanceSymbolFilters _binanceSymbolFiltersFromWire(
  wire.WireBinanceSymbolFilters value,
) => BinanceSymbolFilters(
  symbol: value.symbol,
  tickSize: _decimalFromWire(value.tickSize),
  minPrice: _decimalFromWire(value.minPrice),
  maxPrice: _decimalFromWire(value.maxPrice),
  stepSize: _decimalFromWire(value.stepSize),
  minQuantity: _decimalFromWire(value.minQuantity),
  maxQuantity: _decimalFromWire(value.maxQuantity),
  minNotional: _decimalFromWire(value.minNotional),
);

BinanceSpotOrderDetail _binanceSpotOrderFromWire(
  wire.WireBinanceSpotOrderDetail value,
) => BinanceSpotOrderDetail(
  order: _orderFromWire(value.order),
  clientOrderId: value.clientOrderId,
  orderType: value.orderType,
  timeInForce: value.timeInForce,
  filledQuoteQuantity: Decimal.parse(value.filledQuoteQuantity),
  updatedAt: _timestampFromWire(value.updatedAtNs),
);

HyperliquidAssetContext _hyperliquidAssetContextFromWire(
  wire.WireHyperliquidAssetContext value,
) => HyperliquidAssetContext(
  midPrice: _decimalFromWire(value.midPrice),
  markPrice: _decimalFromWire(value.markPrice),
  oraclePrice: _decimalFromWire(value.oraclePrice),
  fundingRate: _decimalFromWire(value.fundingRate),
  openInterest: _decimalFromWire(value.openInterest),
  sizeDecimals: value.sizeDecimals,
  priceDecimals: value.priceDecimals,
);

HyperliquidLedgerKind _hyperliquidLedgerKindFromWire(
  wire.WireHyperliquidLedgerEntry value,
) => value.kind == wire.WireHyperliquidLedgerKind.other
    ? HyperliquidLedgerKind.other(value.providerKind ?? 'other')
    : switch (value.kind) {
        wire.WireHyperliquidLedgerKind.deposit => HyperliquidLedgerKind.deposit,
        wire.WireHyperliquidLedgerKind.withdraw =>
          HyperliquidLedgerKind.withdraw,
        wire.WireHyperliquidLedgerKind.internalTransfer =>
          HyperliquidLedgerKind.internalTransfer,
        wire.WireHyperliquidLedgerKind.subAccountTransfer =>
          HyperliquidLedgerKind.subAccountTransfer,
        wire.WireHyperliquidLedgerKind.spotTransfer =>
          HyperliquidLedgerKind.spotTransfer,
        wire.WireHyperliquidLedgerKind.accountClassTransfer =>
          HyperliquidLedgerKind.accountClassTransfer,
        wire.WireHyperliquidLedgerKind.vaultDeposit =>
          HyperliquidLedgerKind.vaultDeposit,
        wire.WireHyperliquidLedgerKind.vaultWithdraw =>
          HyperliquidLedgerKind.vaultWithdraw,
        wire.WireHyperliquidLedgerKind.vaultDistribution =>
          HyperliquidLedgerKind.vaultDistribution,
        wire.WireHyperliquidLedgerKind.liquidation =>
          HyperliquidLedgerKind.liquidation,
        wire.WireHyperliquidLedgerKind.other => throw StateError('unreachable'),
      };

HyperliquidLedgerEntry _hyperliquidLedgerEntryFromWire(
  wire.WireHyperliquidLedgerEntry value,
) => HyperliquidLedgerEntry(
  kind: _hyperliquidLedgerKindFromWire(value),
  time: _timestampFromWire(value.timeNs)!,
  hash: value.hash,
  asset: value.asset,
  amount: _decimalFromWire(value.amount),
  fee: _decimalFromWire(value.fee),
  counterparty: value.counterparty,
);

Page<HyperliquidLedgerEntry> _hyperliquidLedgerPageFromWire(
  wire.WireHyperliquidLedgerPage value,
) => Page(
  items: value.items.map(_hyperliquidLedgerEntryFromWire),
  next: value.next == null ? null : Cursor(value.next!),
);
