// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.

part of 'stream.dart';

/// A single-subscription stream that preserves Upbit-native events.
final class UpbitMarketStream extends _CloseableStream<UpbitMarketStreamEvent> {
  UpbitMarketStream(super.source, {super.onClose});
}

/// A single-subscription stream that preserves Upbit-native events.
final class UpbitAccountStream
    extends _CloseableStream<UpbitAccountStreamEvent> {
  UpbitAccountStream(super.source, {super.onClose});
}

/// A single-subscription stream that preserves Bithumb-native events.
final class BithumbMarketStream extends _CloseableStream<BithumbMarketEvent> {
  BithumbMarketStream(super.source, {super.onClose});
}

/// A single-subscription stream that preserves Bithumb-native events.
final class BithumbAccountStream extends _CloseableStream<BithumbAccountEvent> {
  BithumbAccountStream(super.source, {super.onClose});
}

/// A single-subscription stream that preserves Binance-native events.
final class BinanceMarketStream extends _CloseableStream<BinanceMarketEvent> {
  BinanceMarketStream(super.source, {super.onClose});
}

/// A single-subscription stream that preserves Binance-native events.
final class BinanceAccountStream
    extends _CloseableStream<BinanceAccountStreamEvent> {
  BinanceAccountStream(super.source, {super.onClose});
}
