// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.

part of 'adapters.dart';

extension UpbitAdapterGeneratedMethods on UpbitAdapter {
  Future<List<OrderBook>> orderBooks(List<Market> markets, [int? depth]) =>
      _nativeFuture(
        () => _handle.upbitOrderBooks(
          markets: markets.map(_marketToWire).toList(growable: false),
          depth: checkedUint32(depth, field: 'depth'),
        ),
      ).then(
        (values) => values.map(_orderBookFromWire).toList(growable: false),
      );

  Future<List<Ticker>> tickers(List<Market> markets) => _nativeFuture(
    () => _handle.upbitTickers(
      markets: markets.map(_marketToWire).toList(growable: false),
    ),
  ).then((values) => values.map(_tickerFromWire).toList(growable: false));

  Future<List<UpbitMarketEvent>> marketEvents() =>
      _nativeFuture(_handle.upbitMarketEvents).then(
        (values) =>
            values.map(_upbitMarketEventFromWire).toList(growable: false),
      );
}

extension BithumbAdapterGeneratedMethods on BithumbAdapter {
  Future<List<BithumbMarketWarning>> marketWarnings() =>
      _nativeFuture(_handle.bithumbMarketWarnings).then(
        (values) =>
            values.map(_bithumbMarketWarningFromWire).toList(growable: false),
      );

  Future<List<BithumbMarketAlert>> marketAlerts() =>
      _nativeFuture(_handle.bithumbMarketAlerts).then(
        (values) =>
            values.map(_bithumbMarketAlertFromWire).toList(growable: false),
      );
}

extension BinanceAdapterGeneratedMethods on BinanceAdapter {
  Future<BinanceSymbolFilters> spotSymbolFilters(Market market) =>
      _nativeFuture(
        () => _handle.binanceSpotSymbolFilters(market: _marketToWire(market)),
      ).then(_binanceSymbolFiltersFromWire);

  Future<BinanceSpotOrderDetail> spotOrder(Market market, String orderId) =>
      _nativeFuture(
        () => _handle.binanceSpotOrder(
          market: _marketToWire(market),
          orderId: orderId,
        ),
      ).then(_binanceSpotOrderFromWire);

  Future<BinanceListenKey> usdMCreateListenKey() => _nativeFuture(
    _handle.binanceUsdMCreateListenKey,
  ).then(BinanceListenKey._);

  Future<void> usdMKeepaliveListenKey() =>
      _nativeFuture(_handle.binanceUsdMKeepaliveListenKey);

  Future<void> usdMCloseListenKey() =>
      _nativeFuture(_handle.binanceUsdMCloseListenKey);
}

extension HyperliquidAdapterGeneratedMethods on HyperliquidAdapter {
  Future<Page<HyperliquidLedgerEntry>> nonFundingLedger({
    Timestamp? from,
    Timestamp? to,
    Cursor? cursor,
    int? limit,
  }) => _nativeFuture(
    () => _handle.hyperliquidNonFundingLedger(
      fromNs: from == null
          ? null
          : platformInt64FromBigInt(from.nanosecondsSinceEpoch),
      toNs: to == null
          ? null
          : platformInt64FromBigInt(to.nanosecondsSinceEpoch),
      cursor: cursor?.value,
      limit: checkedUint32(limit, field: 'limit'),
    ),
  ).then(_hyperliquidLedgerPageFromWire);

  Future<HyperliquidAssetContext> assetContext(Market market) => _nativeFuture(
    () => _handle.hyperliquidAssetContext(market: _marketToWire(market)),
  ).then(_hyperliquidAssetContextFromWire);
}
