use maxt_bindings_common::schema::{
    ApiType, Argument, Field, Operation, ProviderMethodKind, Schema, Type,
};

pub(crate) fn render(schema: &Schema) -> String {
    let mut output =
        String::from("// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.\n\n");
    output.push_str(&format!(
        "const exchanges = {};\n",
        list(&schema.exchanges, "")
    ));
    output.push_str(&format!(
        "const features = {};\n",
        list(&schema.features, "")
    ));
    output.push_str(&format!(
        "const errorVariants = {};\n",
        list(schema.errors, "")
    ));
    let operations = schema
        .adapter_operations
        .iter()
        .map(|value| value.language_name)
        .collect::<Vec<_>>();
    output.push_str(&format!(
        "const adapterOperations = {};\n",
        list(&operations, "")
    ));
    output.push_str(&format!(
        "const clientMembers = {};\n",
        list(schema.client_members, "")
    ));
    output.push_str("const providerMethods = <String, List<String>>{\n");
    for provider in schema.providers {
        let methods = provider
            .methods
            .iter()
            .map(|method| method.name)
            .collect::<Vec<_>>();
        output.push_str(&format!(
            "  '{}': {},\n",
            provider.exchange,
            list(&methods, "  ")
        ));
    }
    output.push_str("};\n");
    output
}

pub(crate) fn render_identifiers(schema: &Schema) -> String {
    let mut output =
        String::from("// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.\n\n");

    for (index, identifier) in schema.identifiers.iter().enumerate() {
        if identifier.open {
            render_open_identifier(&mut output, identifier);
        } else {
            render_closed_identifier(&mut output, identifier);
        }
        if index + 1 < schema.identifiers.len() {
            output.push('\n');
        }
    }

    output
}

pub(crate) fn render_wire_converters(schema: &Schema) -> String {
    let mut output = String::from(
        "// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.\n\n\
         part of 'adapters.dart';\n\n",
    );
    for name in [
        "Exchange",
        "Feature",
        "MarketKind",
        "MarketStatus",
        "Side",
        "Interval",
        "OrderStatus",
        "OrderType",
        "TimeInForce",
        "MarginMode",
    ] {
        let lower = lower_camel(name);
        output.push_str(&dart_arrow_function(
            &format!("wire.Wire{name} _{lower}ToWire({name} value)"),
            &format!("_enumByName(wire.Wire{name}.values, value)"),
        ));
        output.push_str(&dart_arrow_function(
            &format!("{name} _{lower}FromWire(wire.Wire{name} value)"),
            &format!("_enumByName({name}.values, value)"),
        ));
        output.push('\n');
    }
    for name in [
        "Market",
        "MarketInfo",
        "Trade",
        "Level",
        "OrderBook",
        "Ticker",
        "Candle",
        "Balance",
        "Order",
        "Position",
        "MarginSummary",
        "FundingRate",
        "FundingPayment",
    ] {
        let record = schema
            .records
            .iter()
            .find(|record| record.name == format!("{name}Wire"))
            .unwrap_or_else(|| panic!("missing record {name}Wire"));
        output.push_str(&render_dart_record_converter(name, &record.fields));
    }
    for operation in schema.adapter_operations {
        if let ApiType::Page(name) = operation.result {
            output.push_str(&render_dart_page_converter(name));
        }
    }
    output.push_str(&render_dart_errors(schema));
    output.push_str(&render_dart_provider_converters(schema));
    output.truncate(output.trim_end().len());
    output.push('\n');
    output
}

pub(crate) fn render_adapter_api(schema: &Schema) -> String {
    let mut output = String::from(
        "// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.\n\n\
         import 'errors.dart';\n\
         import 'models.dart';\n\
         import 'stream.dart';\n\n\
         abstract interface class GeneratedAdapterContract {\n\
         \x20 Exchange get exchange;\n\n\
         \x20 Set<Feature> get features;\n\n\
         \x20 bool supports(Feature feature);\n",
    );
    for operation in schema.adapter_operations {
        output.push('\n');
        render_method_declaration(&mut output, operation);
    }
    output.push_str("}\n\nabstract base class GeneratedAdapterDefaults\n    implements GeneratedAdapterContract {\n  Future<T> _unsupported<T>(Feature feature) => Future<T>.error(\n    UnsupportedError(\n      feature: feature,\n      exchange: exchange,\n      detail: '${exchange.id} has no endpoint for ${feature.wireName}',\n    ),\n  );\n\n  @override\n  bool supports(Feature feature) => features.contains(feature);\n");
    for operation in schema
        .adapter_operations
        .iter()
        .filter(|operation| operation.language_name != "subscribe")
    {
        output.push('\n');
        render_unsupported_method(&mut output, schema, operation);
    }
    output.push_str("}\n");
    output
}

pub(crate) fn render_client_api(schema: &Schema) -> String {
    let mut output = String::from(
        "// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.\n\n\
         import 'adapter.dart';\n\
         import 'adapters.dart'\n\
         \x20   show NativeClientDelegate, checkedUint32, validateStreamConfigIntegers;\n\
         import 'models.dart';\n\
         import 'runtime.dart';\n\
         import 'stream.dart';\n\n\
         abstract base class GeneratedClient<A extends Adapter> {\n\
         \x20 GeneratedClient(this.adapter)\n\
         \x20   : _native = NativeClientDelegate.fromAdapter(adapter);\n\n\
         \x20 final A adapter;\n\
         \x20 final NativeClientDelegate _native;\n\n\
         \x20 Exchange get exchange => _native.exchange;\n\n\
         \x20 bool supports(Feature feature) => _native.supports(feature);\n",
    );
    for operation in schema.adapter_operations {
        for method in operation.client_methods {
            output.push('\n');
            output.push_str(&render_client_method(operation, method));
        }
    }
    output.push_str("\n  static List<Position> _openPositions(List<Position> positions) =>\n      positions.where((position) => !position.isFlat).toList(growable: false);\n}\n");
    output
}

pub(crate) fn render_native_client_api(schema: &Schema) -> String {
    let mut output = String::from(
        "// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.\n\nuse super::*;\n\nimpl NativeClient {\n",
    );
    for (index, operation) in schema
        .adapter_operations
        .iter()
        .filter(|operation| {
            !matches!(
                operation.result,
                ApiType::MarketStream | ApiType::AccountStream
            )
        })
        .enumerate()
    {
        if index > 0 {
            output.push('\n');
        }
        output.push_str(&render_native_method(operation));
    }
    output.push_str("}\n");
    output
}

pub(crate) fn render_rust_adapter_dispatch(schema: &Schema) -> String {
    let mut output = String::from(
        "// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.\n\nuse super::*;\n\n#[rustfmt::skip]\npub(super) fn dispatch(call: CommonAdapterCall) -> Option<(AdapterCall, ExpectedReply)> {\n    match call {\n",
    );
    for operation in schema.adapter_operations.iter().filter(|operation| {
        !matches!(
            operation.result,
            ApiType::MarketStream | ApiType::AccountStream
        )
    }) {
        let variant = pascal_case(operation.rust_name);
        let fields = operation
            .arguments
            .iter()
            .map(|argument| snake_case(argument.name))
            .collect::<Vec<_>>();
        let pattern = if fields.is_empty() {
            format!("CommonAdapterCall::{variant}")
        } else {
            format!("CommonAdapterCall::{variant} {{ {} }}", fields.join(", "))
        };
        let mapped_fields = operation
            .arguments
            .iter()
            .map(|argument| {
                let name = snake_case(argument.name);
                let value = match argument.ty {
                    ApiType::Named(_) => format!("{name}.into()"),
                    ApiType::OptionalNamed(_) => format!("{name}.map(Into::into)"),
                    _ => name.clone(),
                };
                format!("{name}: {value}")
            })
            .collect::<Vec<_>>();
        let expected = if operation.result == ApiType::Unit {
            "Unit".to_owned()
        } else {
            variant.clone()
        };
        if mapped_fields.is_empty() {
            let arm = format!(
                "        {pattern} => Some((AdapterCall::{variant}, ExpectedReply::{expected})),\n"
            );
            if arm.trim_end().chars().count() <= 100 {
                output.push_str(&arm);
            } else {
                output.push_str(&format!(
                    "        {pattern} => {{\n            Some((AdapterCall::{variant}, ExpectedReply::{expected}))\n        }}\n"
                ));
            }
        } else {
            output.push_str(&format!(
                "        {pattern} => Some((\n            AdapterCall::{variant} {{\n"
            ));
            let inline_fields = mapped_fields
                .iter()
                .map(|field| {
                    let (name, value) = field.split_once(": ").expect("generated field");
                    if name == value {
                        name.to_owned()
                    } else {
                        field.clone()
                    }
                })
                .collect::<Vec<_>>()
                .join(", ");
            let inline = format!("            AdapterCall::{variant} {{ {inline_fields} }},\n");
            if inline.trim_end().chars().count() <= 100 {
                output.truncate(
                    output.len() - format!("            AdapterCall::{variant} {{\n").len(),
                );
                output.push_str(&inline);
            } else {
                for field in mapped_fields {
                    let (name, value) = field.split_once(": ").expect("generated field");
                    if name == value {
                        output.push_str(&format!("                {name},\n"));
                    } else {
                        output.push_str(&format!("                {field},\n"));
                    }
                }
                output.push_str("            },\n");
            }
            output.push_str(&format!(
                "            ExpectedReply::{expected},\n        )),\n"
            ));
        }
    }
    output.push_str("        _ => None,\n    }\n}\n");
    output
}

pub(crate) fn render_provider_guard(schema: &Schema) -> String {
    let mut output = String::from(
        "// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.\n// ignore_for_file: unused_element\n\npart of 'adapters.dart';\n\nT _generatedProviderValue<T>() => throw StateError('compile-time API guard');\n\nvoid _generatedProviderGuard({\n",
    );
    for provider in schema.providers {
        output.push_str(&format!(
            "  required {} {},\n",
            provider.adapter, provider.exchange
        ));
    }
    output.push_str("}) {\n");
    for provider in schema.providers {
        for constructor in provider.constructors {
            let name = if constructor.name == "constructor" {
                provider.adapter.to_owned()
            } else {
                format!("{}.{}", provider.adapter, constructor.name)
            };
            let arguments = constructor
                .arguments
                .iter()
                .filter(|argument| argument.default.is_none())
                .map(|argument| format!("_generatedProviderValue<{}>()", dart_type(argument.ty)))
                .collect::<Vec<_>>()
                .join(", ");
            output.push_str(&format!("  {name}({arguments});\n"));
        }
        for method in provider.methods {
            if method.kind == ProviderMethodKind::Property {
                output.push_str(&format!("  {}.{};\n", provider.exchange, method.name));
                continue;
            }
            let arguments = method
                .arguments
                .iter()
                .filter(|argument| argument.default.is_none())
                .map(|argument| format!("_generatedProviderValue<{}>()", dart_type(argument.ty)))
                .collect::<Vec<_>>()
                .join(", ");
            let call = format!("  {}.{}({arguments});", provider.exchange, method.name);
            if call.chars().count() <= 80 || method.arguments.len() < 2 {
                output.push_str(&format!("{call}\n"));
            } else {
                output.push_str(&format!("  {}.{}(\n", provider.exchange, method.name));
                for argument in method
                    .arguments
                    .iter()
                    .filter(|argument| argument.default.is_none())
                {
                    output.push_str(&format!(
                        "    _generatedProviderValue<{}>(),\n",
                        dart_type(argument.ty)
                    ));
                }
                output.push_str("  );\n");
            }
        }
    }
    output.push_str("}\n");
    output
}

pub(crate) fn render_provider_methods(schema: &Schema) -> String {
    let mut output = String::from(
        "// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.\n\npart of 'adapters.dart';\n",
    );
    for provider in schema.providers {
        output.push_str(&format!(
            "\nextension {}GeneratedMethods on {} {{\n",
            provider.adapter, provider.adapter
        ));
        for (index, method) in provider
            .methods
            .iter()
            .filter(|method| method.kind == ProviderMethodKind::Async)
            .enumerate()
        {
            if index > 0 {
                output.push('\n');
            }
            output.push_str(provider_method_source(provider.exchange, method.rust_name));
        }
        output.push_str("}\n");
    }
    output
}

pub(crate) fn render_delegate_methods(schema: &Schema) -> String {
    let mut output = String::from(
        "// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.\n\npart of 'adapters.dart';\n\nabstract base class GeneratedNativeDelegate extends AdapterBase {\n  Future<Adapter> get delegateAdapter;\n",
    );
    for operation in schema.adapter_operations.iter().filter(|operation| {
        !matches!(
            operation.result,
            ApiType::MarketStream | ApiType::AccountStream
        )
    }) {
        let arguments = operation
            .arguments
            .iter()
            .map(|argument| argument.name)
            .collect::<Vec<_>>()
            .join(", ");
        let signature = format!(
            "  Future<{}> {}({}) async =>",
            dart_type(operation.result),
            operation.language_name,
            dart_arguments(operation.arguments),
        );
        let call = format!(
            "(await delegateAdapter).{}({arguments});",
            operation.language_name
        );
        output.push_str("\n  @override\n");
        if signature.chars().count() + call.chars().count() < 80 {
            output.push_str(&format!("{signature} {call}\n"));
        } else {
            output.push_str(&format!("{signature}\n      {call}\n"));
        }
    }
    output.push_str("}\n");
    output
}

pub(crate) fn render_wire_shape_guard(schema: &Schema) -> String {
    const PROJECTED_RECORDS: &[&str] = &[
        "StreamConfigWire",
        "SubscriptionWire",
        "PageWire",
        "UpbitMarketEventWire",
        "BithumbMarketAlertWire",
        "BinanceListenKeyWire",
        "HyperliquidLedgerEntryWire",
        "UpbitOptionsWire",
        "BithumbOptionsWire",
        "BinanceOptionsWire",
        "HyperliquidOptionsWire",
        "NativeStreamReferenceWire",
    ];
    const PROJECTED_UNIONS: &[&str] = &[
        "SizeWire",
        "FeedWire",
        "MarketEventWire",
        "AccountEventWire",
        "MarketStreamItemWire",
        "AccountStreamItemWire",
        "ErrorWire",
        "AdapterCallWire",
        "AdapterReplyWire",
    ];
    const WIRE_IDENTIFIERS: &[(&str, &str)] = &[
        ("Exchange", "WireExchange"),
        ("Feature", "WireFeature"),
        ("MarketKind", "WireMarketKind"),
        ("MarketStatus", "WireMarketStatus"),
        ("Side", "WireSide"),
        ("Interval", "WireInterval"),
        ("MarginMode", "WireMarginMode"),
        ("OrderStatus", "WireOrderStatus"),
        ("OrderType", "WireOrderType"),
        ("TimeInForce", "WireTimeInForce"),
        ("SizeKind", "WireSizeKind"),
        ("BithumbAlertStep", "WireBithumbAlertStep"),
        ("ExchangeErrorKind", "WireExchangeErrorKind"),
    ];
    let mut output = String::from(
        "// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.\n#![allow(dead_code)]\n\nuse super::*;\n",
    );
    for record in &schema.records {
        if PROJECTED_RECORDS.contains(&record.name) {
            continue;
        }
        assert!(
            record.type_parameters.is_empty(),
            "unclassified generic Dart wire record: {}",
            record.name
        );
        let wire_name = format!(
            "Wire{}",
            record
                .name
                .strip_suffix("Wire")
                .unwrap_or_else(|| panic!("Dart wire record needs Wire suffix: {}", record.name))
        );
        output.push_str(&format!(
            "\nfn _guard_{}(value: {wire_name}) {{\n    let {wire_name} {{\n",
            snake_case(record.name)
        ));
        for field in &record.fields {
            let name = rust_wire_field(field.name, &field.ty);
            output.push_str(&format!("        {name}: _,\n"));
        }
        output.push_str("    } = value;\n}\n");
    }
    for union in &schema.unions {
        assert!(
            PROJECTED_UNIONS.contains(&union.name),
            "unclassified Dart wire union: {}",
            union.name
        );
    }
    let error_union = schema
        .unions
        .iter()
        .find(|union| union.name == "ErrorWire")
        .expect("ErrorWire schema");
    let mut error_fields = error_union
        .variants
        .iter()
        .flat_map(|variant| variant.fields.iter().map(|field| field.name))
        .collect::<std::collections::BTreeSet<_>>();
    error_fields.extend(["kind", "retryable", "rate_limited"]);
    output.push_str("\nfn _guard_native_error(value: NativeError) {\n    let NativeError {\n");
    for field in error_fields {
        output.push_str(&format!("        {field}: _,\n"));
    }
    output.push_str("    } = value;\n}\n\nfn _guard_native_error_kind(value: NativeErrorKind) {\n    match value {\n");
    for error in schema.errors {
        output.push_str(&format!(
            "        NativeErrorKind::{} => {{}}\n",
            pascal_case(error)
        ));
    }
    output.push_str("    }\n}\n");
    for (identifier_name, wire_name) in WIRE_IDENTIFIERS {
        let identifier = schema
            .identifier(identifier_name)
            .unwrap_or_else(|| panic!("missing identifier: {identifier_name}"));
        output.push_str(&format!(
            "\nfn _guard_{}(value: {wire_name}) {{\n    match value {{\n",
            snake_case(identifier_name)
        ));
        for variant in identifier.variants {
            output.push_str(&format!(
                "        {wire_name}::{} => {{}}\n",
                variant.rust_name
            ));
        }
        output.push_str("    }\n}\n");
    }
    output
}

fn rust_wire_field(name: &str, ty: &Type) -> String {
    let timestamp = matches!(ty, Type::Timestamp)
        || matches!(ty, Type::Optional(inner) if matches!(inner.as_ref(), Type::Timestamp));
    if timestamp {
        format!("{name}_ns")
    } else {
        name.to_owned()
    }
}

fn provider_method_source(exchange: &str, method: &str) -> &'static str {
    match (exchange, method) {
        ("upbit", "order_books") => {
            "  Future<List<OrderBook>> orderBooks(List<Market> markets, [int? depth]) =>\n      _nativeFuture(\n        () => _handle.upbitOrderBooks(\n          markets: markets.map(_marketToWire).toList(growable: false),\n          depth: checkedUint32(depth, field: 'depth'),\n        ),\n      ).then(\n        (values) => values.map(_orderBookFromWire).toList(growable: false),\n      );\n"
        }
        ("upbit", "tickers") => {
            "  Future<List<Ticker>> tickers(List<Market> markets) => _nativeFuture(\n    () => _handle.upbitTickers(\n      markets: markets.map(_marketToWire).toList(growable: false),\n    ),\n  ).then((values) => values.map(_tickerFromWire).toList(growable: false));\n"
        }
        ("upbit", "market_events") => {
            "  Future<List<UpbitMarketEvent>> marketEvents() =>\n      _nativeFuture(_handle.upbitMarketEvents).then(\n        (values) =>\n            values.map(_upbitMarketEventFromWire).toList(growable: false),\n      );\n"
        }
        ("bithumb", "market_warnings") => {
            "  Future<List<BithumbMarketWarning>> marketWarnings() =>\n      _nativeFuture(_handle.bithumbMarketWarnings).then(\n        (values) =>\n            values.map(_bithumbMarketWarningFromWire).toList(growable: false),\n      );\n"
        }
        ("bithumb", "market_alerts") => {
            "  Future<List<BithumbMarketAlert>> marketAlerts() =>\n      _nativeFuture(_handle.bithumbMarketAlerts).then(\n        (values) =>\n            values.map(_bithumbMarketAlertFromWire).toList(growable: false),\n      );\n"
        }
        ("binance", "spot_symbol_filters") => {
            "  Future<BinanceSymbolFilters> spotSymbolFilters(Market market) =>\n      _nativeFuture(\n        () => _handle.binanceSpotSymbolFilters(market: _marketToWire(market)),\n      ).then(_binanceSymbolFiltersFromWire);\n"
        }
        ("binance", "spot_order") => {
            "  Future<BinanceSpotOrderDetail> spotOrder(Market market, String orderId) =>\n      _nativeFuture(\n        () => _handle.binanceSpotOrder(\n          market: _marketToWire(market),\n          orderId: orderId,\n        ),\n      ).then(_binanceSpotOrderFromWire);\n"
        }
        ("binance", "usd_m_create_listen_key") => {
            "  Future<BinanceListenKey> usdMCreateListenKey() => _nativeFuture(\n    _handle.binanceUsdMCreateListenKey,\n  ).then(BinanceListenKey._);\n"
        }
        ("binance", "usd_m_keepalive_listen_key") => {
            "  Future<void> usdMKeepaliveListenKey(BinanceListenKey key) => _nativeFuture(\n    () => _handle.binanceUsdMKeepaliveListenKey(key: key._handle),\n  );\n"
        }
        ("binance", "usd_m_close_listen_key") => {
            "  Future<void> usdMCloseListenKey(BinanceListenKey key) =>\n      _nativeFuture(() => _handle.binanceUsdMCloseListenKey(key: key._handle));\n"
        }
        ("hyperliquid", "non_funding_ledger") => {
            "  Future<Page<HyperliquidLedgerEntry>> nonFundingLedger({\n    Timestamp? from,\n    Timestamp? to,\n    Cursor? cursor,\n    int? limit,\n  }) => _nativeFuture(\n    () => _handle.hyperliquidNonFundingLedger(\n      fromNs: from == null\n          ? null\n          : platformInt64FromBigInt(from.nanosecondsSinceEpoch),\n      toNs: to == null\n          ? null\n          : platformInt64FromBigInt(to.nanosecondsSinceEpoch),\n      cursor: cursor?.value,\n      limit: checkedUint32(limit, field: 'limit'),\n    ),\n  ).then(_hyperliquidLedgerPageFromWire);\n"
        }
        ("hyperliquid", "asset_context") => {
            "  Future<HyperliquidAssetContext> assetContext(Market market) => _nativeFuture(\n    () => _handle.hyperliquidAssetContext(market: _marketToWire(market)),\n  ).then(_hyperliquidAssetContextFromWire);\n"
        }
        _ => panic!("unsupported Dart provider method: {exchange}.{method}"),
    }
}

fn render_native_method(operation: &Operation) -> String {
    let argument_lines = operation
        .arguments
        .iter()
        .map(|argument| {
            format!(
                "        {}: {},\n",
                snake_case(argument.name),
                rust_wire_type(argument.ty)
            )
        })
        .collect::<String>();
    let inline_arguments = operation
        .arguments
        .iter()
        .map(|argument| {
            format!(
                "{}: {}",
                snake_case(argument.name),
                rust_wire_type(argument.ty)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let inline = format!(
        "    pub async fn {}(&self{}{}) -> Result<{}, NativeError> {{\n",
        operation.rust_name,
        if inline_arguments.is_empty() {
            ""
        } else {
            ", "
        },
        inline_arguments,
        rust_wire_type(operation.result),
    );
    let mut output = if inline.trim_end().chars().count() <= 100 {
        inline
    } else {
        format!(
            "    pub async fn {}(\n        &self,\n{argument_lines}    ) -> Result<{}, NativeError> {{\n",
            operation.rust_name,
            rust_wire_type(operation.result),
        )
    };

    for argument in operation.arguments {
        let name = snake_case(argument.name);
        match argument.ty {
            ApiType::OptionalNamed("Market") => {
                output.push_str(&format!("        let {name} = {name}.map(Into::into);\n"));
            }
            ApiType::Named("OrderRequest" | "MarginRequest") => {
                output.push_str(&format!("        let {name} = {name}.try_into()?;\n"));
            }
            _ => {}
        }
    }

    if operation.rust_name == "positions" {
        output.push_str(
            "        let mut positions = self\n            .adapter\n            .positions(market.as_ref())\n            .await\n            .map_err(NativeError::from)?;\n        positions.retain(|position| !position.is_flat());\n        Ok(positions.into_iter().map(Into::into).collect())\n",
        );
    } else {
        let call_arguments = operation
            .arguments
            .iter()
            .map(native_call_argument)
            .collect::<Vec<_>>()
            .join(", ");
        if operation.result == ApiType::Unit {
            output.push_str(&format!(
                "        self.adapter.{}({call_arguments}).await",
                operation.rust_name
            ));
        } else {
            output.push_str(&format!(
                "        self.adapter\n            .{}({call_arguments})\n            .await",
                operation.rust_name
            ));
        }
        match operation.result {
            ApiType::List(_) | ApiType::PairList(_, _) => {
                output.push_str(
                    "\n            .map(|items| items.into_iter().map(Into::into).collect())",
                );
            }
            ApiType::Named(_) | ApiType::Page(_) | ApiType::Handle(_) => {
                output.push_str("\n            .map(Into::into)");
            }
            _ => {}
        }
        if operation.result == ApiType::Unit {
            output.push_str(".map_err(Into::into)\n");
        } else {
            output.push_str("\n            .map_err(Into::into)\n");
        }
    }
    output.push_str("    }\n");
    output
}

fn native_call_argument(argument: &Argument) -> String {
    let name = snake_case(argument.name);
    match argument.ty {
        ApiType::Named("Market") => format!("&{name}.into()"),
        ApiType::Named("MarketKind") => format!("{name}.into()"),
        ApiType::Named("OrderRequest" | "MarginRequest") => format!("&{name}"),
        ApiType::Named(_) => format!("&{name}.into()"),
        ApiType::OptionalNamed("Market") => format!("{name}.as_ref()"),
        ApiType::String => format!("&{name}"),
        _ => name,
    }
}

fn rust_wire_type(ty: ApiType) -> String {
    match ty {
        ApiType::String => "String".into(),
        ApiType::Boolean => "bool".into(),
        ApiType::Number => "u32".into(),
        ApiType::Named(name) => format!("Wire{name}"),
        ApiType::OptionalString => "Option<String>".into(),
        ApiType::OptionalNumber => "Option<u32>".into(),
        ApiType::OptionalNamed(name) => format!("Option<Wire{name}>"),
        ApiType::List(name) | ApiType::PairList(_, name) => format!("Vec<Wire{name}>"),
        ApiType::Page(name) => format!("Wire{name}Page"),
        ApiType::Handle(name) => format!("Wire{name}"),
        ApiType::HandleToken(name) => name.into(),
        ApiType::Unit => "()".into(),
        ApiType::MarketStream | ApiType::AccountStream => {
            unreachable!("stream façades remain handwritten")
        }
    }
}

fn snake_case(value: &str) -> String {
    value
        .chars()
        .enumerate()
        .fold(String::new(), |mut output, (index, character)| {
            if index > 0 && character.is_ascii_uppercase() {
                output.push('_');
            }
            output.push(character.to_ascii_lowercase());
            output
        })
}

fn render_dart_record_converter(name: &str, fields: &[Field]) -> String {
    let function = lower_camel(name);
    let from_fields = fields
        .iter()
        .map(|field| {
            let public = snake_to_lower_camel(field.name);
            let value = dart_from_wire_expression(field.name, &field.ty);
            if name == "Market" {
                format!("  {value},\n")
            } else {
                format!("  {public}: {value},\n")
            }
        })
        .collect::<String>();
    let to_fields = fields
        .iter()
        .map(|field| {
            let public = snake_to_lower_camel(field.name);
            let wire = dart_wire_field(field.name, &field.ty);
            let value = dart_to_wire_expression(&format!("value.{public}"), &field.ty);
            format!("  {wire}: {value},\n")
        })
        .collect::<String>();
    let from_signature = format!("{name} _{function}FromWire(wire.Wire{name} value)");
    let from_constructor = format!("{name}(");
    let (from_head, from_fields, from_tail) =
        dart_constructor_call(&from_signature, &from_constructor, &from_fields);
    let to_signature = format!("wire.Wire{name} _{function}ToWire({name} value)");
    let to_constructor = format!("wire.Wire{name}(");
    let (to_head, to_fields, to_tail) =
        dart_constructor_call(&to_signature, &to_constructor, &to_fields);
    format!("{from_head}{from_fields}{from_tail}{to_head}{to_fields}{to_tail}\n")
}

fn render_dart_page_converter(name: &str) -> String {
    let lower = lower_camel(name);
    let from_fields = format!(
        "  items: value.items.map(_{lower}FromWire),\n  next: value.next == null ? null : Cursor(value.next!),\n"
    );
    let from = dart_named_constructor_function(
        &format!("Page<{name}> _{lower}PageFromWire"),
        &format!("wire.Wire{name}Page"),
        "Page",
        &from_fields,
    );
    let to_fields = format!(
        "  items: value.items.map(_{lower}ToWire).toList(growable: false),\n  next: value.next?.value,\n"
    );
    let to = dart_named_constructor_function(
        &format!("wire.Wire{name}Page _{lower}PageToWire"),
        &format!("Page<{name}>"),
        &format!("wire.Wire{name}Page"),
        &to_fields,
    );
    format!("{from}{to}\n")
}

fn render_dart_errors(schema: &Schema) -> String {
    let error = schema
        .unions
        .iter()
        .find(|union| union.name == "ErrorWire")
        .expect("ErrorWire union must exist");
    let mut from =
        String::from("Object _nativeError(wire.NativeError value) => switch (value.kind) {\n");
    let mut to = String::from(
        "wire.NativeError _errorToWire(\n  Object value, {\n  Feature? feature,\n  Exchange? exchange,\n}) {\n  final message = value.toString();\n  return switch (value) {\n",
    );
    for variant in &error.variants {
        let (from_arm, to_arm) = match variant.name {
            "invalid_request" => (
                "  wire.NativeErrorKind.invalidRequest => InvalidRequestError(\n    field: value.field ?? 'request',\n    detail: value.detail ?? value.message,\n  ),\n",
                "    InvalidRequestError error => wire.NativeError(\n      kind: wire.NativeErrorKind.invalidRequest,\n      message: message,\n      detail: error.detail,\n      field: error.field,\n      retryable: false,\n      rateLimited: false,\n    ),\n",
            ),
            "unsupported" => (
                "  wire.NativeErrorKind.unsupported => _unsupportedErrorFromWire(value),\n",
                "    UnsupportedError error => wire.NativeError(\n      kind: wire.NativeErrorKind.unsupported,\n      message: message,\n      detail: error.detail,\n      feature: _featureToWire(error.feature),\n      exchange: error.exchange.id,\n      retryable: false,\n      rateLimited: false,\n    ),\n",
            ),
            "adapter" => (
                "  wire.NativeErrorKind.adapter => AdapterError(value.detail ?? value.message),\n",
                "    AdapterError error => wire.NativeError(\n      kind: wire.NativeErrorKind.adapter,\n      message: message,\n      detail: error.detail,\n      retryable: false,\n      rateLimited: false,\n    ),\n",
            ),
            "auth" => (
                "  wire.NativeErrorKind.auth => AuthenticationError(\n    value.detail ?? value.message,\n  ),\n",
                "    AuthenticationError error => wire.NativeError(\n      kind: wire.NativeErrorKind.auth,\n      message: message,\n      detail: error.detail,\n      retryable: false,\n      rateLimited: false,\n    ),\n",
            ),
            "exchange" => (
                "  wire.NativeErrorKind.exchange => _exchangeErrorFromWire(value),\n",
                "    ExchangeError error => wire.NativeError(\n      kind: wire.NativeErrorKind.exchange,\n      message: message,\n      detail: error.message,\n      exchange: error.exchange.id,\n      code: error.code,\n      status: error.status,\n      exchangeKind: _enumByName(wire.WireExchangeErrorKind.values, error.kind),\n      retryable: error.isRetryable,\n      rateLimited: error.isRateLimited,\n    ),\n",
            ),
            "transport" => (
                "  wire.NativeErrorKind.transport => TransportError(\n    value.detail ?? value.message,\n  ),\n",
                "    TransportError error => wire.NativeError(\n      kind: wire.NativeErrorKind.transport,\n      message: message,\n      detail: error.detail,\n      retryable: true,\n      rateLimited: false,\n    ),\n",
            ),
            "decode" => (
                "  wire.NativeErrorKind.decode => DecodeError(value.detail ?? value.message),\n",
                "    DecodeError error => wire.NativeError(\n      kind: wire.NativeErrorKind.decode,\n      message: message,\n      detail: error.detail,\n      retryable: false,\n      rateLimited: false,\n    ),\n",
            ),
            other => panic!("unsupported Dart ErrorWire variant: {other}"),
        };
        from.push_str(from_arm);
        to.push_str(to_arm);
    }
    from.push_str("};\n");
    to.push_str(
        "    _ => wire.NativeError(\n      kind: wire.NativeErrorKind.adapter,\n      message: message,\n      detail: message,\n      retryable: false,\n      rateLimited: false,\n    ),\n  };\n}\n",
    );
    format!("{from}{to}\n")
}

fn render_dart_provider_converters(schema: &Schema) -> String {
    for (exchange, method) in [
        ("upbit", "marketEvents"),
        ("bithumb", "marketWarnings"),
        ("bithumb", "marketAlerts"),
        ("binance", "spotSymbolFilters"),
        ("binance", "spotOrder"),
        ("hyperliquid", "nonFundingLedger"),
        ("hyperliquid", "assetContext"),
    ] {
        let provider = schema
            .providers
            .iter()
            .find(|provider| provider.exchange == exchange)
            .unwrap_or_else(|| panic!("missing provider {exchange}"));
        assert!(
            provider.methods.iter().any(|value| value.name == method),
            "missing provider method {exchange}.{method}"
        );
    }
    let mut output = String::from(
        "UpbitMarketEvent _upbitMarketEventFromWire(wire.WireUpbitMarketEvent value) =>\n    UpbitMarketEvent(\n      market: _marketFromWire(value.market),\n      warning: value.warning,\n      cautions: value.cautions,\n    );\n\n\
         BithumbMarketWarning _bithumbMarketWarningFromWire(\n  wire.WireBithumbMarketWarning value,\n) => BithumbMarketWarning(\n  market: _marketFromWire(value.market),\n  warning: value.warning,\n);\n\n\
         BithumbMarketAlert _bithumbMarketAlertFromWire(\n  wire.WireBithumbMarketAlert value,\n) => BithumbMarketAlert(\n  market: _marketFromWire(value.market),\n  kind: value.kind,\n  step: _enumByName(BithumbAlertStep.values, value.step),\n  endsAt: _timestampFromWire(value.endsAtNs)!,\n);\n\n",
    );
    for name in [
        "BinanceSymbolFilters",
        "BinanceSpotOrderDetail",
        "HyperliquidAssetContext",
    ] {
        let record = schema
            .records
            .iter()
            .find(|record| record.name == format!("{name}Wire"))
            .unwrap_or_else(|| panic!("missing record {name}Wire"));
        output.push_str(&render_dart_record_from_wire(name, &record.fields));
    }
    let identifier = schema
        .identifier("HyperliquidLedgerKind")
        .expect("HyperliquidLedgerKind identifier must exist");
    assert!(identifier.open, "HyperliquidLedgerKind must stay open");
    output.push_str(
        "HyperliquidLedgerKind _hyperliquidLedgerKindFromWire(\n  wire.WireHyperliquidLedgerEntry value,\n) => value.kind == wire.WireHyperliquidLedgerKind.other\n    ? HyperliquidLedgerKind.other(value.providerKind ?? 'other')\n    : switch (value.kind) {\n",
    );
    for variant in identifier.variants {
        let dart = dart_name(variant.rust_name);
        let source = format!("wire.WireHyperliquidLedgerKind.{dart}");
        let target = format!("HyperliquidLedgerKind.{dart}");
        if source.len() + target.len() + 12 <= 80 {
            output.push_str(&format!("        {source} => {target},\n"));
        } else {
            output.push_str(&format!("        {source} =>\n          {target},\n"));
        }
    }
    output.push_str(
        "        wire.WireHyperliquidLedgerKind.other => throw StateError('unreachable'),\n      };\n\n\
         HyperliquidLedgerEntry _hyperliquidLedgerEntryFromWire(\n  wire.WireHyperliquidLedgerEntry value,\n) => HyperliquidLedgerEntry(\n  kind: _hyperliquidLedgerKindFromWire(value),\n  time: _timestampFromWire(value.timeNs)!,\n  hash: value.hash,\n  asset: value.asset,\n  amount: _decimalFromWire(value.amount),\n  fee: _decimalFromWire(value.fee),\n  counterparty: value.counterparty,\n);\n\n\
         Page<HyperliquidLedgerEntry> _hyperliquidLedgerPageFromWire(\n  wire.WireHyperliquidLedgerPage value,\n) => Page(\n  items: value.items.map(_hyperliquidLedgerEntryFromWire),\n  next: value.next == null ? null : Cursor(value.next!),\n);\n",
    );
    output
}

fn render_dart_record_from_wire(name: &str, fields: &[Field]) -> String {
    let function = match name {
        "BinanceSpotOrderDetail" => "binanceSpotOrder".to_owned(),
        _ => lower_camel(name),
    };
    let fields = fields
        .iter()
        .map(|field| {
            let public = snake_to_lower_camel(field.name);
            let value = dart_from_wire_expression(field.name, &field.ty);
            format!("  {public}: {value},\n")
        })
        .collect::<String>();
    dart_named_constructor_function(
        &format!("{name} _{function}FromWire"),
        &format!("wire.Wire{name}"),
        name,
        &fields,
    ) + "\n"
}

fn dart_named_constructor_function(
    declaration: &str,
    parameter_type: &str,
    constructor: &str,
    fields: &str,
) -> String {
    let signature = format!("{declaration}({parameter_type} value)");
    if signature.len() > 80 {
        return format!(
            "{declaration}(\n  {parameter_type} value,\n) => {constructor}(\n{fields});\n"
        );
    }
    if signature.len() + constructor.len() + 5 > 80 {
        let fields = fields
            .lines()
            .map(|line| format!("    {line}\n"))
            .collect::<String>();
        return format!("{signature} =>\n    {constructor}(\n{fields}    );\n");
    }
    format!("{signature} => {constructor}(\n{fields});\n")
}

fn dart_constructor_call(
    signature: &str,
    constructor: &str,
    fields: &str,
) -> (String, String, String) {
    if signature.len() + constructor.len() + 4 <= 80 {
        (
            format!("{signature} => {constructor}\n"),
            fields.to_owned(),
            ");\n".to_owned(),
        )
    } else {
        (
            format!("{signature} =>\n    {constructor}\n"),
            fields.lines().map(|line| format!("    {line}\n")).collect(),
            "    );\n".to_owned(),
        )
    }
}

fn dart_from_wire_expression(name: &str, ty: &Type) -> String {
    let field = format!("value.{}", dart_wire_field(name, ty));
    match ty {
        Type::String | Type::Boolean | Type::Number => field,
        Type::UnsignedInteger => format!("{field}.toInt()"),
        Type::Decimal => format!("Decimal.parse({field})"),
        Type::Timestamp => format!("_timestampFromWire({field})!"),
        Type::Identifier(identifier) => {
            format!("_{}FromWire({field})", lower_camel(identifier))
        }
        Type::Named(named) => format!(
            "_{}FromWire({field})",
            lower_camel(named.trim_end_matches("Wire"))
        ),
        Type::Optional(inner) => match inner.as_ref() {
            Type::String | Type::Boolean | Type::Number => field,
            Type::UnsignedInteger => format!("{field}?.toInt()"),
            Type::Decimal => format!("_decimalFromWire({field})"),
            Type::Timestamp => format!("_timestampFromWire({field})"),
            Type::Identifier(identifier) => dart_optional_expression(
                &field,
                &format!("_{}FromWire({field}!)", lower_camel(identifier)),
            ),
            Type::Named(named) => dart_optional_expression(
                &field,
                &format!(
                    "_{}FromWire({field}!)",
                    lower_camel(named.trim_end_matches("Wire"))
                ),
            ),
            other => panic!("unsupported optional Dart wire field: {other:?}"),
        },
        Type::List(inner) => match inner.as_ref() {
            Type::String | Type::Boolean | Type::Number => field,
            Type::Named(named) => format!(
                "{field}.map(_{}FromWire)",
                lower_camel(named.trim_end_matches("Wire"))
            ),
            other => panic!("unsupported Dart wire list field: {other:?}"),
        },
        Type::Tuple(_) => panic!("tuple record fields are not used by Dart DTOs"),
    }
}

fn dart_to_wire_expression(value: &str, ty: &Type) -> String {
    match ty {
        Type::String | Type::Boolean | Type::Number => value.to_owned(),
        Type::UnsignedInteger => format!("BigInt.from({value})"),
        Type::Decimal => format!("{value}.toString()"),
        Type::Timestamp => format!("_timestampToWire({value})"),
        Type::Identifier(identifier) => {
            format!("_{}ToWire({value})", lower_camel(identifier))
        }
        Type::Named(named) => format!(
            "_{}ToWire({value})",
            lower_camel(named.trim_end_matches("Wire"))
        ),
        Type::Optional(inner) => match inner.as_ref() {
            Type::String | Type::Boolean | Type::Number => value.to_owned(),
            Type::UnsignedInteger => format!("{value} == null ? null : BigInt.from({value}!)"),
            Type::Decimal => format!("{value}?.toString()"),
            Type::Timestamp => format!("_optionalTimestampToWire({value})"),
            Type::Identifier(identifier) => dart_optional_expression(
                value,
                &format!("_{}ToWire({value}!)", lower_camel(identifier)),
            ),
            Type::Named(named) => dart_optional_expression(
                value,
                &format!(
                    "_{}ToWire({value}!)",
                    lower_camel(named.trim_end_matches("Wire"))
                ),
            ),
            other => panic!("unsupported optional Dart model field: {other:?}"),
        },
        Type::List(inner) => match inner.as_ref() {
            Type::String | Type::Boolean | Type::Number => {
                format!("{value}.toList(growable: false)")
            }
            Type::Named(named) => format!(
                "{value}.map(_{}ToWire).toList(growable: false)",
                lower_camel(named.trim_end_matches("Wire"))
            ),
            other => panic!("unsupported Dart model list field: {other:?}"),
        },
        Type::Tuple(_) => panic!("tuple record fields are not used by Dart DTOs"),
    }
}

fn dart_wire_field(name: &str, ty: &Type) -> String {
    let mut name = snake_to_lower_camel(name);
    if matches!(ty, Type::Timestamp)
        || matches!(ty, Type::Optional(inner) if matches!(inner.as_ref(), Type::Timestamp))
    {
        name.push_str("Ns");
    }
    name
}

fn dart_arrow_function(signature: &str, expression: &str) -> String {
    if signature.len() + expression.len() + 5 <= 80 {
        format!("{signature} => {expression};\n")
    } else {
        format!("{signature} =>\n    {expression};\n")
    }
}

fn dart_optional_expression(value: &str, converted: &str) -> String {
    let inline = format!("{value} == null ? null : {converted}");
    if inline.len() <= 64 {
        inline
    } else {
        format!("{value} == null\n      ? null\n      : {converted}")
    }
}

fn snake_to_lower_camel(value: &str) -> String {
    let mut output = String::new();
    let mut uppercase = false;
    for character in value.chars() {
        if character == '_' {
            uppercase = true;
        } else if uppercase {
            output.push(character.to_ascii_uppercase());
            uppercase = false;
        } else {
            output.push(character);
        }
    }
    output
}

fn lower_camel(value: &str) -> String {
    let mut characters = value.chars();
    match characters.next() {
        Some(first) => first.to_ascii_lowercase().to_string() + characters.as_str(),
        None => String::new(),
    }
}

fn pascal_case(value: &str) -> String {
    value
        .split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut characters = part.chars();
            characters
                .next()
                .map(char::to_uppercase)
                .into_iter()
                .flatten()
                .chain(characters)
                .collect::<String>()
        })
        .collect()
}

fn render_method_declaration(output: &mut String, operation: &Operation) {
    if let Some(doc) = adapter_doc(operation.language_name) {
        output.push_str(doc);
    }
    let declaration = format!(
        "  Future<{}> {}({});\n",
        dart_type(operation.result),
        operation.language_name,
        dart_arguments(operation.arguments)
    );
    if declaration.trim_end().chars().count() <= 80 || operation.arguments.len() < 2 {
        output.push_str(&declaration);
    } else {
        output.push_str(&format!(
            "  Future<{}> {}(\n{}  );\n",
            dart_type(operation.result),
            operation.language_name,
            operation
                .arguments
                .iter()
                .map(|argument| format!("    {},\n", dart_argument(argument)))
                .collect::<String>()
        ));
    }
}

fn render_unsupported_method(output: &mut String, schema: &Schema, operation: &Operation) {
    let feature = schema
        .identifier("Feature")
        .and_then(|identifier| {
            identifier
                .variants
                .iter()
                .find(|variant| variant.wire_name == operation.feature)
        })
        .unwrap_or_else(|| panic!("unknown Feature wire name: {}", operation.feature));
    let signature = format!(
        "  Future<{}> {}({})",
        dart_type(operation.result),
        operation.language_name,
        dart_arguments(operation.arguments),
    );
    let call = format!("_unsupported(Feature.{})", dart_name(feature.rust_name));
    if signature.chars().count() + call.chars().count() + 5 <= 80 {
        output.push_str(&format!("  @override\n{signature} => {call};\n"));
    } else {
        output.push_str(&format!("  @override\n{signature} =>\n      {call};\n"));
    }
}

fn render_client_method(
    operation: &Operation,
    method: &maxt_bindings_common::schema::ClientMethod,
) -> String {
    let signature = format!(
        "{}  Future<{}> {}({})",
        client_doc(method.name).unwrap_or_default(),
        dart_type(operation.result),
        method.name,
        dart_arguments(method.arguments)
    );
    let body = match method.name {
        "trades" => {
            " async =>\n      _native.trades(market, checkedUint32(limit, field: 'limit'));"
        }
        "orderBook" => {
            " async =>\n      _native.orderBook(market, checkedUint32(depth, field: 'depth'));"
        }
        "candles" => {
            " async {\n    checkedUint32(request.limit, field: 'limit');\n    return _native.candles(request);\n  }"
        }
        "subscribe" => " =>\n      subscribeWith(subscription, defaultStreamConfig());",
        "subscribeWith" => {
            return format!(
                "{}  Future<MarketStream> subscribeWith(\n    Subscription subscription,\n    StreamConfig config,\n  ) async {{\n    validateStreamConfigIntegers(config);\n    return _native.subscribe(subscription, config);\n  }}\n",
                client_doc(method.name).unwrap_or_default()
            );
        }
        "openOrders" => " => _native.openOrders();",
        "openOrdersOn" => " => _native.openOrders(market);",
        "subscribeAccount" => " =>\n      subscribeAccountWith(defaultStreamConfig());",
        "subscribeAccountWith" => {
            " async {\n    validateStreamConfigIntegers(config);\n    return _native.subscribeAccount(config);\n  }"
        }
        "cancelOrder" => " =>\n      _native.cancelOrder(market, orderId);",
        "positions" => " async =>\n      _openPositions(await _native.positions());",
        "positionsOn" => " async =>\n      _openPositions(await _native.positions(market));",
        "fundingRates" | "fundingPayments" => {
            return format!(
                "{signature} async {{\n    checkedUint32(request.limit, field: 'limit');\n    return _native.{}(request);\n  }}\n",
                method.native_name
            );
        }
        _ => {
            let arguments = method
                .arguments
                .iter()
                .map(|argument| argument.name)
                .collect::<Vec<_>>()
                .join(", ");
            return format!(
                "{signature} => _native.{}({arguments});\n",
                method.native_name
            );
        }
    };
    format!("{signature}{body}\n")
}

fn adapter_doc(name: &str) -> Option<&'static str> {
    match name {
        "trades" => {
            Some("  /// 최근 체결을 최신순으로 반환하며, `limit`은 요청할 최대 개수입니다.\n")
        }
        "orderBook" => Some(
            "  /// 호가창 스냅샷을 반환하며, `depth`는 매수·매도 각 측의 최대 단계 수입니다.\n",
        ),
        "candles" => Some("  /// [CandleRequest] 조건에 맞는 캔들을 오래된 순서로 반환합니다.\n"),
        "subscribe" => Some(
            "  /// 시장 데이터를 구독합니다. 사용 후 [CloseableStream.close]를 호출해야 합니다.\n",
        ),
        _ => None,
    }
}

fn client_doc(name: &str) -> Option<&'static str> {
    match name {
        "trades" | "orderBook" | "candles" => adapter_doc(name),
        "subscribe" => Some("  /// 기본 연결 설정으로 시장 데이터를 구독합니다.\n"),
        "subscribeWith" => Some("  /// 지정한 연결 설정으로 시장 데이터를 구독합니다.\n"),
        _ => None,
    }
}

fn dart_arguments(arguments: &[Argument]) -> String {
    let required = arguments
        .iter()
        .take_while(|argument| argument.default.is_none())
        .map(dart_argument)
        .collect::<Vec<_>>();
    let optional = arguments
        .iter()
        .skip(required.len())
        .map(dart_argument)
        .collect::<Vec<_>>();
    match (required.is_empty(), optional.is_empty()) {
        (_, true) => required.join(", "),
        (true, false) => format!("[{}]", optional.join(", ")),
        (false, false) => format!("{}, [{}]", required.join(", "), optional.join(", ")),
    }
}

fn dart_argument(argument: &Argument) -> String {
    format!("{} {}", dart_type(argument.ty), argument.name)
}

fn dart_type(ty: ApiType) -> String {
    match ty {
        ApiType::String => "String".into(),
        ApiType::Boolean => "bool".into(),
        ApiType::Number => "int".into(),
        ApiType::Named(name) => name.into(),
        ApiType::OptionalString => "String?".into(),
        ApiType::OptionalNumber => "int?".into(),
        ApiType::OptionalNamed(name) => format!("{name}?"),
        ApiType::List(name) | ApiType::PairList(_, name) => format!("List<{name}>"),
        ApiType::Page(name) => format!("Page<{name}>"),
        ApiType::Handle(name) => name.into(),
        ApiType::HandleToken(name) => name.into(),
        ApiType::MarketStream => "MarketStream".into(),
        ApiType::AccountStream => "AccountStream".into(),
        ApiType::Unit => "void".into(),
    }
}

fn render_closed_identifier(
    output: &mut String,
    identifier: &maxt_bindings_common::schema::Identifier,
) {
    let variants = identifier
        .variants
        .iter()
        .map(|variant| dart_name(variant.rust_name))
        .collect::<Vec<_>>()
        .join(", ");
    let declaration = format!("enum {} {{ {variants} }}", identifier.name);
    if declaration.chars().count() <= 80 {
        output.push_str(&format!("{declaration}\n\n"));
    } else {
        output.push_str(&format!("enum {} {{\n", identifier.name));
        for variant in identifier.variants {
            output.push_str(&format!("  {},\n", dart_name(variant.rust_name)));
        }
        output.push_str("}\n\n");
    }
    output.push_str(&format!(
        "extension {}WireName on {} {{\n  String get wireName => switch (this) {{\n",
        identifier.name, identifier.name
    ));
    for variant in identifier.variants {
        output.push_str(&format!(
            "    {}.{} => '{}',\n",
            identifier.name,
            dart_name(variant.rust_name),
            variant.wire_name
        ));
    }
    output.push_str("  };\n}\n");
}

fn render_open_identifier(
    output: &mut String,
    identifier: &maxt_bindings_common::schema::Identifier,
) {
    output.push_str(&format!(
        "final class {} {{\n  const {}._(this.providerName, [this._isOther = false]);\n\n",
        identifier.name, identifier.name
    ));
    for variant in identifier.variants {
        let name = dart_name(variant.rust_name);
        let declaration = format!("  static const {name} = {}._('{name}');", identifier.name);
        if declaration.chars().count() <= 80 {
            output.push_str(&format!("{declaration}\n"));
        } else {
            output.push_str(&format!(
                "  static const {name} = {}._(\n    '{name}',\n  );\n",
                identifier.name
            ));
        }
    }
    output.push_str(&format!(
        "\n  factory {}.other(String providerName) =>\n      {}._(providerName, true);\n\n  final String providerName;\n  final bool _isOther;\n\n  bool get isOther => _isOther;\n\n  @override\n  bool operator ==(Object other) =>\n      other is {} &&\n      _isOther == other._isOther &&\n      providerName == other.providerName;\n\n  @override\n  int get hashCode => Object.hash(_isOther, providerName);\n\n  @override\n  String toString() => providerName;\n}}\n",
        identifier.name, identifier.name, identifier.name
    ));
}

fn dart_name(rust_name: &str) -> String {
    let mut characters = rust_name.chars();
    characters
        .next()
        .map(char::to_lowercase)
        .into_iter()
        .flatten()
        .chain(characters)
        .collect()
}

fn list(values: &[&str], indent: &str) -> String {
    let joined = values
        .iter()
        .map(|value| format!("'{value}'"))
        .collect::<Vec<_>>()
        .join(", ");
    if joined.len() <= 60 {
        format!("<String>[{joined}]")
    } else {
        let items = values
            .iter()
            .map(|value| format!("{indent}  '{value}',\n"))
            .collect::<String>();
        format!("<String>[\n{items}{indent}]")
    }
}

#[cfg(test)]
mod tests {
    use maxt_bindings_common::schema::{ApiType, ProviderMethodKind, binding_schema};

    use super::{
        render_adapter_api, render_client_api, render_delegate_methods, render_identifiers,
        render_native_client_api, render_provider_guard, render_provider_methods,
        render_rust_adapter_dispatch, render_wire_shape_guard,
    };

    #[test]
    fn identifiers_are_rendered_from_the_schema() {
        let output = render_identifiers(&binding_schema());

        assert!(output.contains("enum BinanceMarket { spot, usdMFutures }"));
        assert!(output.contains("BinanceMarket.usdMFutures => 'usd_m'"));
        assert!(output.contains("final class HyperliquidLedgerKind"));
        assert!(output.contains(
            "static const vaultDistribution = HyperliquidLedgerKind._('vaultDistribution');"
        ));
        assert!(output.contains("factory HyperliquidLedgerKind.other(String providerName)"));
    }

    #[test]
    fn public_api_is_rendered_from_the_schema() {
        let schema = binding_schema();
        let adapter = render_adapter_api(&schema);
        let client = render_client_api(&schema);

        for operation in schema.adapter_operations {
            assert!(adapter.contains(&format!(" {}(", operation.language_name)));
            for method in operation.client_methods {
                assert!(client.contains(&format!(" {}(", method.name)));
            }
        }
        assert!(adapter.contains("unsupported(Feature.marginConfig)"));
        assert!(client.contains("checkedUint32(request.limit, field: 'limit')"));
        assert!(client.contains("validateStreamConfigIntegers(config)"));
    }

    #[test]
    fn native_client_api_is_rendered_from_the_schema() {
        let schema = binding_schema();
        let output = render_native_client_api(&schema);

        for operation in schema.adapter_operations.iter().filter(|operation| {
            !matches!(
                operation.result,
                ApiType::MarketStream | ApiType::AccountStream
            )
        }) {
            assert!(output.contains(&format!("pub async fn {}(", operation.rust_name)));
        }
        assert!(!output.contains("pub async fn subscribe("));
        assert!(output.contains("let request = request.try_into()?;"));
        assert!(output.contains("positions.retain(|position| !position.is_flat())"));
    }

    #[test]
    fn rust_adapter_dispatch_is_rendered_from_the_schema() {
        let schema = binding_schema();
        let output = render_rust_adapter_dispatch(&schema);

        for operation in schema.adapter_operations.iter().filter(|operation| {
            !matches!(
                operation.result,
                ApiType::MarketStream | ApiType::AccountStream
            )
        }) {
            assert!(output.contains(&format!(
                "CommonAdapterCall::{}",
                super::pascal_case(operation.rust_name)
            )));
        }
        assert!(output.contains("ExpectedReply::Unit"));
        assert!(output.contains("_ => None"));
    }

    #[test]
    fn provider_guard_is_rendered_from_the_schema() {
        let schema = binding_schema();
        let output = render_provider_guard(&schema);

        for provider in schema.providers {
            assert!(output.contains(provider.adapter));
            for constructor in provider.constructors {
                if constructor.name != "constructor" {
                    assert!(output.contains(constructor.name));
                }
            }
            for method in provider.methods {
                assert!(output.contains(method.name));
            }
        }
    }

    #[test]
    fn provider_methods_are_rendered_from_the_schema() {
        let schema = binding_schema();
        let output = render_provider_methods(&schema);

        for provider in schema.providers {
            for method in provider
                .methods
                .iter()
                .filter(|method| method.kind == ProviderMethodKind::Async)
            {
                assert!(output.contains(method.name));
            }
        }
    }

    #[test]
    fn wire_shape_guard_is_rendered_from_the_schema() {
        let output = render_wire_shape_guard(&binding_schema());

        assert!(output.contains("let WireTrade"));
        assert!(output.contains("timestamp_ns: _"));
        assert!(output.contains("WireFeature::OrderBookStream"));
        assert!(!output.contains("let WireStreamConfig"));
    }

    #[test]
    fn delegate_methods_are_rendered_from_the_schema() {
        let schema = binding_schema();
        let output = render_delegate_methods(&schema);

        for operation in schema.adapter_operations.iter().filter(|operation| {
            !matches!(
                operation.result,
                ApiType::MarketStream | ApiType::AccountStream
            )
        }) {
            assert!(output.contains(operation.language_name));
        }
    }
}
