use maxt_bindings_common::schema::{Provider, Schema};

pub(crate) fn render(schema: &Schema) -> String {
    format!(
        "# Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.\n\nEXCHANGES = ({},)\nFEATURES = ({},)\nERROR_VARIANTS = ({},)\nADAPTER_OPERATIONS = ({},)\nCLIENT_MEMBERS = ({},)\nPROVIDER_METHODS = {{\n{}}}\n",
        items(&schema.exchanges),
        items(&schema.features),
        items(schema.errors),
        items(
            &schema
                .adapter_operations
                .iter()
                .map(|value| value.rust_name)
                .collect::<Vec<_>>()
        ),
        owned_items(schema.client_members.iter().map(|value| snake_case(value))),
        schema
            .providers
            .iter()
            .map(render_provider)
            .collect::<String>(),
    )
}

pub(crate) fn render_identifiers(schema: &Schema) -> String {
    let mut output = String::from(
        r#"# Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.

from __future__ import annotations

from calendar import monthrange
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Optional

_I64_MIN = -(1 << 63)
_I64_MAX = (1 << 63) - 1
_UNIX_EPOCH = datetime(1970, 1, 1, tzinfo=timezone.utc)


def _is_i64(value: int) -> bool:
    return _I64_MIN <= value <= _I64_MAX
"#,
    );

    for identifier in schema.identifiers {
        output.push_str(&format!("\n\nclass {}(str, Enum):\n", identifier.name));
        for variant in identifier.variants {
            output.push_str(&format!(
                "    {} = \"{}\"\n",
                snake_case(variant.rust_name).to_ascii_uppercase(),
                variant.wire_name,
            ));
        }
        output.push_str(identifier_helpers(identifier.name));
        if identifier.open {
            output.push_str(&format!(
                r#"
    @classmethod
    def _missing_(cls, value: object) -> {}:
"#,
                identifier.name,
            ));
            output.push_str(
                r#"        if not isinstance(value, str):
            raise ValueError(value)
        member = str.__new__(cls, value)
        member._name_ = "OTHER"
        member._value_ = value
        return member
"#,
            );
        }
    }

    for identifier in schema.identifiers {
        let module = if identifier.name == "ExchangeErrorKind" {
            "maxt._api"
        } else {
            "maxt.models"
        };
        output.push_str(&format!(
            "\n{}.__module__ = \"{}\"",
            identifier.name, module
        ));
    }
    output.push_str("\n\n__all__ = [\n");
    for identifier in schema.identifiers {
        output.push_str(&format!("    \"{}\",\n", identifier.name));
    }
    output.push_str("]\n");
    output
}

fn identifier_helpers(name: &str) -> &'static str {
    match name {
        "Exchange" => {
            r#"
    def display_name(self) -> str:
        return self.value.capitalize()
"#
        }
        "Feature" => {
            r#"
    def needs_credentials(self) -> bool:
        return self.value in {
            "balances",
            "open_orders",
            "account_stream",
            "trading",
            "positions",
            "margin",
            "funding_payments",
            "margin_config",
            "reduce_only_orders",
        }

    def is_derivatives_only(self) -> bool:
        return self.value in {
            "positions",
            "margin",
            "funding_rates",
            "funding_payments",
            "margin_config",
            "reduce_only_orders",
        }
"#
        }
        "MarketKind" => {
            r#"
    def is_derivative(self) -> bool:
        return self.value == "perpetual"
"#
        }
        "Side" => {
            r#"
    def flip(self) -> Side:
        return Side.SELL if self is Side.BUY else Side.BUY
"#
        }
        "Interval" => {
            r#"
    def as_secs(self) -> Optional[int]:
        unit = self.value.rstrip("0123456789")
        if unit == "month":
            return None
        count = int(self.value[len(unit):])
        return count * {
            "sec": 1,
            "min": 60,
            "hour": 3_600,
            "day": 86_400,
            "week": 604_800,
        }[unit]

    def advance(self, timestamp_ns: int, count: int) -> Optional[int]:
        if not _is_i64(timestamp_ns) or not _is_i64(count):
            return None

        seconds = self.as_secs()
        if seconds is not None:
            span = seconds * 1_000_000_000 * count
            if not _is_i64(span):
                return None
            result = timestamp_ns + span
            return result if _is_i64(result) else None

        if abs(count) > (1 << 32) - 1:
            return None

        whole_seconds, nanoseconds = divmod(timestamp_ns, 1_000_000_000)
        current = _UNIX_EPOCH + timedelta(seconds=whole_seconds)
        month_index = current.year * 12 + current.month - 1 + count
        year, zero_based_month = divmod(month_index, 12)
        month = zero_based_month + 1
        if not 1 <= year <= 9999:
            return None

        moved = datetime(
            year,
            month,
            min(current.day, monthrange(year, month)[1]),
            current.hour,
            current.minute,
            current.second,
            tzinfo=timezone.utc,
        )
        elapsed = moved - _UNIX_EPOCH
        result = (
            (elapsed.days * 86_400 + elapsed.seconds) * 1_000_000_000
            + nanoseconds
        )
        return result if _is_i64(result) else None
"#
        }
        "OrderStatus" => {
            r#"
    def is_live(self) -> bool:
        return self.value in {"accepted", "open", "partially_filled"}
"#
        }
        "ExchangeErrorKind" => {
            r#"
    def is_retryable(self) -> bool:
        return self.value in {"rate_limited", "unavailable"}
"#
        }
        _ => "",
    }
}

pub(crate) fn snake_case(value: &str) -> String {
    let mut output = String::with_capacity(value.len());
    for character in value.chars() {
        if character.is_ascii_uppercase() {
            if !output.is_empty() {
                output.push('_');
            }
            output.push(character.to_ascii_lowercase());
        } else {
            output.push(character);
        }
    }
    output
}

fn items(values: &[&str]) -> String {
    values
        .iter()
        .map(|value| format!("\"{value}\""))
        .collect::<Vec<_>>()
        .join(", ")
}

fn owned_items(values: impl IntoIterator<Item = String>) -> String {
    values
        .into_iter()
        .map(|value| format!("\"{value}\""))
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_provider(provider: &Provider) -> String {
    format!(
        "    \"{}\": ({},),\n",
        provider.exchange,
        items(
            &provider
                .methods
                .iter()
                .map(|method| method.rust_name)
                .collect::<Vec<_>>()
        ),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use maxt_bindings_common::schema::binding_schema;

    #[test]
    fn generated_identifiers_cover_closed_and_open_enums() {
        let output = render_identifiers(&binding_schema());

        assert!(output.contains("class Exchange(str, Enum):\n    UPBIT = \"upbit\""));
        assert!(output.contains("class OrderStatus(str, Enum):"));
        assert!(output.contains("class HyperliquidLedgerKind(str, Enum):"));
        assert!(output.contains("def _missing_(cls, value: object) -> HyperliquidLedgerKind:"));
        assert!(output.contains("class ExchangeErrorKind(str, Enum):"));
        assert!(output.contains("Exchange.__module__ = \"maxt.models\""));
        assert!(output.contains("ExchangeErrorKind.__module__ = \"maxt._api\""));
    }
}
