use maxt_bindings_common::schema::{
    ApiType, Argument, Field, Provider, ProviderMethod, ProviderMethodKind, Schema, Type, Variant,
    uses_generated_native_provider_bridge,
};

use crate::typescript_models::provider_wire_model_names;

/// Renders the output-only Rust wire DTOs required by the schema-selected
/// provider methods. The TypeScript runtime serializes these DTOs as JSON.
pub(crate) fn render_convert(schema: &Schema) -> String {
    let mut output =
        String::from("// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.\n\n");
    for name in provider_wire_model_names(schema) {
        let wire = format!("{name}Wire");
        if let Some(record) = schema.records.iter().find(|record| record.name == wire) {
            output.push_str(&render_record(schema, &name, &record.fields));
        } else if let Some(union) = schema.unions.iter().find(|union| union.name == wire) {
            output.push_str(&render_union(schema, &name, &union.variants));
        } else {
            panic!("generated TypeScript provider model {name} has no schema shape");
        }
    }
    output
}

/// Renders the native version checked by Node and WebAssembly loaders.
pub(crate) fn render_version(schema: &Schema) -> String {
    format!(
        "// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.\n\n#[cfg(not(target_arch = \"wasm32\"))]\n#[napi]\npub const NATIVE_API_VERSION: u32 = {};\n\n#[cfg(target_arch = \"wasm32\")]\n#[wasm_bindgen(inline_js = \"export const NATIVE_API_VERSION = {};\")]\nextern \"C\" {{\n    #[wasm_bindgen(thread_local_v2, reexport)]\n    static NATIVE_API_VERSION: JsValue;\n}}\n",
        schema.native_api_version, schema.native_api_version
    )
}

/// Renders the Node and WebAssembly entry points for the fixed provider batch.
/// Method signatures, argument conversions, and result conversions are all
/// derived from the same schema entries as the public TypeScript API.
pub(crate) fn render_native(schema: &Schema) -> String {
    let mut output =
        String::from("// Generated by `cargo run -p maxt-bindings-codegen`. Do not edit.\n\n");
    for provider in schema.providers {
        let methods = selected_methods(provider);
        if methods.is_empty() {
            continue;
        }
        let native = native_type(provider);
        output.push_str(&format!(
            "#[cfg_attr(test, allow(dead_code, reason = \"생성된 네이티브 메서드는 테스트 빌드에서 제외됩니다\"))]\nimpl {native} {{\n"
        ));
        for method in &methods {
            output.push_str(&render_internal_method(provider, method));
        }
        if methods.iter().any(has_stream_result) {
            output.push_str(&render_stream_registry_methods());
        }
        output.push_str("}\n\n");

        output.push_str(&format!(
            "#[cfg(all(not(test), not(target_arch = \"wasm32\")))]\n#[napi]\nimpl {native} {{\n"
        ));
        for method in &methods {
            output.push_str(&render_napi_method(method));
        }
        if methods.iter().any(has_stream_result) {
            output.push_str(&render_napi_stream_registry_methods());
        }
        output.push_str("}\n\n");

        output.push_str(&format!(
            "#[cfg(target_arch = \"wasm32\")]\n#[wasm_bindgen]\nimpl {native} {{\n"
        ));
        for method in &methods {
            output.push_str(&render_wasm_method(method));
        }
        if methods.iter().any(has_stream_result) {
            output.push_str(&render_wasm_stream_registry_methods());
        }
        output.push_str("}\n\n");
    }
    output.push_str(&render_stream_close_impls(schema));
    output
}

fn render_stream_close_impls(schema: &Schema) -> String {
    let mut streams = Vec::new();
    for provider in schema.providers {
        for method in selected_methods(provider) {
            let event = match method.result {
                ApiType::ProviderMarketStream(event) | ApiType::ProviderAccountStream(event) => {
                    event
                }
                _ => continue,
            };
            let base = event.strip_suffix("Event").unwrap_or(event);
            let stream = if base.ends_with("Stream") {
                base.to_owned()
            } else {
                format!("{base}Stream")
            };
            if !streams.iter().any(|existing| existing == &stream) {
                streams.push(stream);
            }
        }
    }
    streams
        .into_iter()
        .map(|stream| {
            format!(
                "impl crate::stream::ProviderStreamClose for maxt::{stream} {{\n    fn close_provider(&mut self) -> std::pin::Pin<Box<dyn std::future::Future<Output = maxt::Result<()>> + Send + '_>> {{\n        Box::pin(maxt::{stream}::close(self))\n    }}\n}}\n\n"
            )
        })
        .collect()
}

fn selected_methods(provider: &Provider) -> Vec<&ProviderMethod> {
    provider
        .methods
        .iter()
        .filter(|method| {
            method.kind == ProviderMethodKind::Async
                && (uses_generated_native_provider_bridge(provider.exchange, method.rust_name)
                    || matches!(
                        method.result,
                        ApiType::ProviderMarketStream(_) | ApiType::ProviderAccountStream(_)
                    ))
        })
        .collect()
}

fn native_type(provider: &Provider) -> String {
    format!("Native{}", pascal_case(provider.exchange))
}

fn render_internal_method(provider: &Provider, method: &ProviderMethod) -> String {
    let arguments = method
        .arguments
        .iter()
        .map(|argument| format!("        {}: maxt::Result<String>", rust_name(argument.name)))
        .collect::<Vec<_>>();
    let signature = if arguments.is_empty() {
        String::new()
    } else {
        format!(",\n{}", arguments.join(",\n"))
    };
    let parsed = method
        .arguments
        .iter()
        .map(render_parse_argument)
        .collect::<Vec<_>>();
    let result = render_provider_call(provider, method, &parsed);
    format!(
        "    async fn {}(&self{signature}) -> Value {{\n{result}    }}\n\n",
        method.rust_name
    )
}

struct ParsedArgument {
    name: String,
    expression: String,
    call: String,
}

fn render_parse_argument(argument: &Argument) -> ParsedArgument {
    let name = rust_name(argument.name);
    let expression = match argument.ty {
        ApiType::Named("Timestamp") => format!(
            "parse_text::<String>({name}, \"{}\").and_then(|value| timestamp_from_wire(&value, \"{}\"))",
            argument.name, argument.name
        ),
        ApiType::Named(model) => format!(
            "parse_wire::<maxt::{model}, crate::convert::Wire{model}>({name}, \"{}\")",
            argument.name
        ),
        ApiType::OptionalNamed("Timestamp") => format!(
            "parse_text::<Option<String>>({name}, \"{}\").and_then(|value| value.as_deref().map(|value| timestamp_from_wire(value, \"{}\")).transpose())",
            argument.name, argument.name
        ),
        ApiType::OptionalNamed(model) => format!(
            "parse_text::<Option<crate::convert::Wire{model}>>({name}, \"{}\").and_then(|value| value.map(TryInto::try_into).transpose())",
            argument.name
        ),
        ApiType::String => format!("parse_text::<String>({name}, \"{}\")", argument.name),
        ApiType::OptionalString => format!(
            "parse_text::<Option<String>>({name}, \"{}\")",
            argument.name
        ),
        ApiType::Number => format!("parse_text::<u32>({name}, \"{}\")", argument.name),
        ApiType::OptionalNumber => {
            format!("parse_text::<Option<u32>>({name}, \"{}\")", argument.name)
        }
        ApiType::Boolean => format!("parse_text::<bool>({name}, \"{}\")", argument.name),
        other => panic!(
            "generated TypeScript provider bridge has unsupported argument {other:?}: {}",
            argument.name
        ),
    };
    let call = match argument.ty {
        ApiType::Named("Timestamp")
        | ApiType::Number
        | ApiType::OptionalNumber
        | ApiType::Boolean => name.clone(),
        ApiType::OptionalNamed("Timestamp") | ApiType::OptionalNamed(_) => {
            format!("{name}.as_ref()")
        }
        ApiType::OptionalString => format!("{name}.as_deref()"),
        _ => format!("&{name}"),
    };
    ParsedArgument {
        name,
        expression,
        call,
    }
}

fn render_provider_call(
    provider: &Provider,
    method: &ProviderMethod,
    arguments: &[ParsedArgument],
) -> String {
    let call_arguments = arguments
        .iter()
        .map(|argument| argument.call.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    let call = format!("self.adapter.{}({call_arguments}).await", method.rust_name);
    let success = match method.result {
        ApiType::Named(model) => {
            format!("{call}.and_then(TryInto::<crate::convert::Wire{model}>::try_into)")
        }
        ApiType::List(model) => format!("wire_vec::<_, crate::convert::Wire{model}>({call})"),
        ApiType::Page(model) => format!(
            "{call}.and_then(TryInto::<crate::convert::WirePage<crate::convert::Wire{model}>>::try_into)"
        ),
        ApiType::ProviderMarketStream(event) | ApiType::ProviderAccountStream(event) => {
            let kind = if matches!(method.result, ApiType::ProviderAccountStream(_)) {
                "account"
            } else {
                "market"
            };
            format!(
                "match {call} {{\n                Ok(stream) => self.streams.insert_provider(\n                    stream,\n                    \"{}_{}\",\n                    crate::stream::provider_stream_item::<maxt::{event}, crate::convert::Wire{event}>,\n                ).await,\n                Err(error) => Err(error),\n            }}",
                provider.exchange, kind
            )
        }
        other => panic!(
            "generated TypeScript provider bridge has unsupported result {other:?}: {}.{}",
            provider.exchange, method.rust_name
        ),
    };
    if arguments.is_empty() {
        return format!("        outcome({success})\n");
    }
    let setups = arguments
        .iter()
        .map(|argument| format!("        let {} = {};\n", argument.name, argument.expression))
        .collect::<String>();
    if arguments.len() == 1 {
        let argument = &arguments[0];
        return format!(
            "{setups}        let result = match {} {{\n            Ok({}) => {success},\n            Err(error) => Err(error),\n        }};\n        outcome(result)\n",
            argument.name, argument.name,
        );
    }
    let patterns = arguments
        .iter()
        .map(|argument| format!("Ok({})", argument.name))
        .collect::<Vec<_>>()
        .join(", ");
    let mut errors = Vec::new();
    for index in 0..arguments.len() {
        let pattern = arguments
            .iter()
            .enumerate()
            .map(|(position, _)| {
                if position == index {
                    "Err(error)".to_owned()
                } else {
                    "_".to_owned()
                }
            })
            .collect::<Vec<_>>()
            .join(", ");
        errors.push(format!("            ({pattern}) => Err(error),"));
    }
    format!(
        "{setups}        let result = match ({}) {{\n            ({patterns}) => {success},\n{}\n        }};\n        outcome(result)\n",
        arguments
            .iter()
            .map(|argument| argument.name.as_str())
            .collect::<Vec<_>>()
            .join(", "),
        errors.join("\n")
    )
}

fn render_stream_registry_methods() -> String {
    "    async fn stream_next(&self, id: maxt::Result<String>) -> Value {\n        let result = match parse_text::<String>(id, \"stream_id\") {\n            Ok(id) => self.streams.next(&id).await,\n            Err(error) => Err(error),\n        };\n        outcome(result)\n    }\n\n    async fn stream_close(&self, id: maxt::Result<String>) -> Value {\n        let result = match parse_text::<String>(id, \"stream_id\") {\n            Ok(id) => self.streams.close(&id).await,\n            Err(error) => Err(error),\n        };\n        outcome(result.map(|()| Value::Null))\n    }\n\n".to_owned()
}

fn render_napi_method(method: &ProviderMethod) -> String {
    let arguments = method
        .arguments
        .iter()
        .map(|argument| format!("        {}: NativeJsonText<'env>", rust_name(argument.name)))
        .collect::<Vec<_>>();
    let signature = if arguments.is_empty() {
        String::new()
    } else {
        format!(",\n{}", arguments.join(",\n"))
    };
    let setup = method
        .arguments
        .iter()
        .map(|argument| {
            let name = rust_name(argument.name);
            format!(
                "        let {name} = native_json_text({name}, \"{}\");\n",
                argument.name
            )
        })
        .collect::<String>();
    let call_arguments = method
        .arguments
        .iter()
        .map(|argument| rust_name(argument.name))
        .collect::<Vec<_>>()
        .join(", ");
    let ts_arguments = method
        .arguments
        .iter()
        .map(|argument| format!("{}: string", argument.name))
        .collect::<Vec<_>>()
        .join(", ");
    let attribute = if ts_arguments.is_empty() {
        format!("    #[napi(js_name = \"{}\")]\n", method.name)
    } else {
        format!(
            "    #[napi(js_name = \"{}\", ts_args_type = \"{}\")]\n",
            method.name, ts_arguments
        )
    };
    format!(
        "{attribute}    pub fn {}_native<'env>(&self, env: &'env Env{signature}) -> napi::Result<PromiseRaw<'env, Value>> {{\n        let this = self.clone();\n{setup}        spawn_native(env, async move {{ this.{}({call_arguments}).await }})\n    }}\n\n",
        method.rust_name, method.rust_name
    )
}

fn render_napi_stream_registry_methods() -> String {
    "    #[napi(js_name = \"streamNext\", ts_args_type = \"id: string\")]\n    pub fn stream_next_native<'env>(&self, env: &'env Env, id: NativeJsonText<'env>) -> napi::Result<PromiseRaw<'env, Value>> {\n        let this = self.clone();\n        let id = native_json_text(id, \"stream_id\");\n        spawn_native(env, async move { this.stream_next(id).await })\n    }\n\n    #[napi(js_name = \"streamClose\", ts_args_type = \"id: string\")]\n    pub fn stream_close_native<'env>(&self, env: &'env Env, id: NativeJsonText<'env>) -> napi::Result<PromiseRaw<'env, Value>> {\n        let this = self.clone();\n        let id = native_json_text(id, \"stream_id\");\n        spawn_native(env, async move { this.stream_close(id).await })\n    }\n\n".to_owned()
}

fn render_wasm_method(method: &ProviderMethod) -> String {
    let arguments = method
        .arguments
        .iter()
        .map(|argument| format!("{}: String", rust_name(argument.name)))
        .collect::<Vec<_>>();
    let signature = if arguments.is_empty() {
        String::new()
    } else {
        format!(", {}", arguments.join(", "))
    };
    let call_arguments = method
        .arguments
        .iter()
        .map(|argument| format!("Ok({})", rust_name(argument.name)))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "    #[wasm_bindgen(js_name = \"{}\")]\n    pub async fn {}_wasm(&self{signature}) -> JsValue {{\n        crate::web::value(self.{}({call_arguments}).await)\n    }}\n\n",
        method.name, method.rust_name, method.rust_name
    )
}

fn render_wasm_stream_registry_methods() -> String {
    "    #[wasm_bindgen(js_name = \"streamNext\")]\n    pub async fn stream_next_wasm(&self, id: String) -> JsValue {\n        crate::web::value(self.stream_next(Ok(id)).await)\n    }\n\n    #[wasm_bindgen(js_name = \"streamClose\")]\n    pub async fn stream_close_wasm(&self, id: String) -> JsValue {\n        crate::web::value(self.stream_close(Ok(id)).await)\n    }\n\n".to_owned()
}

fn has_stream_result(method: &&ProviderMethod) -> bool {
    matches!(
        method.result,
        ApiType::ProviderMarketStream(_) | ApiType::ProviderAccountStream(_)
    )
}

fn render_record(schema: &Schema, name: &str, fields: &[Field]) -> String {
    let declarations = fields
        .iter()
        .map(|field| format!("    pub(crate) {}: {},\n", field.name, wire_type(&field.ty)))
        .collect::<String>();
    let values = fields
        .iter()
        .map(|field| {
            format!(
                "            {}: {},\n",
                field.name,
                core_to_wire(schema, &field.ty, &format!("value.{}", field.name))
            )
        })
        .collect::<String>();
    format!(
        "#[derive(Debug, Clone, PartialEq, Eq, Serialize)]\n#[serde(deny_unknown_fields)]\npub(crate) struct Wire{name} {{\n{declarations}}}\n\nimpl TryFrom<maxt::{name}> for Wire{name} {{\n    type Error = Error;\n\n    fn try_from(value: maxt::{name}) -> Result<Self, Self::Error> {{\n        Ok(Self {{\n{values}        }})\n    }}\n}}\n\n"
    )
}

fn render_union(schema: &Schema, name: &str, variants: &[Variant]) -> String {
    let declarations = variants
        .iter()
        .map(|variant| {
            let variant_name = pascal_case(variant.name);
            match variant.fields.as_slice() {
                [] => format!("    {variant_name},\n"),
                fields => {
                    let fields = fields
                        .iter()
                        .map(|field| format!("        {}: {},\n", field.name, wire_type(&field.ty)))
                        .collect::<String>();
                    format!("    {variant_name} {{\n{fields}    }},\n")
                }
            }
        })
        .collect::<String>();
    let arms = variants
        .iter()
        .map(|variant| render_union_arm(schema, name, variant))
        .collect::<String>();
    format!(
        "#[derive(Debug, Clone, PartialEq, Eq, Serialize)]\n#[serde(tag = \"kind\", rename_all = \"snake_case\")]\npub(crate) enum Wire{name} {{\n{declarations}}}\n\nimpl TryFrom<maxt::{name}> for Wire{name} {{\n    type Error = Error;\n\n    fn try_from(value: maxt::{name}) -> Result<Self, Self::Error> {{\n        match value {{\n{arms}            _ => Err(Error::adapter(\"new {name} variant requires a generated TypeScript wire variant\")),\n        }}\n    }}\n}}\n\n"
    )
}

fn render_union_arm(schema: &Schema, name: &str, variant: &Variant) -> String {
    let variant_name = pascal_case(variant.name);
    match variant.fields.as_slice() {
        [] => format!("            maxt::{name}::{variant_name} => Ok(Self::{variant_name}),\n"),
        [field] if field.name == "value" => format!(
            "            maxt::{name}::{variant_name}(value) => Ok(Self::{variant_name} {{ value: {} }}),\n",
            core_to_wire(schema, &field.ty, "value")
        ),
        fields => {
            let source = fields
                .iter()
                .map(|field| field.name)
                .collect::<Vec<_>>()
                .join(", ");
            let values = fields
                .iter()
                .map(|field| {
                    format!(
                        "                {}: {},\n",
                        field.name,
                        core_to_wire(schema, &field.ty, field.name)
                    )
                })
                .collect::<String>();
            format!(
                "            maxt::{name}::{variant_name} {{ {source} }} => Ok(Self::{variant_name} {{\n{values}            }}),\n"
            )
        }
    }
}

fn wire_type(ty: &Type) -> String {
    match ty {
        Type::String | Type::Decimal | Type::Timestamp | Type::UnsignedInteger => {
            "String".to_owned()
        }
        Type::Boolean => "bool".to_owned(),
        Type::Number => "u32".to_owned(),
        Type::Named(name) => format!("Wire{}", name.strip_suffix("Wire").unwrap_or(name)),
        Type::Optional(inner) => format!("Option<{}>", wire_type(inner)),
        Type::List(inner) => format!("Vec<{}>", wire_type(inner)),
        Type::Tuple(items) => format!(
            "({})",
            items.iter().map(wire_type).collect::<Vec<_>>().join(", ")
        ),
        Type::Identifier(name) => panic!(
            "generated TypeScript provider output must use an existing core wire record for identifier {name}"
        ),
    }
}

fn core_to_wire(schema: &Schema, ty: &Type, value: &str) -> String {
    match ty {
        Type::String | Type::Boolean | Type::Number => value.to_owned(),
        Type::UnsignedInteger => format!("{value}.to_string()"),
        Type::Decimal => format!("decimal_to_wire({value})"),
        Type::Timestamp => format!("timestamp_to_wire({value})"),
        Type::Named(_) => format!("{value}.try_into()?"),
        Type::Optional(inner) => match inner.as_ref() {
            Type::String | Type::Boolean | Type::Number => value.to_owned(),
            Type::UnsignedInteger => format!("{value}.map(|value| value.to_string())"),
            Type::Decimal => format!("{value}.map(decimal_to_wire)"),
            Type::Timestamp => format!("{value}.map(timestamp_to_wire)"),
            Type::Named(_) => format!("{value}.map(TryInto::try_into).transpose()?"),
            Type::List(inner) => format!(
                "{value}.map(|values| values.into_iter().map(|value| {}).collect::<Result<_, _>>()).transpose()?",
                core_to_wire(schema, inner, "value")
            ),
            Type::Identifier(name) => panic!(
                "generated TypeScript provider output must use an existing core wire record for identifier {name}"
            ),
            Type::Optional(_) | Type::Tuple(_) => {
                panic!(
                    "generated TypeScript provider outputs do not use nested optionals or tuple optionals"
                )
            }
        },
        Type::List(inner) => match inner.as_ref() {
            Type::String | Type::Boolean | Type::Number => value.to_owned(),
            Type::UnsignedInteger => {
                format!("{value}.into_iter().map(|value| value.to_string()).collect()")
            }
            Type::Decimal => format!("{value}.into_iter().map(decimal_to_wire).collect()"),
            Type::Timestamp => format!("{value}.into_iter().map(timestamp_to_wire).collect()"),
            Type::Named(_) => {
                format!("{value}.into_iter().map(TryInto::try_into).collect::<Result<_, _>>()?")
            }
            Type::Identifier(name) => panic!(
                "generated TypeScript provider output must use an existing core wire record for identifier {name}"
            ),
            Type::Optional(_) | Type::List(_) | Type::Tuple(_) => {
                panic!("generated TypeScript provider outputs do not use nested complex lists")
            }
        },
        Type::Identifier(name) => panic!(
            "generated TypeScript provider output must use an existing core wire record for identifier {name}"
        ),
        Type::Tuple(_) => panic!("generated TypeScript provider outputs do not use tuples"),
    }
}

fn pascal_case(value: &str) -> String {
    let mut output = String::new();
    let mut upper = true;
    for character in value.chars() {
        if character == '_' {
            upper = true;
        } else if upper {
            output.push(character.to_ascii_uppercase());
            upper = false;
        } else {
            output.push(character);
        }
    }
    output
}

fn rust_name(name: &str) -> String {
    let mut value = String::new();
    for character in name.chars() {
        if character.is_ascii_uppercase() {
            if !value.is_empty() {
                value.push('_');
            }
            value.push(character.to_ascii_lowercase());
        } else {
            value.push(character);
        }
    }
    match value.as_str() {
        "self" | "crate" | "super" | "type" | "match" | "ref" | "move" | "from" | "where"
        | "loop" | "async" | "await" => format!("r#{value}"),
        _ => value,
    }
}

#[cfg(test)]
mod tests {
    use maxt_bindings_common::schema::binding_schema;

    use super::{render_convert, render_native, render_version};

    #[test]
    fn fixed_provider_methods_have_generated_native_paths() {
        let schema = binding_schema();
        let native = render_native(&schema);
        let convert = render_convert(&schema);
        for expected in [
            "async fn test_order_detail",
            "async fn order_book_snapshot",
            "async fn all_mids_detail",
            "struct WireUpbitOrderResponse",
            "enum WireBinanceMarketEvent",
            "enum WireHyperliquidMarketEvent",
        ] {
            assert!(
                native.contains(expected) || convert.contains(expected),
                "missing {expected}"
            );
        }
    }

    #[test]
    fn native_version_comes_from_the_schema() {
        let schema = binding_schema();
        assert!(render_version(&schema).contains(&format!(
            "pub const NATIVE_API_VERSION: u32 = {};",
            schema.native_api_version
        )));
    }
}
